<?

	if ( !is_null($this->academiaDO) ){
		
?>
		<div class="ficha">
			<h3>Datos del usuario</h3>
			<p><strong>Nombre:</strong><span> <?= $this->usuarioDO->getVNombre() ?></span></p>
			<p><strong>Email:</strong><span> <?= $this->usuarioDO->getVEmail() ?></span></p>
		</div>
		
		<div class="ficha">
			<h3>Datos de la academia</h3>
			<p><strong>Nombre:</strong><span> <?= $this->academiaDO->getVNombre() ?></span></p>
			<p><strong>CIF:</strong><span> <?= $this->academiaDO->getVCif() ?></span></p>
			<p><strong>País:</strong><span> <?= $this->academiaDO->getTblPais()->getVNombre() ?></span></p>
			<p><strong>Provincia:</strong><span> <?= $this->academiaDO->getTblProvincia()->getVNombre() ?></span></p>
			<?
			
			$poblacion = $this->academiaDO->getVPoblacion();
			if ( !empty($poblacion) ){
				?><p><strong>Población:</strong><span> <?= $poblacion ?></span></p><?
			}
			
			$direccion = $this->academiaDO->getVDireccion();
			if ( !empty($direccion) ){
				?><p><strong>Dirección:</strong><span> <?= $direccion ?></span></p><?
			}
			
			$cp = $this->academiaDO->getVCp();
			if ( !empty($cp) ){
				?><p><strong>CP:</strong><span> <?= $cp ?></span></p><?
			}
			
			$telefono1 = $this->academiaDO->getVTelefono();
			if ( !empty($telefono1) ){
				?><p><strong>Teléfono 1:</strong><span> <?= $telefono1 ?></span></p><?
			}
			
			$telefono2 = $this->academiaDO->getVTelefono2();
			if ( !empty($telefono2) ){
				?><p><strong>Teléfono 2:</strong><span> <?= $telefono2 ?></span></p><?
			}
			
			$fax = $this->academiaDO->getVFax();
			if ( !empty($fax) ){
				?><p><strong>Fax:</strong><span> <?= $fax ?></span></p><?
			}
			
			?>
		</div>
<?
		
	} else {
		
		?><h3>No se ha encontrado la academia</h3><?
		
	}
?>