<h2>Listado de Academias</h2>

<table class="listado">
    <thead>
		<tr>
			<th><a href="/academia/index.html/?ob=nom&o=<?=$this->order?>" <?=( ($this->orderBy == 'nom')?'class="ordenado ' . $this->order . '"':'' )?> >Nombre</a></th>
			<th><a href="/academia/index.html/?ob=dir&o=<?=$this->order?>" <?=( ($this->orderBy == 'dir')?'class="ordenado ' . $this->order . '"':'' )?> >Dirección</a></th>
			<th><a href="/academia/index.html/?ob=pob&o=<?=$this->order?>" <?=( ($this->orderBy == 'pob')?'class="ordenado ' . $this->order . '"':'' )?> >Población</a></th>
			<th><a href="/academia/index.html/?ob=tel&o=<?=$this->order?>" <?=( ($this->orderBy == 'tel')?'class="ordenado ' . $this->order . '"':'' )?> >Teléfono</a></th>
			<?
			
				if ( $this->editar ){
					?><th>Eliminar</th>
					<th>Editar</th>
					<th>Duplicar</th><?	
				}
			
			?>
		</tr>
	</thead>
	<tbody>
		<?php
		
			$contador = 0;
			foreach ( $this->arrAcademiasDO as $academiaDO ){
				
			    //$academiaDO = new TblEmpresa($db);
				$clase = ( ($contador%2)==0 )?'':'class="alter"';
				$contador++;
				
				?>
				<tr	<?= $clase ?> >
					<td><a href="/academia/ficha.html/<?= $academiaDO->getIdEmpresa() ?>"><?= $academiaDO->getVNombre() ?></a></td>
					<td><?= $academiaDO->getVDireccion() ?></td>
					<td><?= $academiaDO->getVPoblacion() ?></td>
					<td><?= $academiaDO->getVTelefono() ?></td>
					<?
					
						if ( $this->editar ){
							?><td class="accion"><a href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea eliminar la academia <strong><?= $academiaDO->getVNombre() ?></strong>?','/academia/eliminar.html/<?= $academiaDO->getIdEmpresa() ?>')" class="btnEliminar" title="Eliminar Academia"><span>eliminar</span></a></td>
							<td class="accion"><a href="/academia/editar.html/<?= $academiaDO->getIdEmpresa() ?>" class="btnEditar" title="Editar Academia"><span>editar</span></a></td>
							<td class="accion"><a href="/academia/duplicar.html/<?= $academiaDO->getIdEmpresa() ?>" class="btnDuplicar" title="Duplicar Academia"><span>duplicar</span></a></td><?	
						}
					
					?>
				</tr>
				<?
				
			}
			
		?>
	</tbody>
</table>
<div id="paginadorContainer"><?= $this->paginador ?></div>