<?php
	$this->addJavascriptInclude('/js/convocatoria.js');
	
	if ( !is_null($this->popup) ){
    	echo '<script type="text/javascript">ventana' . ucfirst($this->popup['estado']) . '("' . $this->popup['titulo'] . '", "' . $this->popup['mensaje'] . '", "' . $this->popup['url'] . '");</script>'; 
	}
?>
    
<?
	
	if ( !is_null($this->convocatoriaDO) ){

?>
    <form id="editarConvocatoria" action="/convocatoria/editar.html/<?= $this->convocatoriaDO->getIdConvocatoria() ?>" method="post">
        <fieldset>
        
            <legend>Editar Convocatoria</legend>
        	
        	<input type="hidden" value="1" name="send" />
        	
            <div class="campo controlado">
                <label for="nombre">Nombre*</label>
                <input type="text" name="nombre" id="nombre" class="campoTexto" value="<?= $this->convocatoriaDO->getVNombre() ?>"/>
                <p id="errorNombre" class="errorInput"><?= $this->errorNombre ?></p>
            </div>
            
            <div class="campo controlado">
            	<label for="tipoConvocatoria">Tipo de Convocatoria*</label>
	            <select class="mediano" name="tipoConvocatoria" id="tipoConvocatoria">
	            	<option value=""></option>
					<?
					
					//Tipo Convocatoria
					foreach ( $this->tiposConvocatoriaIDX as $clave => $nombre) {
						
						?><option value="<?= $clave ?>" <?= ( ($this->convocatoriaDO->getFkTipoConvocatoria() == $clave)?'selected="selected"':'' ) ?>><?= $nombre ?></option><?
						
					}
					
					?>
				</select>
				<p id="errorTipoConvocatoria" class="errorInput"><?= $this->errorTipo ?></p>
			</div>
            
            <div class="campo controlado">
                <label for="presupuesto">Presupuesto*</label>
                <input class="campoTexto dinero" type="text" name="presupuesto" id="presupuesto" value="<?= NingenNumeric::decimalFormatoEuropeo($this->convocatoriaDO->getEPresupuesto(), 2) ?>"/>
                <p id="errorPresupuesto" class="errorInput"><?= $this->errorPresupuesto ?></p>
                <p class="tooltip" id="presupuestoTooltip">Utilice la coma(,) para separar decimales y el punto(.) para los miles</p>
            </div>
            
            <div class="campo">
                <label for="descripcion">Descripción</label>
                <textarea rows="5" cols="40" name="descripcion" id="descripcion"><?= $this->convocatoriaDO->getVDescripcion() ?></textarea>
            </div>
            
            <h3>Requisitos</h3>
            <div class="campo">
	            <?
	            
	 			foreach ( $this->requisitosIDX as $clave => $nombre ){
	            	$checked = '';
	            	
	            	if ( !is_null($this->requisitosConvocatoriaDO) ){
		 				
	            		foreach ( $this->requisitosConvocatoriaDO as $requisitoConvocatoriaDO ){
		 					if ( $requisitoConvocatoriaDO->getFkRequisito() == $clave ){
		 						$checked = 'checked="checked"';
		 					}
		 				}
		 				
	            	}
	 				
	            	?>
	            	<label class="alter" for="requisito_<?= $clave ?>"><?= $nombre ?></label>
	            	<input class="checkbox" type="checkbox" name="requisito_<?= $clave ?>" id="requisito_<?=$clave?>" <?=$checked?>/>
	            	<?
	            	
	            }
	            
	            ?>
            </div>
            
            <input class="oculto" type="submit" value="Guardar" />
            
            <noscript>
            	<div class="campo">
            		<input type="submit" value="Guardar" />
            	</div>
            </noscript>
            
        </fieldset>
    </form>
    <p>* Campos obligatorios</p>
    
<?
	
	} else {
	
	?><h3>No se ha encontrado la convocatoria</h3><?
	
	}

?>