<?

	if ( !is_null($this->convocatoriaDO) ){
		
?>
		<div class="ficha bloque">
		
			<h3>Datos generales</h3>
		
			<p><strong>Nombre</strong><span> <?= $this->convocatoriaDO->getVNombre() ?></span></p>
			<p><strong>Tipo</strong><span> <?= $this->tiposConvocatoriaIDX[$this->convocatoriaDO->getFkTipoConvocatoria()] ?></span></p>
			<p><strong>Presupuesto</strong><span> <?= OwlNumeric::decimalFormatoEuropeo($this->convocatoriaDO->getEPresupuesto(), 2) ?>€</span></p>
			<?
			
			$descripcion = $this->convocatoriaDO->getVDescripcion();
			if ( !empty($descripcion) ){
				?><p class="extended"><strong>Descripción</strong><span> <?= $descripcion ?></span></p><?
			}
			
			?>
		<?
		
		// Requisitos
		if ( !is_null($this->arrRequisitosConvocatoriaDO) ){
			
			?><p class="lista"><strong>Requisitos</strong></p><ul class="listaFicha"><?
			
			$reqARR = array();
			foreach ( $this->arrRequisitosConvocatoriaDO as $requisitoConvocatoriaDO ){
				
				$reqARR[] = $this->requisitosIDX[$requisitoConvocatoriaDO->getFkRequisito()];
				
			}
			
			if (count($reqARR) > 0){
				
				echo '<li>' . implode('</li><li>', $reqARR) . '</li>';
				
			}
			
			?></ul><?
			
		}
		
		?><div class="separadorH"></div>
		</div><?

		
        // Planes
        $arrPlanesDO = $this->convocatoriaDO->getTblPlans();
        if ( !empty($arrPlanesDO) ){

            ?><div class="bloque">
	            <h3>Planes presentados para esta convocatoria: </h3><?
	            
	            echo '<ul class="listaItemsFicha">';
	            
	            foreach ( $arrPlanesDO as $planDO ){
	                echo '<li><a href="/plan/ficha/' . $planDO->getIdPlan() . '" class="' . strtolower($this->estadosPlanIDX[$planDO->getFkEstadoPlan()]) . '">' . $planDO->getVNombre() . '</a></li>';
	            }
	            
	            echo '</ul>';
            
        }
        
        ?></div><?
        
        
        if ($this->documentosCOL){

        	?><div id="documentacion">
	        	<h3 class="conSubtitulo">Documentación seleccionada</h3>
	        	<p>Documentación que podrá ser generada para los planes y cursos que han sido presentados para esta convocatoria</p>
	        	
				<ul id="convocatoriaDoc"><?
				
					foreach ($this->documentosCOL as $documentoDO){
				
						?><li>
							<label><a href="/documento/ver/<?= $documentoDO->getIdDocumento() ?>" rel="external"><?= $documentoDO->getVNombre() ?></a></label>
						</li><?
					
					}
					
				?></ul>
			</div><?
        	
        }	
        
		
	} else {
		
		?><h3>No se ha encontrado la convocatoria</h3><?
		
	}
?>