<h2>Listado de Convocatorias</h2>

<table class="listado">
    <thead>
		<tr>
			<th><a href="/convocatoria/index.html/?ob=nom&o=<?=$this->order?>" <?=( ($this->orderBy == 'nom')?'class="ordenado ' . $this->order . '"':'' )?> >Nombre</a></th>
			<th><a href="/convocatoria/index.html/?ob=desc&o=<?=$this->order?>" <?=( ($this->orderBy == 'desc')?'class="ordenado ' . $this->order . '"':'' )?>>Descripción</a></th>
			<th><a href="/convocatoria/index.html/?ob=pres&o=<?=$this->order?>" <?=( ($this->orderBy == 'pres')?'class="ordenado ' . $this->order . '"':'' )?>>Presupuesto</a></th>
			<th><a href="/convocatoria/index.html/?ob=tipo&o=<?=$this->order?>" <?=( ($this->orderBy == 'tipo')?'class="ordenado ' . $this->order . '"':'' )?>>Tipo de Convocatoria</a></th>
			<?
			
				if ( $this->editar ){
					?><th>Eliminar</th>
					<th>Editar</th>
					<th>Duplicar</th><?	
				}
			
			?>
		</tr>
	</thead>
	<tbody>
		<?php
		
			$contador = 0;
			foreach ( $this->arrConvocatoriasDO as $convocatoriaDO ){
				
			    //$convocatoriaDO = new TblConvocatoria($db);
				$clase = ( ($contador%2)==0 )?'':'class="alter"';
				$contador++;
				
				?>
				<tr	<?= $clase ?> >
					<td><a href="/convocatoria/ficha.html/<?= $convocatoriaDO->getIdConvocatoria() ?>"><?= $convocatoriaDO->getVNombre() ?></a></td>
					<td><?= $convocatoriaDO->getVDescripcion()?></td>
					<td><?= NingenNumeric::decimalFormatoEuropeo($convocatoriaDO->getEPresupuesto(), 2) ?>€</td>
					<td><?= $this->tiposConvocatoriaIDX[$convocatoriaDO->getFkTipoConvocatoria()] ?></td>
					<?
					
						if ( $this->editar ){
							?><td class="accion"><a href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea eliminar la convocatoria <strong><?= $convocatoriaDO->getVNombre() ?></strong>?','/convocatoria/eliminar.html/<?= $convocatoriaDO->getIdConvocatoria() ?>')" class="btnEliminar" title="Eliminar Convocatoria"><span>eliminar</span></a></td>
							<td class="accion"><a href="/convocatoria/editar.html/<?= $convocatoriaDO->getIdConvocatoria() ?>" class="btnEditar" title="Editar Convocatoria"><span>editar</span></a></td>
							<td class="accion"><a href="/convocatoria/duplicar.html/<?= $convocatoriaDO->getIdConvocatoria() ?>" class="btnDuplicar" title="Duplicar Convocatoria"><span>duplicar</span></a></td><?	
						}
					
					?>
				</tr>
				<?
				
			}
			
		?>
	</tbody>
</table>
<div id="paginadorContainer"><?= $this->paginador ?></div>