<?php
	$this->addJavascriptInclude('/js/alumno.js');
	
	if ( !is_null($this->popup) ){
    	echo '<script type="text/javascript">ventana' . ucfirst($this->popup['estado']) . '("' . $this->popup['titulo'] . '", "' . $this->popup['mensaje'] . '", "' . $this->popup['url'] . '");</script>'; 
	}
?>
    
    <form id="altaAlumno" action="/alumno/alta.html" method="post">
        <fieldset>
        
        	<input type="hidden" value="1" name="send" />
        	
        	<h3>Datos del Usuario</h3>
        	
        	<div class="campo controlado">
	        	<label for="nombreUsuario">Nombre de usuario*</label>
	            <input type="text" name="nombreUsuario" id="nombreUsuario" class="campoTexto mediano" onblur="comprobarUsuario('nombreUsuario')" />
	            <p id="errorNombreUsuario" class="errorInput"><?= $this->errorNombreUsuario ?></p>
	            <p class="tooltip" id="nombreUsuarioTooltip">El nombre de usuario debe tener 5 caracteres como mínimo y 16 como máximo. Debe estar compuesto de sólo letras y/o números. <em>Ej: usuario12</em></p>
	        </div>
	        
	        <div class="campo controlado multi">
	            <label for="password1">Contraseña*</label>
	            <input type="password" name="password1" id="password1" class="campoTexto" />
	            <p id="errorPassword1" class="errorInput"><?= $this->errorPassword ?></p>
	        </div>
	        
	        <div class="campo controlado multi">
	            <label for="repassword1">Repetir Contraseña*</label>
	            <input type="password" name="repassword1" id="repassword1" class="campoTexto" />
	            <p class="tooltip" id="password1Tooltip">La contraseña debe tener 6 caracteres como mínimo y 16 como máximo. Puede estar compuesta por cualquier caracter, pero al menos debe contener un número.<em> Ej: test1_casa</em></p>
	            <p id="errorRepassword1" class="errorInput"><?= $this->errorPassword ?></p>
	        </div>
        
        	<div class="campo clear">
	             <label for="emailUsuario">Correo electrónico*</label>
	             <input type="text" name="emailUsuario" id="emailUsuario" class="campoTexto" />
	             <p id="errorEmailUsuario" class="errorInput"><?= $this->errorEmail ?></p>
	        </div>
	        
        	<h3>Datos del Alumno</h3>
        	
            <div class="campo controlado">
                <label for="nombre">Nombre*</label>
                <input type="text" name="nombre" id="nombre" class="campoTexto" />
                <p id="errorNombre" class="errorInput"><?= $this->errorNombre ?></p>
            </div>
    
            <div class="campo multi controlado">
                <label for="apellido1">Primer Apellido*</label>
                <input type="text" name="apellido1" id="apellido1" class="campoTexto" />
                <p id="errorApellido1" class="errorInput"><?= $this->errorApellido ?></p>
            </div>
    
            <div class="campo multi controlado">
                <label for="apellido2">Segundo Apellido</label>
                <input type="text" name="apellido2" id="apellido2" class="campoTexto"  />
                <p id="errorApellido2" class="errorInput"><?= $this->errorApellido2 ?></p>
            </div>
            
            <div class="separadorH"></div>
            
            <div class="campo multi controlado">
                <label for="nacimiento">Fecha de nacimiento*</label>
                <input type="text" name="nacimiento" id="nacimiento" class="campoTexto mediano" onkeypress="return false;"  />
                <p id="errorNacimiento" class="errorInput"><?= $this->errorNacimiento ?></p>
            </div>
            
            <div class="campo multi">
                <label for="tipoIdentificacion">Tipo de identificación</label><?
                
                ?><select name="tipoIdentificacion" id="tipoIdentificacion" class="campoTexto desplegable mediano">
                    <option value=""></option><?
                    
                    foreach ($this->tipoIdentificacionCOL as $tipoIdentificacionDO){
    
                        $claveTipo = $tipoIdentificacionDO->getIdTipoIdentificacion();
                        echo '<option value="' . $claveTipo . '">' . $tipoIdentificacionDO->getVNombre() . '</option>' . "\n";
                        
                    }
                    
                ?></select>
                <p id="errorTipoIdentificacion" class="errorInput"><?= $this->errorTipoIdentificacion ?></p>
            </div>
            
            <div class="campo multi controlado">
                <label for="dni">Número identificación*</label>
                <input type="text" name="dni" id="dni" onblur="comprobarDni('dni')" class="campoTexto mediano" />
                <p id="errorDni" class="errorInput"><?= $this->errorDni ?></p>
            </div>
            
            <div class="separadorH"></div>
            
            <div class="campo multi">
                <label for="tel">Teléfono</label>
                <input type="text" name="tel" id="tel" class="campoTexto mediano" />
            </div>
    
            <div class="campo multi">
                <label for="movil">Teléfono movil</label>
                <input type="text" name="movil" id="movil" class="campoTexto mediano" />
            </div>
    
            <div class="separadorH"></div>
    
            <div class="campo multi">
                <label for="direccion">Dirección</label>
                <input type="text" name="direccion" id="direccion" class="campoTexto" />
            </div>
    
            <div class="campo multi">
                <label for="poblacion">Población</label>
                <input type="text" name="poblacion" id="poblacion" class="campoTexto" />
            </div>
    
            <div class="separadorH"></div>
    
            <div class="campo multi">
                <label for="cp">Código Postal</label>
                <input type="text" name="cp" id="cp" class="campoTexto mediano" />
            </div>
    
            <div class="campo multi">
                <label for="provincia">Provincia</label><?
                
                ?><select name="provinciasUsuario" id="provincia" class="campoTexto desplegable mediano">
                    <option value=""></option><?
                    
                    foreach ($this->provinciasCOL as $provinciaDO){
    
                        $claveProvincia = $provinciaDO->getIdProvincia();
                        echo '<option value="' . $claveProvincia . '">' . $provinciaDO->getVNombreEs() . '</option>' . "\n";
                        
                    }
                    
                ?></select>
            </div>
            
            <div class="campo multi controlado">
                
                <label for="pais">País*</label>
                    <select name="pais" id="pais" class="campoTexto desplegable mediano">
                        <option value=""></option><?
                        
                        foreach ($this->paisesCOL as $paisDO){
    
                            $clavePais = $paisDO->getVIso();
                            echo '<option value="' . $clavePais . '" >' . $paisDO->getVNombreEs() . '</option>' . "\n"; 
                            
                        }
                        
                    ?></select>
                    <p id="errorPais" class="errorInput"><?= $this->errorPais ?></p>
            </div>
            
            <div class="separadorH"></div>
            
            <div class="campo multi controlado">
                
                <label for="estadoCivil">Estado Civil*</label>
                    <select name="estadoCivil" id="estadoCivil" class="campoTexto desplegable mediano">
                        <option value=""></option><?
                        
                        foreach ($this->estadosCivilesCOL as $estadoCivilDO){
                            
                            $claveEstadoCivil = $estadoCivilDO->getIdEstadoCivil();
                            echo '<option value="' . $claveEstadoCivil . '" >' . $estadoCivilDO->getVNombre() . '</option>' . "\n";
                            
                        }
                        
                    ?></select>
                    <p id="errorEstadoCivil" class="errorInput"><?= $this->errorEstadoCivil ?></p>
            </div>
            
                    
            <div class="campo multi controlado">
                
                <label for="estadoLaboral">Estado Laboral*</label>
                    <select name="estadoLaboral" id="estadoLaboral" class="campoTexto desplegable mediano">
                        <option value=""></option><?
                        
                        foreach ($this->estadosLaboralesCOL as $estadoLaboralDO){
                            
                            $claveEstadoLaboral = $estadoLaboralDO->getIdEstadoLaboral();
                            echo '<option value="' . $claveEstadoLaboral . '" >' . $estadoLaboralDO->getVNombre() . '</option>' . "\n";
                            
                        }
                        
                    ?></select>
                    <p id="errorEstadoLaboral" class="errorInput"><?= $this->errorEstadoLaboral ?></p>
            </div>
            
                            
            <div class="campo multi controlado">
                
                <label for="nivelEstudios">Nivel de estudios*</label>
                    <select name="nivelEstudios" id="nivelEstudios" class="campoTexto desplegable mediano">
                        <option value=""></option><?
                        
                        foreach ($this->nivelEstudiosCOL as $nivelEstudiosDO){
                            
                            $claveNivelEstudios = $nivelEstudiosDO->getIdNivelEstudios();
                            echo '<option value="' . $claveNivelEstudios . '" >' . $nivelEstudiosDO->getVNombre() . '</option>' . "\n";
                            
                        }
                        
                    ?></select>
                    <p id="errorNivelEstudios" class="errorInput"><?= $this->errorNivelEstudios ?></p>
            </div>
			
			<div class="separadorH"></div>
    
           	<h3>Carnet de conducir</h3>
            <div class="campo">
	            <?
	            
	            foreach ( $this->carnetsCOL as $carnetDO ){
	            	
	            	?>
	            	<label class="alter" for="carnet_<?=$carnetDO->getIdCarnetConducir()?>"><?=$carnetDO->getVNombre() . '(' . $carnetDO->getVDescripcion() . ')'?></label>
	            	<input class="checkbox" type="checkbox" name="carnet_<?=$carnetDO->getIdCarnetConducir()?>" id="carnet_<?=$carnetDO->getIdCarnetConducir()?>" />
	            	<?
	            	
	            }
	            
	            ?>
            </div>
			
			<div class="campo">
				<label for="observaciones">Observaciones</label>
		        <textarea name="observaciones" id="observaciones" ></textarea>
		    </div>
		    
			<div class="campo multi">
	            <label for="cursosSeleccionados">Preinscripciones del alumno</label>
	            
	            <div class="contenedorMultiselect">
		            <a title="Quitar curso" class="btnEliminar" href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea quitar el/los curso/s del alumno?', 'javascript:quitarCursoAlumno();hidePopups()')"><span>eliminar</span></a>
		            <select name="cursos[]" multiple="multiple" id="cursosSeleccionados" class="campoTexto enorme multiple"><?
		            	
		            ?></select>
	            </div>
	            <p class="tooltip" id="cursosSeleccionadosTooltip">Se pueden seleccionar varios cursos manteniendo pulsada la tecla CTRL</p>
        	</div>
			
			<div class="separadorH"></div>
			
            <input class="oculto" type="submit" value="Guardar" />
            
            <noscript>
            	<div class="campo">
            		<input type="submit" value="Guardar" />
            	</div>
            </noscript>
            
        </fieldset>
    </form>
    
    <?
    	if ( count($this->cursosCOL) > 0 ){
    ?>
    <h3>Listado de cursos</h3>
    <div class="campo multi">
    	<div class="scroll">
	    	<table class="listado">
			    <thead>
					<tr>
						<th>Nombre</th>
						<th>Sector</th>
						<th>Categoria</th>
						<th>Inicio</th>
						<th>Fin</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php
					
						$contador = 0;
						foreach ( $this->cursosCOL as $cursoDO ){
							
						    //$cursoDO = new TblCurso($db);
							$clase = ( ($contador%2)==0 )?'':'class="alter"';
							$contador++;
							
							?>
							<tr	<?= $clase ?> >
								<td><a href="/curso/ficha.html/<?= $cursoDO->getIdCurso() ?>"><?= $cursoDO->getVNombre() ?></a></td>
								<!-- td><a href="/plan/ficha.html/<?= $cursoDO->getFkPlan() ?>"><?= $this->planesIDX[$cursoDO->getFkPlan()] ?></a></td>
								<td><?= $this->sectoresIDX[$cursoDO->getFkSector()] ?></td>
								<td><?= $this->categoriasIDX[$cursoDO->getFkCategoria()] ?></td-->
								<td><?= $this->sectoresIDX[$cursoDO->getFkSector()] ?></td>
								<td><?= $this->categoriasIDX[$cursoDO->getFkCategoria()] ?></td>
								<?php
					 
								$fechaIni = OwlDate::getDiaMesAno($cursoDO->getDInicio());
								( $fechaIni == '01/01/1970' ) ? $fechaIni = '-' : '';
								$fechaFin = OwlDate::getDiaMesAno($cursoDO->getDFin());
								( $fechaFin == '01/01/1970' ) ? $fechaFin = '-' : '';
								
								?>
								<td><?= $fechaIni ?></td>
								<td><?= $fechaFin ?></td>
								<td><a href="javascript:addCursoAlumno('<?= $cursoDO->getIdCurso() ?>', '<?= $cursoDO->getVNombre() ?>')" class="btnAnadir" title="Asignar al alumno"><span>añadir</span></a></td>
							</tr>
							<?
							
						}
						
					?>
				</tbody>
			</table>
		</div>
    </div>
    <?
    	}
    ?>
    
    <div class="separadorH"></div>
    
    <p>* Campos obligatorios</p>