<?php
	$this->addJavascriptInclude('/js/alumno.js');
	
	// Se actualiza el tipo de dato que se comprobará con javascript.
	// Es necesario para controlar la contraseña del usuario
    $javascript = '<script type="text/javascript">editar = true;</script>';
    $this->echoOnHead($javascript);
	
	if ( !is_null($this->popup) ){
    	echo '<script type="text/javascript">ventana' . ucfirst($this->popup['estado']) . '("' . $this->popup['titulo'] . '", "' . $this->popup['mensaje'] . '", "' . $this->popup['url'] . '");</script>'; 
	}
?>

<?

	if ( !is_null($this->alumnoDO) ){

?>

    <form id="editarAlumno" action="<?= $_SERVER['REQUEST_URI'] ?>" method="post">
        <fieldset>
        
        	<input type="hidden" value="1" name="send" />
        	
        	<h3>Datos del Usuario</h3>
        	
        	<div class="campo controlado">
	        	<label for="nombreUsuario">Nombre de usuario*</label>
	            <input type="text" name="nombreUsuario" id="nombreUsuario" class="campoTexto mediano" onblur="comprobarUsuario('nombreUsuario')" value="<?= (!$this->duplicar) ? $this->usuarioDO->getVNombre() : '' ?>"/>
	            <input type="hidden" id="nombreUsuarioOculto" name="nombreUsuarioOculto" value="<?= (!$this->duplicar) ? $this->usuarioDO->getVNombre() : '' ?>" />
	            <p id="errorNombreUsuario" class="errorInput"><?= $this->errorNombreUsuario ?></p>
	            <p class="tooltip" id="nombreUsuarioTooltip">El nombre de usuario debe tener 5 caracteres como mínimo y 16 como máximo. Debe estar compuesto de sólo letras y/o números. <em>Ej: usuario12</em></p>
	        </div>
	        
	        <div class="campo controlado multi">
	            <label for="password1">Contraseña*</label>
	            <input type="password" name="password1" id="password1" class="campoTexto" />
	            <p id="errorPassword1" class="errorInput"><?= $this->errorPassword ?></p>
	        </div>
	        
	        <div class="campo controlado multi">
	            <label for="repassword1">Repetir Contraseña*</label>
	            <input type="password" name="repassword1" id="repassword1" class="campoTexto" />
	            <p class="tooltip" id="password1Tooltip">La contraseña debe tener 6 caracteres como mínimo y 16 como máximo. Puede estar compuesta por cualquier caracter, pero al menos debe contener un número.<em> Ej: test1_casa</em></p>
	            <p id="errorRepassword1" class="errorInput"><?= $this->errorPassword ?></p>
	        </div>
        
        	<div class="campo clear">
	             <label for="emailUsuario">Correo electrónico*</label>
	             <input type="text" name="emailUsuario" id="emailUsuario" class="campoTexto" value="<?= (!$this->duplicar) ? $this->usuarioDO->getVEmail() : '' ?>"/>
	             <p id="errorEmailUsuario" class="errorInput"><?= $this->errorEmail ?></p>
	        </div>
	        
        	<h3>Datos del Alumno</h3>
        	
            <div class="campo controlado">
                <label for="nombre">Nombre*</label>
                <input type="text" name="nombre" id="nombre" class="campoTexto" value="<?= $this->alumnoDO->getVNombre() ?>"/>
                <p id="errorNombre" class="errorInput"><?= $this->errorNombre ?></p>
            </div>
    
            <div class="campo multi controlado">
                <label for="apellido1">Primer Apellido*</label>
                <input type="text" name="apellido1" id="apellido1" class="campoTexto" value="<?= $this->alumnoDO->getVPrimerApellido() ?>"/>
                <p id="errorApellido1" class="errorInput"><?= $this->errorApellido ?></p>
            </div>
    
            <div class="campo multi controlado">
                <label for="apellido2">Segundo Apellido</label>
                <input type="text" name="apellido2" id="apellido2" class="campoTexto" value="<?= $this->alumnoDO->getVSegundoApellido() ?>"/>
                <p id="errorApellido2" class="errorInput"><?= $this->errorApellido2 ?></p>
            </div>
            
            <div class="separadorH"></div>
            
            <div class="campo multi controlado">
                <label for="nacimiento">Fecha de nacimiento*</label>
                <input type="text" name="nacimiento" id="nacimiento" class="campoTexto mediano" onkeypress="return false;"  value="<?= OwlDate::getDiaMesAno($this->alumnoDO->getDNacimiento()) ?>"/>
                <p id="errorNacimiento" class="errorInput"><?= $this->errorNacimiento ?></p>
            </div>
            
            <div class="campo multi">
                <label for="tipoIdentificacion">Tipo de identificación</label><?
                
                ?><select name="tipoIdentificacion" id="tipoIdentificacion" class="campoTexto mediano">
                    <option value=""></option><?
                    
                    foreach ($this->tipoIdentificacionCOL as $tipoIdentificacionDO){
    
                        $claveTipo = $tipoIdentificacionDO->getIdTipoIdentificacion();
                        echo '<option value="' . $claveTipo . '" ' . ( ($this->alumnoDO->getFkTipoIdentificacion() == $claveTipo)?'selected="selected"':'' ) . ' >' . $tipoIdentificacionDO->getVNombre() . '</option>' . "\n";
                        
                    }
                    
                ?></select>
                <p id="errorTipoIdentificacion" class="errorInput"><?= $this->errorTipoIdentificacion ?></p>
            </div>
            
            <div class="campo multi controlado">
                <label for="dni">Número identificación*</label>
                <input type="text" name="dni" id="dni" class="campoTexto mediano" onblur="comprobarDni('dni', false, true)" value="<?= $this->alumnoDO->getVNumeroIdentificacion() ?>"/>
                <input type="hidden" name="dniOculto" id="dniOculto" value="<?= $this->alumnoDO->getVNumeroIdentificacion() ?>"/>
                <p id="errorDni" class="errorInput"><?= $this->errorDni ?></p>
            </div>
            
            <div class="separadorH"></div>
            
            <div class="campo multi">
                <label for="tel">Teléfono</label>
                <input type="text" name="tel" id="tel" class="campoTexto mediano" value="<?= $this->alumnoDO->getVTelefono() ?>" />
            </div>
    
            <div class="campo multi">
                <label for="movil">Teléfono movil</label>
                <input type="text" name="movil" id="movil" class="campoTexto mediano" value="<?= $this->alumnoDO->getVMovil() ?>" />
            </div>
            
            <div class="separadorH"></div>
    
            <div class="campo multi">
                <label for="direccion">Dirección</label>
                <input type="text" name="direccion" id="direccion" class="campoTexto" value="<?= $this->alumnoDO->getVDireccion() ?>" />
            </div>
    
            <div class="campo multi">
                <label for="poblacion">Población</label>
                <input type="text" name="poblacion" id="poblacion" class="campoTexto" value="<?= $this->alumnoDO->getVPoblacion() ?>" />
            </div>
    
            <div class="separadorH"></div>
    
            <div class="campo multi">
                <label for="cp">Código Postal</label>
                <input type="text" name="cp" id="cp" class="campoTexto mediano" value="<?= $this->alumnoDO->getVCp() ?>" />
            </div>
    
            <div class="campo multi">
                <label for="provincia">Provincia</label><?
                
                ?><select name="provinciasUsuario" id="provincia" class="campoTexto mediano">
                    <option value=""></option><?
                    
                    foreach ($this->provinciasCOL as $provinciaDO){
    
                        $claveProvincia = $provinciaDO->getIdProvincia();
                        echo '<option value="' . $claveProvincia . '" ' . ( ($this->alumnoDO->getFkProvincia() == $claveProvincia)?'selected="selected"':'' ) . '>' . $provinciaDO->getVNombreEs() . '</option>' . "\n";
                        
                    }
                    
                ?></select>
            </div>
            
            <div class="campo multi controlado">
                
                <label for="pais">País*</label>
                    <select name="pais" id="pais" class="campoTexto mediano">
                        <option value=""></option><?
                        
                        foreach ($this->paisesCOL as $paisDO){
    
                            $clavePais = $paisDO->getVIso();
                            echo '<option value="' . $clavePais . '" ' . ( ($this->alumnoDO->getFkPais() == $clavePais)?'selected="selected"':'' ) . '>' . $paisDO->getVNombreEs() . '</option>' . "\n"; 
                            
                        }
                        
                    ?></select>
                    <p id="errorPais" class="errorInput"><?= $this->errorPais ?></p>
            </div>
            
            <div class="separadorH"></div>
            
            <div class="campo multi">
                
                <label for="estadoCivil">Estado Civil*</label>
                    <select name="estadoCivil" id="estadoCivil" class="campoTexto mediano">
                        <option value=""></option><?
                        
                        foreach ($this->estadosCivilesCOL as $estadoCivilDO){
                            
                            $claveEstadoCivil = $estadoCivilDO->getIdEstadoCivil();
                            echo '<option value="' . $claveEstadoCivil . '" ' . ( ($this->alumnoDO->getFkEstadoCivil() == $claveEstadoCivil)?'selected="selected"':'' ) . '>' . $estadoCivilDO->getVNombre() . '</option>' . "\n";
                            
                        }
                        
                    ?></select>
                    <p id="errorEstadoCivil" class="errorInput"><?= $this->errorEstadoCivil ?></p>
            </div>
            
                    
            <div class="campo multi">
                
                <label for="estadoLaboral">Estado Laboral*</label>
                    <select name="estadoLaboral" id="estadoLaboral" class="campoTexto mediano">
                        <option value=""></option><?
                        
                        foreach ($this->estadosLaboralesCOL as $estadoLaboralDO){
                            
                            $claveEstadoLaboral = $estadoLaboralDO->getIdEstadoLaboral();
                            echo '<option value="' . $claveEstadoLaboral . '" ' . ( ($this->alumnoDO->getFkEstadoLaboral() == $claveEstadoLaboral)?'selected="selected"':'' ) . '>' . $estadoLaboralDO->getVNombre() . '</option>' . "\n";
                            
                        }
                        
                    ?></select>
                    <p id="errorEstadoLaboral" class="errorInput"><?= $this->errorEstadoLaboral ?></p>
            </div>
            
                            
            <div class="campo multi">
                
                <label for="nivelEstudios">Nivel de estudios*</label>
                    <select name="nivelEstudios" id="nivelEstudios" class="campoTexto mediano">
                        <option value=""></option><?
                        
                        foreach ($this->nivelEstudiosCOL as $nivelEstudiosDO){
                            
                            $claveNivelEstudios = $nivelEstudiosDO->getIdNivelEstudios();
                            echo '<option value="' . $claveNivelEstudios . '" ' . ( ($this->alumnoDO->getFkNivelEstudios() == $claveNivelEstudios)?'selected="selected"':'' ) . '>' . $nivelEstudiosDO->getVNombre() . '</option>' . "\n";
                            
                        }
                        
                    ?></select>
                    <p id="errorNivelEstudios" class="errorInput"><?= $this->errorNivelEstudios ?></p>
            </div>
			
			<div class="separadorH"></div>
			
			<div class="campo multi">
	            <label for="cursosSeleccionados">Preinscripciones del alumno</label>
	            
	            <div class="contenedorMultiselect">
	            	<a title="Ir a la ficha del curso" class="btnFicha" href="javascript:fichaCurso();hidePopups();"><span>ficha</span></a>
		            <a title="Quitar curso" class="btnEliminar" href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea quitar el/los curso/s del alumno?', 'javascript:quitarCursoAlumno();hidePopups()')"><span>eliminar</span></a>
		            <select name="cursos[]" multiple="multiple" id="cursosSeleccionados" class="campoTexto enorme multiple"><?
						
		            	foreach ( $this->cursosAlumnoCOL as $cursoAlumnoDO ){
		            		
		            		?><option value="<?= $cursoAlumnoDO->getFkCurso() ?>"><?
		            		
		            			foreach ( $this->cursosCOL as $cursoDO ){
		            				
		            				if ( $cursoDO->getIdCurso() == $cursoAlumnoDO->getFkCurso() ){
		            					echo $cursoDO->getVNombre(); 
		            				}
		            				
		            			}
		            			 
		            		?></option><?
		            		
		            	}
		            	
		            ?></select>
	            </div>
	            <p class="tooltip" id="cursosSeleccionadosTooltip">Se pueden seleccionar varios cursos manteniendo pulsada la tecla CTRL</p>
        	</div>
			
			<div class="separadorH"></div>
			
            <input class="oculto" type="submit" value="Guardar" />
            
            <noscript>
            	<div class="campo">
            		<input type="submit" value="Guardar" />
            	</div>
            </noscript>
            
        </fieldset>
    </form>
    
    <?
    	if ( count($this->cursosCOL) > 0 ){
    ?>
    <h3>Listado de cursos</h3>
    <div class="campo multi">
    	<div class="scroll">
	    	<table class="listado">
    <thead>
		<tr>
			<th>Nombre</th>
			<th>Sector</th>
			<th>Categoria</th>
			<th>Inicio</th>
			<th>Fin</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<?php
		
			$contador = 0;
			foreach ( $this->cursosCOL as $cursoDO ){
				
			    //$cursoDO = new TblCurso($db);
				$clase = ( ($contador%2)==0 )?'':'class="alter"';
				$contador++;
				
				?>
				<tr	<?= $clase ?> >
					<td><a href="/curso/ficha.html/<?= $cursoDO->getIdCurso() ?>"><?= $cursoDO->getVNombre() ?></a></td>
					<!-- td><a href="/plan/ficha.html/<?= $cursoDO->getFkPlan() ?>"><?= $this->planesIDX[$cursoDO->getFkPlan()] ?></a></td>
					<td><?= $this->sectoresIDX[$cursoDO->getFkSector()] ?></td>
					<td><?= $this->categoriasIDX[$cursoDO->getFkCategoria()] ?></td-->
					<td><?= $this->sectoresIDX[$cursoDO->getFkSector()] ?></td>
					<td><?= $this->categoriasIDX[$cursoDO->getFkCategoria()] ?></td>
					<td><?= OwlDate::getDiaMesAno($cursoDO->getDInicio()) ?></td>
					<td><?= OwlDate::getDiaMesAno($cursoDO->getDFin()) ?></td>
					<td><a href="javascript:comprobarCandidatoCurso('<?= $this->alumnoDO->getIdPersona() ?>','<?= $cursoDO->getIdCurso() ?>', '<?= $cursoDO->getVNombre() ?>')" class="btnAnadir" title="Asignar al alumno"><span>añadir</span></a></td>
				</tr>
				<?
				
			}
			
		?>
	</tbody>
</table>
		</div>
    </div>
    <?
    	}
    ?>
    
    <div class="separadorH"></div>
     
    <p>* Campos obligatorios</p>
<?
	
	} else {
	
	?><h3>No se ha encontrado el alumno</h3><?
	
	}

?>