<?

	if ( !is_null($this->alumnoDO) ){
		
?>
		<div class="ficha">
			<h3>Datos del usuario</h3>
			<p><strong>Nombre:</strong><span> <?= $this->usuarioDO->getVNombre() ?></span></p>
			<p><strong>Email:</strong><span> <?= $this->usuarioDO->getVEmail() ?></span></p>
		</div>
		
		<div class="ficha">
			<h3>Datos del alumno</h3>
			<p><strong>Nombre:</strong><span> <?= $this->alumnoDO->getVNombre() . ' ' .$this->alumnoDO->getVPrimerApellido() . ' ' . $this->alumnoDO->getVSegundoApellido() ?></span></p>
			<p><strong>Fecha de nacimiento: </strong><span> <?= OwlDate::getDiaMesAno($this->alumnoDO->getDNacimiento())  ?></span></p>
			<p><strong><?= $this->alumnoDO->getTblTipoIdentificacion()->getVNombre() ?>:</strong><span> <?= $this->alumnoDO->getVNumeroIdentificacion() ?></span></p>
			
			<?
			
			$numeroSS = $this->alumnoDO->getVNumeroSS();
			if ( !empty($numeroSS) ){
				?><p><strong>Número Seguridad Social:</strong><span> <?= $numeroSS ?></span></p><?
			}

			$sexo = $this->alumnoDO->getVSexo();
			if ( !empty($sexo) ){
				?><p><strong>Sexo:</strong><span> <?= $sexo ?></span></p><?
			}

			$discapacidad = $this->alumnoDO->getBDiscapacidad();
			if ( !is_null($discapacidad) ){
				?><p><strong>Discapacidad:</strong><span> <?= ($discapacidad)? 'Si' : 'No' ?></span></p><?
			}
			
			$telefono = $this->alumnoDO->getVTelefono();
			if ( !empty($telefono) ){
				?><p><strong>Teléfono:</strong><span> <?= $telefono ?></span></p><?
			}
			
			$movil = $this->alumnoDO->getVMovil();
			if ( !empty($movil) ){
				?><p><strong>Móvil:</strong><span> <?= $movil ?></span></p><?
			}
			
			// Carnets
			if ( count($this->carnetsAlumnoCOL) > 0 ){
				
				?><p><strong>Carnets de conducir: </strong><span><?
				
				$contador = 0;
				foreach ( $this->carnetsAlumnoCOL as $carnetAlumnoDO ){
					echo ($contador)?', ':'';
					echo $this->carnetsIDX[$carnetAlumnoDO->getFkCarnet()];
					$contador++;
				}
				?></span></p><?
				
			}
			
			$direccion = $this->alumnoDO->getVDireccion();
			if ( !empty($direccion) ){
				?><p><strong>Dirección:</strong><span> <?= $direccion ?></span></p><?
			}
			
			$poblacion = $this->alumnoDO->getVPoblacion();
			if ( !empty($poblacion) ){
				?><p><strong>Población:</strong><span> <?= $poblacion ?></span></p><?
			}
			
			$cp = $this->alumnoDO->getVCp();
			if ( !empty($cp) ){
				?><p><strong>CP:</strong><span> <?= $cp ?></span></p><?
			}
			
			$provinciaDO = $this->alumnoDO->getTblProvincia();
			if ( !empty($provinciaDO) ){
				$provincia = $this->alumnoDO->getTblProvincia()->getVNombre();
				if ( !empty($provincia) ){
					?><p><strong>Provincia:</strong><span> <?= $provincia ?></span></p><?
				}
			}
			
			?>
			<p><strong>País:</strong><span> <?= $this->alumnoDO->getTblPais()->getVNombre() ?></span></p>
			<p><strong>Estado civil:</strong><span> <?= $this->alumnoDO->getTblEstadoCivil()->getVNombre() ?></span></p>
			<p><strong>Estado laboral:</strong><span> <?= $this->alumnoDO->getTblEstadoLaboral()->getVNombre() ?></span></p>
			<p><strong>Nivel de estudios:</strong><span> <?= $this->alumnoDO->getTblNivelEstudios()->getVNombre() ?></span></p>
			
			<?
			
			// Observaciones
			$observaciones = $this->alumnoDO->getVObservaciones();
			if ( !empty($observaciones) ){
				?><p class="extended"><strong>Observaciones:</strong><span> <?= $observaciones ?></span></p><?
			}
			
			?>
			
			
		</div>
		
		<?
		// Cursos preinscritos
		if ( count($this->cursosPreinscritosCOL) > 0){
			
			?><div class="ficha">
				<h3>Preinscripciones</h3>
				
				<div class="scroll">
					<table class="listado">
						<thead>
							<tr>
								<th>Curso</th>
							</tr>
						</thead>
						<tbody>
						<?
						$alter = true;
						foreach ( $this->cursosPreinscritosCOL as $cursoPreinscritoDO ){
						
							foreach ( $this->cursosCOL as $cursoDO ){
				            				
		            			if ( $cursoDO->getIdCurso() == $cursoPreinscritoDO->getFkCurso() ){
		            				$alter = !$alter;
		            				?>
		            				<tr <?= $alter ? 'class="alter"' : '' ?>>
		            					<td><a href="/curso/ficha.html/<?= $cursoDO->getIdCurso() ?>"><?= $cursoDO->getVNombre() ?></a></td>
		            				</tr>
		            				<?
		            			}
		            				
		            		}
						
						}
						
					?></tbody>
					</table>
				</div>
				<div class="separadorH"></div>
			</div><?
			
		}
		?>
		
		<?
		// Cursos candidato
		if ( count($this->cursosCandidatoCOL) > 0){
			
			?><div class="ficha">
				<h3>Candidato</h3>
				
				<div class="scroll">
					<table class="listado">
						<thead>
							<tr>
								<th>Curso</th>
							</tr>
						</thead>
						<tbody>
						<?
						$alter = true;
						foreach ( $this->cursosCandidatoCOL as $cursoCandidatoDO ){
						
							foreach ( $this->cursosCOL as $cursoDO ){
				            				
		            			if ( $cursoDO->getIdCurso() == $cursoCandidatoDO->getFkCurso() ){
		            				$alter = !$alter;
		            				?>
		            				<tr <?= $alter ? 'class="alter"' : '' ?>>
		            					<td><a href="/curso/ficha.html/<?= $cursoDO->getIdCurso() ?>"><?= $cursoDO->getVNombre() ?></a></td>
		            				</tr>
		            				<?
		            			}
		            				
		            		}
						
						}
						
					?></tbody>
					</table>
				</div>
				<div class="separadorH"></div>
			</div><?
			
		}
		?>
		
		<?
		// Cursos alumno
		if ( count($this->alumnoCursosCOL) > 0){
			
			?><div class="ficha">
				<h3>Alumno</h3>
				
				<div class="scroll">
					<table class="listado">
						<thead>
							<tr>
								<th>Curso</th>
							</tr>
						</thead>
						<tbody>
						<?
						$alter = true;
						foreach ( $this->alumnoCursosCOL as $cursoDO ){
            				$alter = !$alter;
            				?>
            				<tr <?= $alter ? 'class="alter"' : '' ?>>
            					<td><a href="/curso/ficha.html/<?= $cursoDO->getIdCurso() ?>"><?= $cursoDO->getVNombre() ?></a></td>
            				</tr>
            				<?
						}
						
					?></tbody>
					</table>
				</div>
				<div class="separadorH"></div>
			</div><?
			
		}
		?>
<?
		
	} else {
		
		?><h3>No se ha encontrado el alumno</h3><?
		
	}
?>