<div class="bloque">
	<form id="buscarUsuario" action="/usuario/buscar.html" method="post">
	    
	        <fieldset>
	        
	        	<legend>Buscar usuarios</legend>
	        
	            <input type="hidden" name="sent" value="<?= md5(date('is')) ?>" />
	        
	            <div class="campo multi">
	                <label for="idUsuario">Id</label>
	                <input type="text" class="campoTexto mini" id="idUsuario" name="idUsuario" value="<?= $this->id ?>" />
	            </div>
	        
	            <div class="campo multi">
	                <label for="username">Nombre de usuario</label>
	                <input type="text" class="campoTexto mediano" id="username" name="username" value="<?= $this->username ?>" />
	            </div>
	        
	            <div class="campo multi">
	                <label for="email">Email</label>
	                <input type="text" class="campoTexto" id="email" name="email" value="<?= $this->email ?>" />
	            </div>
	            
	            <div class="separadorH"></div>
	            
	            <div class="campo">
	                <label for="roles">Roles</label>
	                <select name="roles[]" multiple="multiple" id="roles" class="campoTexto grande"><?
	            
	                    foreach ($this->rolesIDX as $idRol => $rol){
	                
	                        $sel = '';
	                        if (count($this->roles) > 0){
	                            
	                            if ( (is_array($this->roles) && in_array($idRol, $this->roles)) || ( $this->roles == $idRol ) ) {
	                                $sel = 'selected="selected"';
	                            }
	                            
	                        }
	                        
	                        ?><option value="<?= $idRol ?> " <?= $sel ?>><?= $rol ?></option>
	                        <?
	                    
	                    }
	                
	                ?></select>
	           </div>            
	           
	           <div class="campo">
	                <input type="submit" class="btnSubmit" value="Buscar" />
	           </div>
	            
	        </fieldset>
	        
	</form>
</div><?

if ($this->result){

    ?><h3 class="buscar">Resultados de búsqueda</h3>
    
    <table class="listado fijo">
        <thead>
            <tr>
                <th><a href="/usuario/buscar.html/?ob=id&o=<?=$this->order . $this->querystring?>" <?=( ($this->orderBy == 'id')?'class="ordenado ' . $this->order . '"':'' )?> >Id</a></th>
                <th><a href="/usuario/buscar.html/?ob=nom&o=<?=$this->order . $this->querystring?>" <?=( ($this->orderBy == 'nom')?'class="ordenado ' . $this->order . '"':'' )?> >Nombre</a></th>
                <th><a href="/usuario/buscar.html/?ob=mail&o=<?=$this->order . $this->querystring?>" <?=( ($this->orderBy == 'mail')?'class="ordenado ' . $this->order . '"':'' )?> >Email</a></th>
                <th>Roles</th><?
                
                    if ( $this->editar ){
                        ?>
                        <th>Eliminar</th>
                        <th>Editar</th><? 
                    }
                
            ?></tr>
        </thead>
        <tbody><?
        
            $alter = true;
        
            foreach ($this->result as $clave => $usuario){
        
                $alter = !$alter;
                
                ?><tr <?= $alter ? 'class="alter"' : '' ?>>
                    <td><?= $clave ?></td>
                    <td><a href="/usuario/ficha/<?= $clave ?>"><?= $usuario['nombre'] ?></a></td>
                    <td><?= $usuario['email'] ?></td>
                    <td><?= $usuario['roles'] ?></td><?
                    
                        if ( $this->editar ){
    
                            ?><td class="accion"><a href="/usuario/eliminar/<?= $clave ?>" onclick="ventanaConfirmacion('Eliminar usuario', '¿Está seguro que desea eliminar el usuario <strong><?= $usuario['nombre'] ?></strong>?', this.href); return false;" class="btnEliminar usuario" title="Eliminar Usuario"><span>eliminar</span></a></td>
                            <td class="accion"><a href="/usuario/editar.html/<?= $clave ?>" class="btnEditar" title="Editar Usuario"><span>editar</span></a></td><?
                               
                        }
                            
                ?></tr><?
            
            }
            
            ?>
        </tbody>
    </table>
    <div id="paginadorContainer"><?= $this->paginador ?></div><?

} else if ($this->querystring){
	
	?><h3 class="noResult">No hay resultados</h3><?
	
}

?>