<?php


?><h3>Datos de acceso:</h3>

<div class="ficha">
    
    <p><strong>Identificador:</strong><span> <?= $this->usuarioBO->getId() ?></span></p>
    <p><strong>Nombre de usuario:</strong><span> <?= $this->usuarioBO->getNombre() ?></span></p>
    <p><strong>Roles asignados:</strong><span> <? 
    
        $rolesUsuario = $this->usuarioBO->getRoles();
        $rolesUsuarioLabels = array();
        foreach ($rolesUsuario as $rolUsuario){
            $rolesUsuarioLabels[] = $this->rolesIDX[$rolUsuario];
        }
        echo implode(', ', $rolesUsuarioLabels);
        
    ?></span></p>
    <p><strong>Correo electrónico:</strong><span> <?= $this->usuarioBO->getEmail() ?></span></p>

</div>

<div id="datosEntidad" class="ficha"><?

    if ($this->tipo == 'persona'){
        
        // FICHA DE PERSONA
        
        ?><h3>Datos personales: </h3>
        <p><strong>Nombre: </strong><span> <?= $this->personaDO->getVNombre()  ?></span></p>        
        <p><strong>Apellidos: </strong><span> <?= $this->personaDO->getVPrimerApellido() . ' ' . $this->personaDO->getVSegundoApellido()  ?></span></p>
        <p><strong>Fecha de nacimiento: </strong><span> <?= NingenDate::getDiaMesAno($this->personaDO->getDNacimiento())  ?></span></p>        
        <p><strong><?= $this->personaDO->getTblTipoIdentificacion()->getVNombre() ?>: </strong><span> <?= $this->personaDO->getVNumeroIdentificacion() ?></span></p><?
        
        if ($telefono = $this->personaDO->getVTelefono()){
        
            ?><p><strong>Teléfono: </strong><span> <?= $telefono ?></span></p><?
            
        }
        
        if ($movil = $this->personaDO->getVMovil()){

            ?><p><strong>Teléfono Movil: </strong><span> <?= $movil ?></span></p><?        
            
        }
            
        ?><p><strong>Dirección: </strong><span> <?= $this->personaDO->getVDireccion()  ?></span></p>        
        <p><strong>Población: </strong><span> <?= $this->personaDO->getVPoblacion()  ?></span></p>        
        <p><strong>Provincia: </strong><span> <?= $this->personaDO->getTblProvincia()->getVNombreEs()  ?></span></p>        
        <p><strong>País: </strong><span> <?= $this->personaDO->getTblPais()->getVNombreEs()  ?></span></p>
        <p class="nuevaSeccion"><strong>Estado civil: </strong><span><?= $this->personaDO->getTblEstadoCivil()->getVNombre() ?></span></p>
        <p><strong>Estado laboral: </strong><span> <?= $this->personaDO->getTblEstadoLaboral()->getVNombre()  ?></span></p>
        <p><strong>Nivel de estudios: </strong><span> <?= $this->personaDO->getTblNivelEstudios()->getVNombre()  ?></span></p>
        <p><strong>Fecha de alta: </strong><span> <?= NingenDate::getDiaMesAno($this->personaDO->getDAlta())  ?></span></p><?
        
    } elseif ($this->tipo = 'empresa'){
        
        // FICHA DE EMPRESA
        
        ?><h3>Datos de la empresa: </h3>
        <p><strong>Nombre: </strong><span><?= $this->empresaDO->getVNombre() ?></span></p>
        <p><strong>CIF: </strong><span><?= $this->empresaDO->getVCif() ?></span></p>
        <p><strong>Dirección: </strong><span><?= $this->empresaDO->getVDireccion() ?></span></p>
        <p><strong>Código Postal: </strong><span><?= $this->empresaDO->getVCp() ?></span></p>
        <p><strong>Población: </strong><span><?= $this->empresaDO->getVPoblacion() ?></span></p>
        <p><strong>Provincia: </strong><span> <?= $this->empresaDO->getTblProvincia()->getVNombreEs()  ?></span></p>        
        <p><strong>País: </strong><span> <?= $this->empresaDO->getTblPais()->getVNombreEs()  ?></span></p><?
        
        if ($tel = $this->empresaDO->getVTelefono()){

            ?><p><strong>Teléfono: </strong><span><?= $tel ?></span></p><?
            
        }
        
        if ($tel2 = $this->empresaDO->getVTelefono2()){

            ?><p><strong>Teléfono 2: </strong><span><?= $tel2 ?></span></p><?
            
        }
        
        if ($fax = $this->empresaDO->getVFax()){

            ?><p><strong>Fax: </strong><span><?= $fax ?></span></p><?
            
        }
        
        ?><p><strong>Fecha de alta: </strong><span> <?= NingenDate::getDiaMesAno($this->empresaDO->getDAlta()) ?></span></p><?
        
    }

?></div>