<div id="listadoDocumentos"><?
    
	if (count($this->documentosCOL)){

	    ?><table class="listado">
	        <thead>
	            <tr>
	                <th><a href="/documento/index.html/?ob=id&amp;o=<?=$this->order?>" <?=( ($this->orderBy == 'id')?'class="ordenado ' . $this->order . '"':'' )?> >Id</a></th>
	                <th><a href="/documento/index.html/?ob=nom&amp;o=<?=$this->order?>" <?=( ($this->orderBy == 'nom')?'class="ordenado ' . $this->order . '"':'' )?> >Nombre</a></th>
	                <th><a href="/documento/index.html/?ob=tipo&amp;o=<?=$this->order?>" <?=( ($this->orderBy == 'tipo')?'class="ordenado ' . $this->order . '"':'' )?> >Tipo</a></th><?
	                
		                if ($this->isAdmin){
		                	
		                	?><th><a href="/documento/index.html/?ob=tif&amp;o=<?=$this->order?>" <?=( ($this->orderBy == 'tipo')?'class="ordenado ' . $this->order . '"':'' )?> >Identificador</a></th>
		                	<th><a href="/documento/index.html/?ob=din&amp;o=<?=$this->order?>" <?=( ($this->orderBy == 'tipo')?'class="ordenado ' . $this->order . '"':'' )?> >Dinámico</a></th><?
		                	
		                }
	                
	                ?><th>Eliminar</th>
	                <th>Ver</th>
	            </tr>
	        </thead>
	        <tbody><?
	            
                $alter = true;
            
                foreach ($this->documentosCOL as $documentoDO){
                    
					// $documentoDO = new TblDocumento($this->db);
                    $alter = !$alter;
                    $id = $documentoDO->getIdDocumento();
                    
                    ?><tr <?= $alter ? 'class="alter"' : '' ?>>
                        <td><?= $documentoDO->getIdDocumento() ?></td>
                        <td><?= $documentoDO->getVNombre() ?></td>
                        <td><?= $documentoDO->getVMime() ?></td><?
                        
	                        if ($this->isAdmin){
	                        	
	                        	?><td><?= $documentoDO->getVIdentificador() ?></td>
	                        	<td><?= $documentoDO->getBDinamico() ? '<span class="checkedCell"><strong>Si</strong></span>' : ''  ?></td><?
	                        	
	                        }
                        
                        ?><td class="accion"><a href="/documento/eliminar/<?= $id ?>" onclick="ventanaConfirmacion('Eliminar Documento', '¿Está seguro que desea eliminar el documento <strong><?= $documentoDO->getVNombre() ?></strong>?', this.href);return false;" class="btnEliminar" title="Eliminar Documento"><span>eliminar</span></a></td>
                        <td><a href="/documento/ver/<?= $id ?>" class="doc pdf" rel="external"><span>ver</span></a></td>
                    </tr><?
                    
                }  
	            
	       ?></tbody>
	    </table>  
	      
	    <div id="paginadorContainer">
	    	<?= $this->paginador ?>
	    </div><?
    
	} else{
		
		echo '<h3>No hay documentos</h3>';
		
	}
	    
?></div>
<div id="formAltaDocumento">
    <form id="altaDocumento" action="/documento/index.html" method="post" enctype="multipart/form-data">
        <fieldset>
        	<legend>Alta de nuevo documento</legend>
            <input type="hidden" name="sent" value="1" />
            <input type="hidden" name="MAX_FILE_SIZE" value="2000000" />
            <div class="campo">
                <label for="nombre">Nombre:</label>
                <input type="text" class="campoTexto" name="nombre" id="nombre" />
            </div>
            <div class="campo">
                <label for="desc">Descripción:</label>
                <textarea rows="10" cols="40" name="desc" id="desc"></textarea>
            </div>
            <div class="campo">
                <label for="archivo">Archivo:</label>
                <input type="file" name="archivo" id="archivo" size="40" />
            </div><?
            
            if ($this->isAdmin){
            
	            ?><div class="adminOpts">
		            <div class="campo">
		            	<label for="identificador">Identificador:</label>
		            	<input type="text" id="identificador" name="identificador" class="campoTexto" />
		            </div>
		            <div class="campo check">
		            	<input type="checkbox" name="dinamico" id="dinamico" class="checkbox" />
		            	<label for="dinamico">Documento dinámico</label>
		            </div>
	            </div>
	            <div class="separadorH"></div><?
            
            }
            
            ?><div class="campo">
                <input type="submit" class="btnSubmit" value="Enviar" />
            </div>
        </fieldset>
    </form>
</div>