<div id="formularioPrincipal">
    <form action="">
        <fieldset>
        
            <legend>Formulario de pruebas</legend>
        
            <div class="campo">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" id="nombre" class="campoTexto" />
            </div>
            
            <div class="campo">
                <label for="comentario">Comentario</label>
                <textarea rows="5" cols="40" id="comentario"></textarea>
            </div>
            
            <div class="campo">
            
                <label for="opcion1" class="alter">Opción Uno</label>
                <input type="radio" class="radioOpt" name="opciones" id="opcion1" />
                
                <label for="opcion2" class="alter">Opción Dos</label>
                <input type="radio" class="radioOpt" name="opciones" id="opcion2" />
                
                <label for="opcion3" class="alter">Opción Tres</label>
                <input type="radio" class="radioOpt" name="opciones" id="opcion3" />
                
            </div>
            
            <h2>H2 - Tamaños de inputs</h2>
            
            <div class="campo">
                <label for="mini">Mini(40px)</label>
                <input type="text" name="mini" id="mini" class="campoTexto mini" value="15" />
            </div>
            
            <div class="campo">
                <label for="pequeno">Pequeño(100px)</label>
                <input type="text" name="pequeno" id="pequeno" class="campoTexto pequeno" value="43135621H" />
            </div>
            
            <div class="campo">
                <label for="mediano">Mediano(150px)</label>
                <input type="text" name="mediano" id="mediano" class="campoTexto mediano" value="Diego Aaron" />
            </div>
            
            <div class="campo">
                <label for="grande">Grande(250px)</label>
                <input type="text" name="grande" id="grande" class="campoTexto grande" value="C/Joan Alcover 27 7ºA" />
            </div>
            
            <div class="campo">
                <label for="enorme">Enorme(350px)</label>
                <input type="text" name="enorme" id="enorme" class="campoTexto enorme" value="Datos datos datos datos datos datos datos datos" />
            </div>
            
            <h3>H3 - Select</h3>
            
            <div class="campo">
                <label for="selectmini">Select mini</label>
                <select class="mini" name="selectmini" id="selectmini">
                    <option value="0">Opción 1</option>
                    <option value="1">Opción 2 Opción 2</option>
                    <option value="2">Opción 3 Opción 3 Opción 3</option>
                    <option value="3">Opción 4 Opción 4 Opción 4 Opción 4</option>
                    <option value="4">Opción 5 Opción 5 Opción 5 Opción 5 Opción 5</option>
                </select>
            </div>
            <div class="campo">
                <label for="selectpequeno">Select pequeño</label>
                <select class="pequeno" name="selectpequeno" id="selectpequeno">
                    <option value="0">Opción 1</option>
                    <option value="1">Opción 2 Opción 2</option>
                    <option value="2">Opción 3 Opción 3 Opción 3</option>
                    <option value="3">Opción 4 Opción 4 Opción 4 Opción 4</option>
                    <option value="4">Opción 5 Opción 5 Opción 5 Opción 5 Opción 5</option>
                </select>
            </div>
            <div class="campo">
                <label for="selectmediano">Select mediano</label>
                <select class="mediano" name="selectmediano" id="selectmediano">
                    <option value="0">Opción 1</option>
                    <option value="1">Opción 2 Opción 2</option>
                    <option value="2">Opción 3 Opción 3 Opción 3</option>
                    <option value="3">Opción 4 Opción 4 Opción 4 Opción 4</option>
                    <option value="4">Opción 5 Opción 5 Opción 5 Opción 5 Opción 5</option>
                </select>
            </div>
            <div class="campo">
                <label for="selectgrande">Select grande</label>
                <select class="grande" name="selectgrande" id="selectgrande">
                    <option value="0">Opción 1</option>
                    <option value="1">Opción 2 Opción 2</option>
                    <option value="2">Opción 3 Opción 3 Opción 3</option>
                    <option value="3">Opción 4 Opción 4 Opción 4 Opción 4</option>
                    <option value="4">Opción 5 Opción 5 Opción 5 Opción 5 Opción 5</option>
                </select>
            </div>
            <div class="campo">
                <label for="selectenorme">Select enorme</label>
                <select class="enorme" name="selectenorme" id="selectenorme">
                    <option value="0">Opción 1</option>
                    <option value="1">Opción 2 Opción 2</option>
                    <option value="2">Opción 3 Opción 3 Opción 3</option>
                    <option value="3">Opción 4 Opción 4 Opción 4 Opción 4</option>
                    <option value="4">Opción 5 Opción 5 Opción 5 Opción 5 Opción 5</option>
                </select>
            </div>
            
            <h4>H4 - Checkbox</h4>
            
            <div class="campo">
                <label for="check1" class="alter">Opción 1 check</label>
                <input type="checkbox" name="check1" id="check1" class="checkbox" />
                <label for="check2" class="alter">Opción 2 check</label>
                <input type="checkbox" name="check2" id="check2" class="checkbox" />
                <label for="check3" class="alter">Opción 3 check</label>
                <input type="checkbox" name="check3" id="check3" class="checkbox" />
            </div>
            
            <div class="campo">
            	<input type="button" value="Guardar" />
            </div>
            
        </fieldset>
    </form>
</div>