<?php
	$this->addJavascriptInclude('/js/curso.js');
	
	if ( !is_null($this->popup) ){
    	echo '<script type="text/javascript">ventana' . ucfirst($this->popup['estado']) . '("' . $this->popup['titulo'] . '", "' . $this->popup['mensaje'] . '", "' . $this->popup['url'] . '");</script>'; 
	}
?>
    
    <form id="altaCurso" action="/curso/alta.html" method="post">
        <fieldset>
        
        	<input type="hidden" value="1" name="send" />
        
            <div class="campo controlado multi">
                <label for="nombre">Nombre*</label>
                <input type="text" name="nombre" id="nombre" class="campoTexto" />
                <p id="errorNombre" class="errorInput"><?=$this->errorNombre?></p>
            </div>
			
			<div class="campo controlado multi">
            	<label for="plan">Plan*</label>
	            <select class="grande desplegable" name="plan" id="plan">
	            	<option value=""></option>
					<?
					
					// Plan
					foreach ( $this->planesIDX as $clave => $nombre) {
						
						?><option value="<?= $clave ?>" ><?= $nombre ?></option><?
						
					}
					
					?>
				</select>
				<p id="errorPlan" class="errorInput"><?= $this->errorPlan ?></p>
			</div>
			
			<div class="campo controlado multi">
            	<label for="categoria">Categoría*</label>
	            <select class="grande desplegable" name="categoria" id="categoria">
	            	<option value=""></option>
					<?
					
					// Categorias
					echo $this->htmlSelectCategorias;
					
					?>
				</select>
				<p id="errorCategoria" class="errorInput"><?= $this->errorCategoria ?></p>
			</div>
			
			<div class="separadorH"></div>
			
			<div class="campo controlado multi">
            	<label for="colectivo">Colectivo*</label>
	            <select class="grande desplegable" name="colectivo" id="colectivo">
	            	<option value=""></option>
					<?
					
					// Colectivo
					foreach ( $this->colectivosIDX as $clave => $nombre) {
						
						?><option value="<?= $clave ?>" ><?= $nombre ?></option><?
						
					}
					
					?>
				</select>
				<p id="errorColectivo" class="errorInput"><?= $this->errorColectivo ?></p>
			</div>
			
			<div class="campo controlado multi">
            	<label for="modalidad">Modalidad*</label>
	            <select class="grande desplegable" name="modalidad" id="modalidad">
	            	<option value=""></option>
					<?
					
					// Modalidad
					foreach ( $this->modalidadesIDX as $clave => $nombre) {
						
						?><option value="<?= $clave ?>" ><?= $nombre ?></option><?
						
					}
					
					?>
				</select>
				<p id="errorModalidad" class="errorInput"><?= $this->errorModalidad ?></p>
			</div>
			
			<div class="separadorH"></div>
			
			<div class="campo controlado multi">
            	<label for="centro">Centro*</label>
	            <select class="grande desplegable" name="centro" id="centro">
	            	<option value=""></option>
					<?
					
					// Aula
					foreach ( $this->centrosIDX as $clave => $nombre) {
						
						?><option value="<?= $clave ?>" ><?= $nombre ?></option><?
						
					}
					
					?>
				</select>
				<p id="errorAula" class="errorInput"><?= $this->errorAula ?></p>
			</div>
			
			<div class="separadorH"></div>
			
			<div class="campo multi">
                <label for="horasP">Horas presenciales</label>
                <input type="text" name="horasP" id="horasP" class="campoTexto mediano numerico" />
            </div>
			
			<div class="campo multi">
                <label for="horasD">Horas a distancia</label>
                <input type="text" name="horasD" id="horasD" class="campoTexto mediano numerico" />
            </div>
			
			<div class="campo multi">
                <label for="horasT">Horas de tutoría</label>
                <input type="text" name="horasT" id="horasT" class="campoTexto mediano numerico" />
            </div>
			
			<div class="campo multi">
                <label for="numAlumnos">Número de alumnos</label>
                <input type="text" name="numAlumnos" id="numAlumnos" class="campoTexto mediano numerico" />
            </div>
            
            <div class="separadorH"></div>
            
            <div class="campo multi">
                <label for="accion">Número de acción</label>
                <input type="text" name="accion" id="accion" class="campoTexto mediano decimal" />
            </div>
            
            <div class="campo multi">
                <label for="inicio">Fecha de inicio</label>
                <input type="text" name="inicio" id="inicio" class="campoTexto pequeno" onkeypress="return false;" />
            </div>
            
            <div class="campo multi">
                <label for="fin">Fecha de fin</label>
                <input type="text" name="fin" id="fin" class="campoTexto pequeno" onkeypress="return false;" />
            </div>
            
            <div class="separadorH"></div>
            
            <div class="campo">
            	<label for="descripcion">Descripción</label>
            	<textarea name="descripcion" id="descripcion"></textarea>
            </div>
            
 			<div class="alterForm">
            	<h3>Tutoría a distancia</h3>
            	<div class="campo multi">
            		<label for="tutorDistancia">Tutor a distancia</label>
            		<select name="tutorDistancia" name="tutorDistancia" id="tutorDistancia" class="desplegable grande">
            			<option value=""></option><?
            			
            			foreach ($this->profesoresIDX as $clave => $profesor){
            				
            				echo '<option value="' . $clave . '">' . $profesor . '</option>' . "\n";
            				
            			}
            			
            		?></select>
            	</div>
				<div class="campo multi">
	                <label for="horasT">Horas de tutoría</label>
	                <input type="text" name="horasT" id="horasT" class="campoTexto mediano numerico" />
	            </div>            	
	            <div class="campo multi">
					<label for="modalidadTutoria">Tipo de tutoría</label>
            		<select name="modalidadTutoria" name="modalidadTutoria" id="modalidadTutoria" class="desplegable mediano">
            			<option value=""></option><?
            			
            			foreach ($this->modalidadesIDX as $clave=>$modalidad){
            				
            				echo '<option value="' . $clave . '">' . $modalidad . '</option>' . "\n";
            				
            			}
            			
            		?></select>	            		
	            </div>
            </div>            
            
            <div class="separadorH"></div>
            
            <div class="campo multi">
	            <label for="profesoresSeleccionados">Profesores del curso</label>
	            
	            <div class="contenedorMultiselect">
		            <a title="Quitar profesor" class="btnEliminar" href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea quitar el/los profesor/es del curso?', 'javascript:quitarProfCurso();hidePopups()')"><span>eliminar</span></a>
		            <select name="profesores[]" multiple="multiple" id="profesoresSeleccionados" class="campoTexto grande multiple"><?
		                
		            ?></select>
	            </div>
	            <p class="tooltip" id="profesoresSeleccionadosTooltip">Se pueden seleccionar varios profesores manteniendo pulsada la tecla CTRL</p>
        	</div>
            
            <input class="oculto" type="submit" value="Guardar" />
            
            <noscript>
            	<div class="campo">
            		<input type="submit" value="Guardar" />
            	</div>
            </noscript>
            
        </fieldset>
    </form>
    
    <?
    	if ( count($this->profesoresIDX) > 0 ){
    ?>
    <h3>Listado de profesores</h3>
    <div class="campo multi">
    	<div class="scroll">
	    	<table class="listado">
	    		<thead>
	    			<tr>
		    			<th>Nombre</th>
		    			<th>Categorías</th>
		    			<th></th>
		    		</tr>
	    		</thead>
	    		<tbody>
					<?
					
					// Profesores
					foreach ( $this->profesoresIDX as $clave => $nombre) {
						
						// Categorías de los profesores
						$categoriasProfesor = '';
						$idsCategoriasARR = $this->categoriasProfesoresIDX[$clave];
						if ( !empty($idsCategoriasARR) ) {
							
							foreach ( $idsCategoriasARR as $idCategoria ) {
	
								$categoriasProfesor .= (( empty($categoriasProfesor) )?'':', ') . $this->categoriasIDX[$idCategoria];
								
							}
							
						}
						
						?>
						<tr>
							<td><a href="/profesor/ficha.html/<?= $clave ?>"><?= $nombre ?></a></td>
							<td><?= $categoriasProfesor ?></td>
							<td><a href="javascript:addProfCurso('<?= $clave ?>', '<?= $nombre ?>')" class="btnAnadir" title="Asignar al curso"><span>añadir</span></a></td>
						</tr>
						<?
						
						
					}
					
					?>
				</tbody>
			</table>
		</div>
    </div>
    <?
    	}
    ?>
    
     <div class="separadorH"></div>
    
    <p>* Campos obligatorios</p>
