<div id="buscadorCursos" class="buscador">
    
    <form id="buscarCurso" action="<?= $_SERVER['REQUEST_URI'] ?>" method="post">
    
        <fieldset>
        
        	<legend>Buscar un curso</legend>
        
            <input type="hidden" name="sent" value="<?= md5(date('is')) ?>" />
        
            <div class="campo multi">
                <label for="idCurso">Id</label>
                <input type="text" class="campoTexto mini" id="idCurso" name="idCurso" value="<?= $this->id ?>" />
            </div>

            <div class="campo multi">
                <label for="idPlan">Miembro del plan</label>
                <select class="desplegable campoTexto grande" id="idPlan" name="idPlan">
                    <option value=""></option><?
                    
                    foreach ($this->planesIDX as $clave=>$plan){
                        
                        $sel = $clave == $this->plan ? ' selected="selected" ' : '';
                        echo '<option value="' . $clave . '"' . $sel . '>' . $plan . '</option>' . "\n";
                        
                    }
                    
                ?></select>
            </div>

            <div class="campo multi">
                <label for="cat">Categoría</label>
                <select class="desplegable campoTexto mediano" id="cat" name="cat">
                    <option value=""></option><?
                    
                    echo $this->htmlSelectCategorias;
                    
                ?></select>
            </div>

            <div class="campo multi">
                <label for="colectivoCurso">Colectivo</label>
                <select class="desplegable campoTexto mediano" id="colectivoCurso" name="colectivoCurso">
                    <option value=""></option><?
                    
                    foreach ($this->colectivosIDX as $clave=>$colectivo){
                        
                        $sel = $clave == $this->colectivo ? ' selected="selected" ' : '';
                        echo '<option value="' . $clave . '" ' . $sel . '>' . $colectivo . '</option>' . "\n";
                        
                    }
                    
                ?></select>
            </div>

            <div class="campo multi">
                <label for="mod">Modalidad</label>
                <select class="desplegable campoTexto mediano" id="mod" name="mod">
                    <option value=""></option><?
                    
                    foreach ($this->modalidadesIDX as $clave=>$tipo){
                        
                        $sel = $clave == $this->modalidad ? ' selected="selected" ' : '';
                        echo '<option value="' . $clave . '" ' . $sel . '>' . $tipo . '</option>' . "\n";
                        
                    }
                    
                ?></select>
            </div>
        
			<div class="separadorH"></div>        
        
            <div class="campo multi">
                <label for="keyword">Palabra clave</label>
                <input type="text" class="campoTexto grande" id="keyword" name="keyword" value="<?= $this->kw ?>" />
            </div>            
            
            <div class="campo multi">
                <input type="submit" value="Buscar" class="btnSubmit" />
            </div>
            
            <div class="separadorH"></div>
            
        
        </fieldset>
    
    </form>
    
    <div class="resultadosBusqueda"><?
    
        if ($this->cursosCOL){
    
            ?><h3 class="buscar alter">Resultados de búsqueda:</h3>
            
            <table class="listado fijo">
                <thead>
                    <tr>
                        <th><a href="/curso/buscar.html/?ob=nom&o=<?=$this->order . $this->querystring?>" <?=( ($this->orderBy == 'nom')?'class="ordenado ' . $this->order . '"':'' )?> >Nombre</a></th>
                        <th><a href="/curso/buscar.html/?ob=plan&o=<?=$this->order . $this->querystring?>" <?=( ($this->orderBy == 'plan')?'class="ordenado ' . $this->order . '"':'' )?> >Plan</a></th>
                        <th><a href="/curso/buscar.html/?ob=ini&o=<?=$this->order . $this->querystring?>" <?=( ($this->orderBy == 'ini')?'class="ordenado ' . $this->order . '"':'' )?> >Inicio</a></th>
                        <th><a href="/curso/buscar.html/?ob=fin&o=<?=$this->order . $this->querystring?>" <?=( ($this->orderBy == 'fin')?'class="ordenado ' . $this->order . '"':'' )?> >Fin</a></th>
                        <th><a href="/curso/index.html/?ob=hor&o=<?=$this->order?>" <?=( ($this->orderBy == 'hor')?'class="ordenado ' . $this->order . '"':'' )?> >Horas</a></th>
						<th>Nº Acción</th>
						<th>Profesor</th>
						<th><a href="/curso/index.html/?ob=cen&o=<?=$this->order?>" <?=( ($this->orderBy == 'cen')?'class="ordenado ' . $this->order . '"':'' )?> >Centro</a></th>
                        <?
                        
                            if ( $this->editar ){
                                ?><th>Editar</th>
								<th>Duplicar</th>		
								<th>Docs.</th>
								<th>Horario</th>
								<th>Alumnos</th>
								<th>Eliminar</th><?  
                            }
                        
                        ?>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    
                        $contador = 0;
                        foreach ( $this->cursosCOL as $cursoDO ){
                            
                            //$cursoDO = new TblCurso($db);
                            $clase = ( ($contador%2)==0 )?'':'class="alter"';
                            $contador++;
                            
                            ?>
                            <tr <?= $clase ?> >
                                <td><a href="/curso/ficha.html/<?= $cursoDO->getIdCurso() ?>"><?= $cursoDO->getVNombre() ?></a></td>
                                <td><a href="/plan/ficha.html/<?= $cursoDO->getFkPlan() ?>"><?= $this->planesIDX[$cursoDO->getFkPlan()] ?></a></td>
                                <?php
                                
								$fechaIni = OwlDate::getDiaMesAno($cursoDO->getDInicio());
								( $fechaIni == '01/01/1970' ) ? $fechaIni = '-' : '';
								$fechaFin = OwlDate::getDiaMesAno($cursoDO->getDFin());
								( $fechaFin == '01/01/1970' ) ? $fechaFin = '-' : '';
								
								?>
								<td><?= $fechaIni ?></td>
								<td><?= $fechaFin ?></td>
								<td><?= $cursoDO->getIHorasPresenciales() + $cursoDO->getIHorasDistancia() ?></td>
								<td><?= (is_null($cursoDO->getIAccion()) || $cursoDO->getIAccion() == 0) ? '-' : $cursoDO->getIAccion() ?></td>
								<td><?= ( array_key_exists($cursoDO->getIdCurso(), $this->profesoresCursosIDX) ) ? OwlString::limitaTexto($this->profesoresCursosIDX[$cursoDO->getIdCurso()], 20) : '-' ?></td>
								<td><?= ( array_key_exists($cursoDO->getFkCentro(), $this->centrosIDX) ) ? OwlString::limitaTexto($this->centrosIDX[$cursoDO->getFkCentro()], 20) : '-' ?></td>
                                <?
                        
		                        if ( $this->editar ){
									?>
									<td class="accion"><a href="/curso/editar.html/<?= $cursoDO->getIdCurso() ?>" class="btnEditar" title="Editar Curso"><span>editar</span></a></td>
									<td class="accion"><a href="/curso/duplicar.html/<?= $cursoDO->getIdCurso() ?>" class="btnDuplicar" title="Duplicar Curso"><span>duplicar</span></a></td>
									<td class="accion"><a href="/curso/documentacion.html/<?= $cursoDO->getIdCurso() ?>" class="btnDocumentacion" title="Documentación"><span>Documentación</span></a></td>
									<td class="accion"><a href="/curso/horario.html/<?= $cursoDO->getIdCurso() ?>" class="btnHorario" title="Horario"><span>horario</span></a></td>
									<td class="accion"><a href="/curso/alumnos.html/<?= $cursoDO->getIdCurso() ?>" class="btnAlumnos" title="Alumnos"><span>alumnos</span></a></td>
									<td class="accion"><a href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea eliminar el curso <strong><?= $cursoDO->getVNombre() ?></strong>?','/curso/eliminar.html/<?= $cursoDO->getIdCurso() ?>')" class="btnEliminar" title="Eliminar Curso"><span>eliminar</span></a></td>
									<?	
								}
                                
                                ?>
                            </tr>
                            <?
                            
                        }
                        
                    ?>
                </tbody>
            </table>
            
            <div id="paginadorContainer"><?= $this->paginador ?></div><?
    
    } else if ($this->querystring){

    	?><h3 class="noResult">No hay resultados</h3><?
    	
    }
    
?></div>
</div>