<?php
	$this->addJavascriptInclude('/js/curso.js');
	
	if ( !is_null($this->popup) ){
    	echo '<script type="text/javascript">ventana' . ucfirst($this->popup['estado']) . '("' . $this->popup['titulo'] . '", "' . $this->popup['mensaje'] . '", "' . $this->popup['url'] . '");</script>'; 
	}
?>

<?
	
	if ( !is_null($this->cursoDO) ){

?>
	<ul class="pestanyas">
		<li class="actual"><strong>Datos generales</strong></li>
		<li><a href="/curso/horario.html/<?= $this->cursoDO->getIdCurso() ?>">Horario</a></li>
		<li><a href="/curso/documentacion.html/<?= $this->cursoDO->getIdCurso() ?>">Documentación</a></li>
	</ul>
	
	<div class="separadorH"></div>

    <form id="editarCurso" action="<?= $_SERVER['REQUEST_URI'] ?>" method="post">
        <fieldset>
        
        	<input type="hidden" value="1" name="send" />
        
            <div class="campo controlado multi">
                <label for="nombre">Nombre*</label>
                <input type="text" name="nombre" id="nombre" class="campoTexto" value="<?= $this->cursoDO->getVNombre() ?>"/>
                <p id="errorNombre" class="errorInput"><?=$this->errorNombre?></p>
            </div>
			
			<div class="campo controlado multi">
            	<label for="plan">Plan*</label>
	            <select class="grande" name="plan" id="plan">
	            	<option value=""></option>
					<?
					
					// Plan
					foreach ( $this->planesIDX as $clave => $nombre) {
						
						?><option value="<?= $clave ?>" <?= ( ($this->cursoDO->getFkPlan() == $clave)?'selected="selected"':'' ) ?>><?= $nombre ?></option><?
						
					}
					
					?>
				</select>
				<p id="errorPlan" class="errorInput"><?= $this->errorPlan ?></p>
			</div>
			
			<div class="campo controlado multi">
            	<label for="categoria">Categoría*</label>
	            <select class="grande" name="categoria" id="categoria">
	            	<option value=""></option>
					<?
					
					// Categorias
					echo $this->htmlSelectCategorias;
					
					?>
				</select>
				<p id="errorCategoria" class="errorInput"><?= $this->errorCategoria ?></p>
			</div>
			
			<div class="separadorH"></div>
			
			<div class="campo controlado multi">
            	<label for="colectivo">Colectivo*</label>
	            <select class="grande" name="colectivo" id="colectivo">
	            	<option value=""></option>
					<?
					
					// Colectivo
					foreach ( $this->colectivosIDX as $clave => $nombre) {
						
						?><option value="<?= $clave ?>" <?= ( ($this->cursoDO->getFkColectivo() == $clave)?'selected="selected"':'' ) ?>><?= $nombre ?></option><?
						
					}
					
					?>
				</select>
				<p id="errorColectivo" class="errorInput"><?= $this->errorColectivo ?></p>
			</div>
			
			<div class="campo controlado multi">
            	<label for="modalidad">Modalidad*</label>
	            <select class="grande" name="modalidad" id="modalidad">
	            	<option value=""></option>
					<?
					
					// Modalidad
					foreach ( $this->modalidadesIDX as $clave => $nombre) {
						
						?><option value="<?= $clave ?>" <?= ( ($this->cursoDO->getFkModalidad() == $clave)?'selected="selected"':'' ) ?>><?= $nombre ?></option><?
						
					}
					
					?>
				</select>
				<p id="errorModalidad" class="errorInput"><?= $this->errorModalidad ?></p>
			</div>
			
			<div class="separadorH"></div>
			
			<div class="campo controlado multi">
            	<label for="centro">Centro*</label>
	            <select class="grande" name="centro" id="centro">
	            	<option value=""></option>
					<?
					
					// Aula
					foreach ( $this->centrosIDX as $clave => $nombre) {
						
						?><option value="<?= $clave ?>" <?= ( ($this->cursoDO->getFkCentro() == $clave)?'selected="selected"':'' ) ?>><?= $nombre ?></option><?
						
					}
					
					?>
				</select>
				<p id="errorAula" class="errorInput"><?= $this->errorAula ?></p>
			</div>
			
			<div class="separadorH"></div>
			
			<div class="campo multi">
                <label for="horasP">Horas presenciales</label>
                <input type="text" name="horasP" id="horasP" class="campoTexto mediano numerico" value="<?= $this->cursoDO->getIHorasPresenciales() ?>"/>
            </div>
			
			<div class="campo multi">
                <label for="horasD">Horas a distancia</label>
                <input type="text" name="horasD" id="horasD" class="campoTexto mediano numerico" value="<?= $this->cursoDO->getIHorasDistancia() ?>"/>
            </div>
			
			<div class="campo multi">
                <label for="numAlumnos">Número de alumnos</label>
                <input type="text" name="numAlumnos" id="numAlumnos" class="campoTexto mediano numerico" value="<?= $this->cursoDO->getINumeroAlumnos() ?>"/>
            </div>
            
            <div class="separadorH"></div>
            
            <div class="campo multi">
                <label for="accion">Número de acción</label>
                <input type="text" name="accion" id="accion" class="campoTexto mediano decimal" value="<?= $this->cursoDO->getIAccion() ?>"/>
            </div>
            
            <div class="campo multi">
                <label for="inicio">Fecha de inicio</label>
                <?php 
                	$fechaIni = OwlDate::getDiaMesAno($this->cursoDO->getDInicio());
					( $fechaIni == '01/01/1970' ) ? $fechaIni = '' : '';
                ?>
                <input type="text" name="inicio" id="inicio" class="campoTexto pequeno" onkeypress="return false;" value="<?= $fechaIni ?>"/>
            </div>
            
            <div class="campo multi">
                <label for="fin">Fecha de fin</label>
                <?php 
					$fechaFin = OwlDate::getDiaMesAno($this->cursoDO->getDFin());
					( $fechaFin == '01/01/1970' ) ? $fechaFin = '' : '';
                ?>
                <input type="text" name="fin" id="fin" class="campoTexto pequeno" onkeypress="return false;" value="<?= $fechaFin ?>"/>
            </div>
            
            <div class="separadorH"></div>
            
            <div class="alterForm">
            	<h3>Tutoría a distancia</h3>
            	<div class="campo multi">
            		<label for="tutorDistancia">Tutor a distancia</label>
            		<select name="tutorDistancia" name="tutorDistancia" id="tutorDistancia" class="desplegable grande">
            			<option value=""></option><?
            			
            			$idTutor = $this->cursoDO->getFkTutorDistancia(); 
            			
            			foreach ($this->profesoresIDX as $clave => $profesor){
            				
            				$sel = $idTutor == $clave ? 'selected="selected"' : '';
            				echo '<option value="' . $clave . '" ' . $sel .'>' . $profesor . '</option>' . "\n";
            				
            			}
            			
            		?></select>
            	</div>
				<div class="campo multi">
	                <label for="horasT">Horas de tutoría</label>
	                <input type="text" name="horasT" id="horasT" class="campoTexto mediano numerico" value="<?= $this->cursoDO->getIHorasTutoria() ?>"/>
	            </div>            	
	            <div class="campo multi">
					<label for="modalidadTutoria">Tipo de tutoría</label>
            		<select name="modalidadTutoria" name="modalidadTutoria" id="modalidadTutoria" class="desplegable mediano">
            			<option value=""></option><?
            			
            			$idModalidadTutoria = $this->cursoDO->getFkModalidadTutoria();
            			
            			foreach ($this->modalidadesIDX as $clave=>$modalidad){
            				
            				$sel = $idModalidadTutoria == $clave ? 'selected="selected"' : '';
            				echo '<option value="' . $clave . '" ' . $sel . '>' . $modalidad . '</option>' . "\n";
            				
            			}
            			
            		?></select>	            		
	            </div>
            </div>
            
            <div class="separadorH"></div>
            
            <div class="campo">
            	<label for="descripcion">Descripción</label>
            	<textarea name="descripcion" id="descripcion"><?= $this->cursoDO->getVDescripcion() ?></textarea>
            </div>
            
            <h3>Profesores</h3>
            
            <div class="campo multi">
	            <label for="profesoresSeleccionados">Profesores del curso</label>
	            
	            <div class="contenedorMultiselect">
	            	<a title="Ir a la ficha de profesor" class="btnFicha" href="javascript:fichaProfesor();hidePopups();"><span>ficha</span></a>
		            <a title="Quitar profesor" class="btnEliminar" href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea quitar el/los profesor/es del curso?', 'javascript:quitarPersonaCurso(\'profesoresSeleccionados\');hidePopups()')"><span>eliminar</span></a>
		            <select name="profesores[]" multiple="multiple" id="profesoresSeleccionados" class="campoTexto grande multiple"><?
		                
		            	foreach ( $this->profesoresCursoCOL as $profesorCursoDO ){
		            		
		            		?><option value="<?= $profesorCursoDO->getFkPersona() ?>"><?= $this->profesoresIDX[$profesorCursoDO->getFkPersona()] ?></option><?
		            		
		            	}
		            
		            ?></select>
	            </div>
        	</div>
            
            <div class="separadorH"></div>
            
            <?
    		if ( count($this->profesoresIDX) > 0 ){
		    ?>
			    <label>Listado de profesores</label>
			    <div class="campo multi">
			    	<div class="scroll">
				    	<table class="listado">
				    		<thead>
				    			<tr>
					    			<th>Nombre</th>
					    			<th>Categorías</th>
					    			<th></th>
					    		</tr>
				    		</thead>
				    		<tbody>
								<?
								
								// Profesores
								$alter = true;
								foreach ( $this->profesoresIDX as $clave => $nombre) {
									
									$alter = !$alter;
									// Categorías de los profesores
									$categoriasProfesor = '';
									$idsCategoriasARR = $this->categoriasProfesoresIDX[$clave];
									if ( !empty($idsCategoriasARR) ) {
										
										foreach ( $idsCategoriasARR as $idCategoria ) {
				
											$categoriasProfesor .= (( empty($categoriasProfesor) )?'':', ') . $this->categoriasIDX[$idCategoria];
											
										}
										
									}
									
									?>
									<tr <?= $alter ? 'class="alter"' : '' ?>>
										<td><a href="/profesor/ficha.html/<?= $clave ?>"><?= $nombre ?></a></td>
										<td><?= $categoriasProfesor ?></td>
										<td><a href="javascript:addProfCurso('<?= $clave ?>', '<?= $nombre ?>')" class="btnAnadir" title="Asignar al curso"><span>añadir</span></a></td>
									</tr>
									<?
									
									
								}
								
								?>
							</tbody>
						</table>
					</div>
			    </div>
		    <?
		    	}
		    ?>
		    
		    <div class="separadorH"></div>
            
            <h3>Alumnos</h3>
            
            <div class="campo multi">
            	<label>Precandidatos</label>
	            <div class="contenedorMultiselect">
	            	<a title="Ir a la ficha de precandidato" class="btnFicha" href="javascript:fichaAlumno('precandidatos');hidePopups();"><span>ficha</span></a>
		            <a title="Quitar precandidato" class="btnEliminar" href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea quitar el/los precandidato/s del curso?', 'javascript:quitarPersonaCurso(\'precandidatos\');hidePopups()')"><span>eliminar</span></a>
		            <select name="precandidatos[]" multiple="multiple" id="precandidatos" class="campoTexto grande multiple"><?
		                if ( count($this->precandidatosCursoCOL) > 0 ){
			            	foreach ( $this->precandidatosCursoCOL as $precandidatoCursoDO ){
			            		
			            		?><option value="<?= $precandidatoCursoDO->getFkPersona() ?>"><?= $this->personasIDX[$precandidatoCursoDO->getFkPersona()]->getVNombre() . ' ' . $this->personasIDX[$precandidatoCursoDO->getFkPersona()]->getVPrimerApellido() . ' ' . $this->personasIDX[$precandidatoCursoDO->getFkPersona()]->getVSegundoApellido() ?></option><?
			            		
			            	}
		                }
		            
		            ?></select>
	            </div>
        	</div>
	        
	        <div class="campo multi">
	        	<ul class="botonesMultiselect">
	        		<li>
	        			<input type="button" value="&gt;" onclick="mueveAlumno('precandidatos','candidatos');"/>
	        		</li>
	        		<li>
	        			<input type="button" value="&lt;" onclick="mueveAlumno('candidatos','precandidatos');"/>
	        		</li>	
	        	</ul>
	        </div>
	        
            <div class="campo multi">
            	<label>Candidatos</label>
	            <div class="contenedorMultiselect">
	            	<a title="Ir a la ficha de precandidato" class="btnFicha" href="javascript:fichaAlumno('candidatos');hidePopups();"><span>ficha</span></a>
		            <a title="Quitar candidato" class="btnEliminar" href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea quitar el/los candidato/s del curso?', 'javascript:quitarPersonaCurso(\'candidatos\');hidePopups()')"><span>eliminar</span></a>
		            <select name="candidatos[]" multiple="multiple" id="candidatos" class="campoTexto grande multiple"><?
		            	if ( count($this->candidatosCursoCOL) > 0 ){
			            	foreach ( $this->candidatosCursoCOL as $candidatoCursoDO ){
			            		
			            		?><option value="<?= $candidatoCursoDO->getFkPersona() ?>"><?= $this->personasIDX[$candidatoCursoDO->getFkPersona()]->getVNombre() . ' ' . $this->personasIDX[$candidatoCursoDO->getFkPersona()]->getVPrimerApellido() . ' ' . $this->personasIDX[$candidatoCursoDO->getFkPersona()]->getVSegundoApellido() ?></option><?
			            		
			            	}
		            	}
		            
		            ?></select>
	            </div>
        	</div>
        	
	        <div class="campo multi">
	        	<ul class="botonesMultiselect">
	        		<li>
	        			<input type="button" value="&gt;" onclick="mueveAlumno('candidatos','alumnos');"/>
	        		</li>
	        		<li>
	        			<input type="button" value="&lt;" onclick="mueveAlumno('alumnos','candidatos');"/>
	        		</li>	
	        	</ul>
	        </div>
	        
            <div class="campo multi">
            	<label>Alumnos</label>
	            <div class="contenedorMultiselect">
	            	<a title="Ir a la ficha de alumno" class="btnFicha" href="javascript:fichaAlumno('alumnos');hidePopups();"><span>ficha</span></a>
		            <a title="Quitar alumno" class="btnEliminar" href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea quitar el/los alumno/s del curso?', 'javascript:quitarPersonaCurso(\'alumnos\');hidePopups()')"><span>eliminar</span></a>
		            <select name="alumnos[]" multiple="multiple" id="alumnos" class="campoTexto grande multiple"><?
		            	if ( count($this->alumnosCursoCOL) > 0 ){
			            	foreach ( $this->alumnosCursoCOL as $alumnoCursoDO ){
			            		
			            		?><option value="<?= $alumnoCursoDO->getIPersona() ?>"><?= $this->personasIDX[$alumnoCursoDO->getIPersona()]->getVNombre() . ' ' . $this->personasIDX[$alumnoCursoDO->getIPersona()]->getVPrimerApellido() . ' ' . $this->personasIDX[$alumnoCursoDO->getIPersona()]->getVSegundoApellido() ?></option><?
			            		
			            	}
		            	}
		            
		            ?></select>
	            </div>
        	</div>
            
            <div class="separadorH"></div>
            
            <input class="oculto" type="submit" value="Guardar" />
            
            <noscript>
            	<div class="campo">
            		<input type="submit" value="Guardar" />
            	</div>
            </noscript>
            
        </fieldset>
    </form>
    
    <p>* Campos obligatorios</p>
<?
	
	} else {
	
	?><h3>No se ha encontrado el curso</h3><?
	
	}

?>