<?

	if ( !is_null($this->cursoDO) ){
	    
?>
		<div class="ficha">
		
			<p><strong>Nombre:</strong><span> <?= $this->cursoDO->getVNombre() ?></span></p>
			<p><strong>Plan:</strong><span> <?= $this->cursoDO->getTblPlan()->getVNombre() ?></span></p>
			<p><strong>Categoría:</strong><span> <?= $this->categoriaDO->getVNombre() ?></span></p>
			<p><strong>Colectivo:</strong><span> <?= $this->cursoDO->getTblColectivo()->getVNombre() ?></span></p>
			<p><strong>Modalidad:</strong><span> <?= $this->modalidadesIDX[$this->cursoDO->getFkModalidad()] ?></span></p>
			<p><strong>Centro:</strong><span> <?= $this->cursoDO->getTblCentro()->getVNombre() ?></span></p><?
			
			$alumnos = $this->cursoDO->getINumeroAlumnos();
            ?><p><strong>Número de alumnos:</strong><span class="min"> <?= $alumnos ?></span></p>
            <p><strong>Número de acción:</strong><span class="min"> <?= $this->cursoDO->getIAccion() ?></span></p>
                
			<div class="multi">
                <p><strong>Grupo:</strong><span class="min"> <?= $this->cursoDO->getIGrupo() ?></span></p>
			</div>
			
            <div class="multi"><?
			
    			$horasP = $this->cursoDO->getIHorasPresenciales();
				?><p><strong>Horas presenciales:</strong><span class="min"> <?= $horasP ?></span></p><?
				
                $horasD = $this->cursoDO->getIHorasDistancia();
                ?><p><strong>Horas a distancia:</strong><span class="min"> <?= $horasD ?></span></p><?
            
    	    ?></div><?
    	    
    	    $horasT = $this->cursoDO->getIHorasTutoria();
    	    
    	    if (intval($horasT) != 0){
    	    
	    	    ?><div class="alterForm ficha">
	    	    
	    	    	<h3>Tutoría a distancia</h3>
	    	    	
    	    		<p><strong>Horas tutoría:</strong><span class="min"> <?= $horasT ?></span></p><?
    	    		
    	    		$tutorDistancia = 'Aún no asignado';
    	    		if ($idTutorDistancia = $this->cursoDO->getFkTutorDistancia()){
    	    			
    	    			$tutorDistancia = $this->profesoresIDX[$idTutorDistancia];
    	    			
    	    		}
	    	    	
	    	    	?><p><strong>Tutor formación a distancia:</strong><span> <?= $tutorDistancia ?></span></p><?
	    	    	
	    	    	$tipoTutoria = 'Aún no asignada';
	    	    	if ($idTipoTutoria = $this->cursoDO->getFkModalidadTutoria()){
	    	    		$tipoTutoria = $this->modalidadesIDX[$idTipoTutoria];
	    	    	}
	    	    	
	    	    	?><p><strong>Tipo de tutoría:</strong><span> <?= $tipoTutoria ?></span></p>
	    	    	
	    	    </div><?
	    	    
    	    }
    	    
    	    ?><div class="multi"><?
			
    			$fechaIni = OwlDate::getDiaMesAno($this->cursoDO->getDInicio());
    			?><p><strong>Fecha de inicio:</strong><span class="med"><?= $fechaIni ?></span></p><?
    			
    			$fechaFin = OwlDate::getDiaMesAno($this->cursoDO->getDFin());
    			?><p><strong>Fecha de finalización:</strong><span class="med"><?= $fechaFin ?></span></p>
    			
			</div><?
			
			$desc = $this->cursoDO->getVdescripcion();
			if (!empty($desc)){
			
                ?><p class="extended separator"><strong>Observaciones:</strong><span><?= $this->cursoDO->getVdescripcion() ?></span></p><?
                
			}
			
			// Profesores
			if ( count($this->profesoresCursoCOL) > 0 ){
	
				?><p><strong>Profesores</strong><span><?
				
				$profesoresARR = array();
				foreach ( $this->profesoresCursoCOL as $profesorCursoDO ){
					$profesoresARR[] = '<a href="/profesor/ficha.html/' . $profesorCursoDO->getFkPersona() . '">' . $this->profesoresIDX[$profesorCursoDO->getFkPersona()] . '</a>';
				}
				
				echo implode(', ', $profesoresARR);
				
				?></span></p><?
				
			}
			
		?>
		</div>
		<div class="ficha">
		<?
			
			// Preinscritos
			if ( count($this->precandidatosCursoCOL) > 0 ){
	
				?><h3>Precandidatos</h3>
				
				<div class="scroll">
					<table class="listado">
						<thead>
							<tr>
								<th>Nombre</th>
							</tr>
						</thead>
						<tbody>
						<?
					
						$alter = true;
						foreach ( $this->precandidatosCursoCOL as $precandidatoCursoDO ){
							
							$alter = !$alter;
							?>
							
		            		<tr <?= $alter ? 'class="alter"' : '' ?>>
		            			<td><a href="/alumno/ficha.html/<?= $precandidatoCursoDO->getFkPersona() ?>"><?= $this->personasIDX[$precandidatoCursoDO->getFkPersona()]->getVNombre() . ' ' . $this->personasIDX[$precandidatoCursoDO->getFkPersona()]->getVPrimerApellido() . ' ' . $this->personasIDX[$precandidatoCursoDO->getFkPersona()]->getVSegundoApellido() ?></a></td>
		            		</tr>
		            		
		            		<?
						}
					
					?></tbody>
					</table>
				</div>
				<div class="separadorH"></div><?
				
			}
			
			// Candidatos
			if ( count($this->candidatosCursoCOL) > 0 ){
	
				?><h3>Candidatos</h3>
				
				<div class="scroll">
					<table class="listado">
						<thead>
							<tr>
								<th>Nombre</th>
							</tr>
						</thead>
						<tbody>
						<?
					
						$alter = true;
						foreach ( $this->candidatosCursoCOL as $candidatoCursoDO ){
							
							$alter = !$alter;
							?>
							
		            		<tr <?= $alter ? 'class="alter"' : '' ?>>
		            			<td><a href="/alumno/ficha.html/<?= $candidatoCursoDO->getFkPersona() ?>"><?= $this->personasIDX[$candidatoCursoDO->getFkPersona()]->getVNombre() . ' ' . $this->personasIDX[$candidatoCursoDO->getFkPersona()]->getVPrimerApellido() . ' ' . $this->personasIDX[$candidatoCursoDO->getFkPersona()]->getVSegundoApellido() ?></a></td>
		            		</tr>
		            		
		            		<?
						}
					
					?></tbody>
					</table>
				</div>
				<div class="separadorH"></div><?
				
			}
			
			// Alumnos
			if ( count($this->alumnosCursoCOL) > 0 ){
	
				?><h3>Alumnos</h3>
				
				<div class="scroll">
					<table class="listado">
						<thead>
							<tr>
								<th>Nombre</th>
							</tr>
						</thead>
						<tbody>
						<?
					
						$alter = true;
						foreach ( $this->alumnosCursoCOL as $alumnoCursoDO ){
							
							$alter = !$alter;
							?>
							
		            		<tr <?= $alter ? 'class="alter"' : '' ?>>
		            			<td><a href="/alumno/ficha.html/<?= $alumnoCursoDO->getIPersona() ?>"><?= $this->personasIDX[$alumnoCursoDO->getIPersona()]->getVNombre() . ' ' . $this->personasIDX[$alumnoCursoDO->getIPersona()]->getVPrimerApellido() . ' ' . $this->personasIDX[$alumnoCursoDO->getIPersona()]->getVSegundoApellido() ?></a></td>
		            		</tr>
		            		
		            		<?
						}
					
					?></tbody>
					</table>
				</div>
				<div class="separadorH"></div><?
				
			}
		?>
		</div>
<?
		
	} else {
		
		?><h3>No se ha encontrado el curso</h3><?
		
	}
?>