<?

	if ( !is_null($this->cursoDO) ){
	    
?><div class="ficha">

		<h3>Secciones de edición</h3>

		<ul class="pestanyas">
			<li><a class="horarios" href="/curso/horario.html/<?= $this->cursoDO->getIdCurso() ?>">Horario</a></li>
			<li><a class="documentacion" href="/curso/documentacion.html/<?= $this->cursoDO->getIdCurso() ?>">Documentación</a></li>
			<li><a class="alumnos" href="/curso/alumnos.html/<?= $this->cursoDO->getIdCurso() ?>">Alumnos</a></li>
			<li><a class="material" href="/curso/materialDidactico.html/<?= $this->cursoDO->getIdCurso() ?>">Material didáctico</a></li>
		</ul>
		
		<div class="separadorH"></div>

		<div class="bloque">

			<h3>Datos generales</h3>
		
			<p><strong>Nombre:</strong><span> <?= $this->cursoDO->getVNombre() ?></span></p>
			<p><strong>Expediente:</strong><span> <?= $this->cursoDO->getVExpediente() ?></span></p>
			<p><strong>Plan:</strong><span> <?= $this->cursoDO->getTblPlan()->getVNombre() ?></span></p>
			<p><strong>Categoría:</strong><span> <?= $this->categoriaDO->getVNombre() ?></span></p>
			<p><strong>Colectivo:</strong><span> <?= $this->cursoDO->getTblColectivo()->getVNombre() ?></span></p>
			<p><strong>Modalidad:</strong><span> <?= $this->modalidadesIDX[$this->cursoDO->getFkModalidad()] ?></span></p>
			<p><strong>Centro:</strong><span> <?= $this->cursoDO->getTblCentro()->getVNombre() ?></span></p><?
			
			$alumnos = $this->cursoDO->getINumeroAlumnos();
            ?><p><strong>Cantidad de plazas:</strong><span class="min"> <?= $alumnos ?></span></p>
            <p><strong>Número de acción:</strong><span class="min"> <?= $this->cursoDO->getIAccion() ?></span></p>
                
			<div class="multi">
                <p><strong>Grupo:</strong><span class="min"> <?= $this->cursoDO->getIGrupo() ?></span></p>
			</div>
			
		</div>
		<div class="bloque">
			
			<h3>Horarios y fechas</h3>
			
            <div class="multi"><?
			
    			$horasP = $this->cursoDO->getIHorasPresenciales();
				?><p><strong>Horas presenciales:</strong><span class="med"> <?= $horasP ?></span></p><?
				
                $horasD = $this->cursoDO->getIHorasDistancia();
                ?><p><strong>Horas a distancia:</strong><span class="med"> <?= $horasD ?></span></p><?
            
    	    ?></div><?
    	       	    
    	    ?><div class="multi"><?
			
    			$fechaIni = OwlDate::getDiaMesAno($this->cursoDO->getDInicio());
    			?><p><strong>Fecha de inicio:</strong><span class="med"><?= $fechaIni ?></span></p><?
    			
    			$fechaFin = OwlDate::getDiaMesAno($this->cursoDO->getDFin());
    			?><p><strong>Fecha de finalización:</strong><span class="med"><?= $fechaFin ?></span></p>
    			
			</div>
		</div><?
		
		if ($this->tutoriaDO instanceof TblTutoria){
		
			?><div class="bloque">
				<h3>Tutoría del curso</h3>	
				<div class="alterForm">
					<p><strong>Modalidad:</strong><span><?= $this->modalidadesIDX[$this->tutoriaDO->getFkModalidad()] ?></span></p>
					<p><strong>Tutor:</strong><span><a href="/profesor/ficha/<?= $this->tutoriaDO->getFkTutor() ?>" rel="external"><?= $this->profesoresIDX[$this->tutoriaDO->getFkTutor()] ?></a></span></p>
					<p><strong>Horas Tutoría:</strong><span class="med"><?= $this->tutoriaDO->getIHoras() ?></span></p>
					<p class="lista"><strong>Días:</strong></p>
					<ul class="listaFicha"><?
						
						$diasARR = array('Lunes'=>'Lunes', 'Martes'=>'Martes', 'Miercoles'=>'Miércoles', 'Jueves'=>'Jueves', 'Viernes'=>'Viernes', 'Sabado'=>'Sábado', 'Domingo'=>'Domingo');
						foreach ($diasARR as $dia => $label){

							$metodo = 'isB' . $dia;
							if (true == $this->tutoriaDO->$metodo()){
								echo '<li>' . $label . '</li>';
							}
							
						}
					
					?></ul><?
					
					$deMan = $this->tutoriaDO->getIDesdeManana();
					$aMan = $this->tutoriaDO->getIHastaManana();
					$deTar = $this->tutoriaDO->getIDesdeTarde();
					$aTar = $this->tutoriaDO->getIHastaTarde();
					
					if ( $deMan && $aMan ){
						
						?><p><strong>Horario (Mañana)</strong><span>De <?= substr($deMan, 0, 5) ?> a <?= substr($aMan, 0, 5) ?></span></p><?
					
					}
					
					if ( $deTar && $aTar ){
						
						?><p><strong>Horario (Tarde)</strong><span>De <?= substr($deTar, 0, 5) ?> a <?= substr($aTar, 0, 5) ?></span></p><?
					
					}
					
				?></div>
				<div class="separadorH"></div>
			</div><?
			
		}
			
		?><div class="bloque">
		
    		<h3>Datos adicionales</h3><?
			
			$desc = $this->cursoDO->getVDescripcion();
			if (!empty($desc)){
			
                ?><p class="extended"><strong>Descripción:</strong><span><?= $this->cursoDO->getVDescripcion() ?></span></p><?
                
			}

			$obs = $this->cursoDO->getVObservaciones();
			if (!empty($obs)){
			
                ?><p class="extended"><strong>Observaciones:</strong><span><?= $this->cursoDO->getVObservaciones() ?></span></p><?
                
			}
			
			// Profesores
			if ( count($this->profesoresCursoCOL) > 0 ){
	
				?><p><strong>Profesores</strong><span><?
				
				$profesoresARR = array();
				foreach ( $this->profesoresCursoCOL as $profesorCursoDO ){
					$profesoresARR[] = '<a href="/profesor/ficha.html/' . $profesorCursoDO->getFkPersona() . '">' . $this->profesoresIDX[$profesorCursoDO->getFkPersona()] . '</a>';
				}
				
				echo implode(', ', $profesoresARR);
				
				?></span></p><?
				
			}
			
		?></div>
		</div>
		<div class="ficha">
		<?
			
			// Preinscritos
			if ( count($this->precandidatosCursoCOL) > 0 ){
	
				?><h3>Precandidatos</h3>
				
				<div class="scroll">
					<table class="listado">
						<thead>
							<tr>
								<th>Nombre</th>
							</tr>
						</thead>
						<tbody>
						<?
					
						$alter = true;
						foreach ( $this->precandidatosCursoCOL as $precandidatoCursoDO ){
							
							$alter = !$alter;
							?>
							
		            		<tr <?= $alter ? 'class="alter"' : '' ?>>
		            			<td><a href="/alumno/ficha.html/<?= $precandidatoCursoDO->getFkPersona() ?>"><?= $this->personasIDX[$precandidatoCursoDO->getFkPersona()]->getVNombre() . ' ' . $this->personasIDX[$precandidatoCursoDO->getFkPersona()]->getVPrimerApellido() . ' ' . $this->personasIDX[$precandidatoCursoDO->getFkPersona()]->getVSegundoApellido() ?></a></td>
		            		</tr>
		            		
		            		<?
						}
					
					?></tbody>
					</table>
				</div>
				<div class="separadorH"></div><?
				
			}
			
			// Candidatos
			if ( count($this->candidatosCursoCOL) > 0 ){
	
				?><h3>Candidatos</h3>
				
				<div class="scroll">
					<table class="listado">
						<thead>
							<tr>
								<th>Nombre</th>
							</tr>
						</thead>
						<tbody>
						<?
					
						$alter = true;
						foreach ( $this->candidatosCursoCOL as $candidatoCursoDO ){
							
							$alter = !$alter;
							?>
							
		            		<tr <?= $alter ? 'class="alter"' : '' ?>>
		            			<td><a href="/alumno/ficha.html/<?= $candidatoCursoDO->getFkPersona() ?>"><?= $this->personasIDX[$candidatoCursoDO->getFkPersona()]->getVNombre() . ' ' . $this->personasIDX[$candidatoCursoDO->getFkPersona()]->getVPrimerApellido() . ' ' . $this->personasIDX[$candidatoCursoDO->getFkPersona()]->getVSegundoApellido() ?></a></td>
		            		</tr>
		            		
		            		<?
						}
					
					?></tbody>
					</table>
				</div>
				<div class="separadorH"></div><?
				
			}
			
			// Alumnos
			if ( count($this->alumnosCursoCOL) > 0 ){
	
				?><h3>Alumnos asignados al curso</h3>
				
				<div class="scroll">
					<table class="listado fijo">
						<thead>
							<tr>
								<th>Nombre</th>
							</tr>
						</thead>
						<tbody>
						<?
					
						$alter = true;
						foreach ( $this->alumnosCursoCOL as $alumnoCursoDO ){
							
							$alter = !$alter;
							?>
							
		            		<tr <?= $alter ? 'class="alter"' : '' ?>>
		            			<td><a href="/alumno/ficha.html/<?= $alumnoCursoDO->getIPersona() ?>"><?= $this->personasIDX[$alumnoCursoDO->getIPersona()]->getVNombre() . ' ' . $this->personasIDX[$alumnoCursoDO->getIPersona()]->getVPrimerApellido() . ' ' . $this->personasIDX[$alumnoCursoDO->getIPersona()]->getVSegundoApellido() ?></a></td>
		            		</tr>
		            		
		            		<?
						}
					
					?></tbody>
					</table>
				</div>
				<div class="separadorH"></div><?
				
			}
		?>
		</div>
<?
		
	} else {
		
		?><h3>No se ha encontrado el curso</h3><?
		
	}
?>