<?php 

	if ( count($this->cursosCOL) > 0 ){

?>

<table class="listado">
    <thead>
		<tr>
			<th><a href="/curso/index.html/?ob=nom&o=<?=$this->order?>" <?=( ($this->orderBy == 'nom')?'class="ordenado ' . $this->order . '"':'' )?> >Nombre</a></th>
			<th><a href="/curso/index.html/?ob=ini&o=<?=$this->order?>" <?=( ($this->orderBy == 'ini')?'class="ordenado ' . $this->order . '"':'' )?> >Inicio</a></th>
			<th><a href="/curso/index.html/?ob=fin&o=<?=$this->order?>" <?=( ($this->orderBy == 'fin')?'class="ordenado ' . $this->order . '"':'' )?> >Fin</a></th>
			<th><a href="/curso/index.html/?ob=hor&o=<?=$this->order?>" <?=( ($this->orderBy == 'hor')?'class="ordenado ' . $this->order . '"':'' )?> >Horas</a></th>
			<th>Nº Acción</th>
			<th>Profesor</th>
			<th><a href="/curso/index.html/?ob=cen&o=<?=$this->order?>" <?=( ($this->orderBy == 'cen')?'class="ordenado ' . $this->order . '"':'' )?> >Centro</a></th>
			<?
			
				if ( $this->editar ){
					?><th>Editar</th>
					<th>Duplicar</th>		
					<th>Docs.</th>
					<th>Horario</th>
					<th>Alumnos</th>
					<th>Eliminar</th><?
				}
			
			?>
		</tr>
	</thead>
	<tbody>
		<?php
		
			$contador = 0;
			foreach ( $this->cursosCOL as $cursoDO ){
				
			    //$cursoDO = new TblCurso($db);
				$clase = ( ($contador%2)==0 )?'':'class="alter"';
				$contador++;
				
				?>
				<tr	<?= $clase ?> >
					<td><a href="/curso/ficha.html/<?= $cursoDO->getIdCurso() ?>"><?= $cursoDO->getVNombre() ?></a></td>
					<?php
					
					$fechaIni = OwlDate::getDiaMesAno($cursoDO->getDInicio());
					( $fechaIni == '01/01/1970' ) ? $fechaIni = '-' : '';
					$fechaFin = OwlDate::getDiaMesAno($cursoDO->getDFin());
					( $fechaFin == '01/01/1970' ) ? $fechaFin = '-' : '';
					
					?>
					<td><?= $fechaIni ?></td>
					<td><?= $fechaFin ?></td>
					<td><?= $cursoDO->getIHorasPresenciales() + $cursoDO->getIHorasDistancia() ?></td>
					<td><?= (is_null($cursoDO->getIAccion()) || $cursoDO->getIAccion() == 0) ? '-' : $cursoDO->getIAccion() ?></td>
					<td><?= ( array_key_exists($cursoDO->getIdCurso(), $this->profesoresCursosIDX) ) ? OwlString::limitaTexto($this->profesoresCursosIDX[$cursoDO->getIdCurso()], 20) : '-' ?></td>
					<td><?= ( array_key_exists($cursoDO->getFkCentro(), $this->centrosIDX) ) ? OwlString::limitaTexto($this->centrosIDX[$cursoDO->getFkCentro()], 20) : '-' ?></td>
					<?
			
						if ( $this->editar ){
							?>
							<td class="accion"><a href="/curso/editar.html/<?= $cursoDO->getIdCurso() ?>" class="btnEditar" title="Editar Curso"><span>editar</span></a></td>
							<td class="accion"><a href="/curso/duplicar.html/<?= $cursoDO->getIdCurso() ?>" class="btnDuplicar" title="Duplicar Curso"><span>duplicar</span></a></td>
							<td class="accion"><a href="/curso/documentacion.html/<?= $cursoDO->getIdCurso() ?>" class="btnDocumentacion" title="Documentación"><span>Documentación</span></a></td>
							<td class="accion"><a href="/curso/horario.html/<?= $cursoDO->getIdCurso() ?>" class="btnHorario" title="Horario"><span>horario</span></a></td>
							<td class="accion"><a href="/curso/alumnos.html/<?= $cursoDO->getIdCurso() ?>" class="btnAlumnos" title="Alumnos"><span>alumnos</span></a></td>
							<td class="accion"><a href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea eliminar el curso <strong><?= $cursoDO->getVNombre() ?></strong>?','/curso/eliminar.html/<?= $cursoDO->getIdCurso() ?>')" class="btnEliminar" title="Eliminar Curso"><span>eliminar</span></a></td>
							<?	
						}
					
					?>
				</tr>
				<?
				
			}
			
		?>
	</tbody>
</table>
<div id="paginadorContainer"><?= $this->paginador ?></div>

<?php

	} else {

?>

<h3>No hay ningún curso</h3>

<?php 

	}

?>