<?php
	$this->addJavascriptInclude('/js/centro.js');
	$this->echoOnHead($this->cabeceraMapa);
	$this->echoOnHead($this->mapa);
	
	if ( !is_null($this->popup) ){
    	echo '<script type="text/javascript">ventana' . ucfirst($this->popup['estado']) . '("' . $this->popup['titulo'] . '", "' . $this->popup['mensaje'] . '", "' . $this->popup['url'] . '");</script>'; 
	}
?>
    
    <form id="altaCentro" action="/centro/alta.html" method="post">
        <fieldset>
        
        	<legend>Alta de nuevo centro de formación</legend>
        
        	<input type="hidden" value="1" name="send" />
        
            <div class="campo controlado multi">
                <label for="nombre">Nombre*</label>
                <input type="text" name="nombre" id="nombre" class="campoTexto" />
                <p id="errorNombre" class="errorInput"><?=$this->errorNombre?></p>
            </div>
			
			<div class="campo controlado multi">
            	<label for="academia">Academia*</label>
	            <select class="grande desplegable" name="academia" id="academia">
	            	<option value=""></option>
					<?
					
					// Academia
					foreach ( $this->academiasIDX as $clave => $nombre) {
						
						?><option value="<?= $clave ?>" ><?= $nombre ?></option><?
						
					}
					
					?>
				</select>
				<p id="errorAcademia" class="errorInput"><?= $this->errorAcademia ?></p>
			</div>
			
			<div class="separadorH"></div>
			
			<div class="campo controlado multi">
            	<label for="pais">País*</label>
	            <select class="grande desplegable" name="pais" id="pais">
	            	<option value=""></option>
					<?
					
					// País
					foreach ( $this->paisesCOL as $paisDO) {
						?><option value="<?= $paisDO->getVIso() ?>" ><?= $paisDO->getVNombre() ?></option><?
						
					}
					
					?>
				</select>
				<p id="errorPais" class="errorInput"><?= $this->errorPais ?></p>
			</div>
			
			<div class="campo controlado multi">
            	<label for="provincia">Provincia*</label>
	            <select class="grande desplegable" name="provincia" id="provincia">
	            	<option value=""></option>
					<?
					
					// Provincia
					foreach ( $this->provinciasCOL as $provinciaDO) {
						
						?><option value="<?= $provinciaDO->getIdProvincia() ?>" ><?= $provinciaDO->getVNombre() ?></option><?
						
					}
					
					?>
				</select>
				<p id="errorProvincia" class="errorInput"><?= $this->errorProvincia ?></p>
			</div>
			
			<div class="separadorH"></div>
			
			<div class="campo multi">
            	<label for="direccion">Dirección</label>
	            <input type="text" name="direccion" id="direccion" class="campoTexto" />
			</div>
			
            <div class="campo multi">
                <label for="poblacion">Población</label>
                <input type="text" name="poblacion" id="poblacion" class="campoTexto" />
            </div>			
			
			<div class="campo multi">
            	<label for="telefono">Teléfono</label>
	            <input type="text" name="telefono" id="telefono" class="campoTexto mediano" />
			</div>
			
			<div class="separadorH"></div>
			
			<div class="bloque">
			
				<h3>Ubicación principal</h3>
			
				<div class="campo multi">
	            	<label for="latitud">Latitud</label>
		            <input type="text" name="latitud" id="latitud" class="campoTexto" />
				</div>
				
				<div class="campo multi">
	            	<label for="longitud">Longitud</label>
		            <input type="text" name="longitud" id="longitud" class="campoTexto" />
				</div>
				
				<div class="separadorH"></div>
				
				<div class="campo">
					<p class="desc">Marca en el mapa el emplazamiento del centro o <a href="javascript:obtenerCoordenadasDireccion()">Actualizar mapa con la dirección proporcionada</a><br/></p>
					<div id="mapa"></div>
				</div>
				
				<div class="separadorH"></div>
				
			</div>
			
			<h3>Datos adicionales</h3>
			
            <div class="campo">
                <label for="descripcion">Observaciones</label>
                <textarea rows="5" cols="40" name="descripcion" id="descripcion"></textarea>
            </div>
            
            <input class="oculto" type="submit" value="Guardar" />
            
            <noscript>
            	<div class="campo">
            		<input type="submit" value="Guardar" />
            	</div>
            </noscript>
            
        </fieldset>
    </form>