<?

	if ( !is_null($this->centroDO) ){
		
?>
		<div class="ficha">
			<p><strong>Nombre:</strong><span> <?= $this->centroDO->getVNombre() ?></span></p>
			<p><strong>Academia:</strong><span> <?= $this->centroDO->getTblEmpresa()->getVNombre() ?></span></p>
			<p><strong>País:</strong><span> <?= $this->centroDO->getTblPais()->getVNombre() ?></span></p>
			<p><strong>Provincia:</strong><span> <?= $this->centroDO->getTblProvincia()->getVNombre() ?></span></p>
			<?
			
			$telefono = $this->centroDO->getVTelefono();
			if ( !empty($telefono) ){
				?><p><strong>Teléfono:</strong><span> <?= $telefono ?></span></p><?
			}
			
			$descripcion = $this->centroDO->getVDescripcion();
			if ( !empty($descripcion) ){
				?><p class="extended"><strong>Descripción:</strong><span> <?= $descripcion ?></span></p><?
			}
			
			?>
		</div>
<?
		
	} else {
		
		?><h3>No se ha encontrado el centro</h3><?
		
	}
?>