<?

    if ( !is_null($this->consultoraDO) ){
        
?>
        <div class="ficha">
            <h3>Datos del usuario</h3>
            <p><strong>Nombre:</strong><span> <?= $this->usuarioDO->getVNombre() ?></span></p>
            <p><strong>Email:</strong><span> <?= $this->usuarioDO->getVEmail() ?></span></p>
        </div>
        
        <div class="ficha">
            <h3>Datos de la gestora</h3>
            <p><strong>Nombre:</strong><span> <?= $this->consultoraDO->getVNombre() ?></span></p>
            <p><strong>CIF:</strong><span> <?= $this->consultoraDO->getVCif() ?></span></p>
            <p><strong>País:</strong><span> <?= $this->consultoraDO->getTblPais()->getVNombre() ?></span></p>
            <p><strong>Provincia:</strong><span> <?= $this->consultoraDO->getTblProvincia()->getVNombre() ?></span></p>
            <?
            
            $poblacion = $this->consultoraDO->getVPoblacion();
            if ( !empty($poblacion) ){
                ?><p><strong>Población:</strong><span> <?= $poblacion ?></span></p><?
            }
            
            $direccion = $this->consultoraDO->getVDireccion();
            if ( !empty($direccion) ){
                ?><p><strong>Dirección:</strong><span> <?= $direccion ?></span></p><?
            }
            
            $cp = $this->consultoraDO->getVCp();
            if ( !empty($cp) ){
                ?><p><strong>CP:</strong><span> <?= $cp ?></span></p><?
            }
            
            $telefono1 = $this->consultoraDO->getVTelefono();
            if ( !empty($telefono1) ){
                ?><p><strong>Teléfono 1:</strong><span> <?= $telefono1 ?></span></p><?
            }
            
            $telefono2 = $this->consultoraDO->getVTelefono2();
            if ( !empty($telefono2) ){
                ?><p><strong>Teléfono 2:</strong><span> <?= $telefono2 ?></span></p><?
            }
            
            $fax = $this->consultoraDO->getVFax();
            if ( !empty($fax) ){
                ?><p><strong>Fax:</strong><span> <?= $fax ?></span></p><?
            }
            
            ?>
        </div>
<?
        
    } else {
        
        ?><h3>No se ha encontrado la gestora</h3><?
        
    }
?>