<?

	if ( !is_null($this->aulaDO) ){
		
?>
		<div class="ficha">
			<p><strong>Nombre:</strong><span> <?= $this->aulaDO->getVNombre() ?></span></p>
			<p><strong>Centro:</strong><span> <?= $this->aulaDO->getTblCentro()->getVNombre() ?></span></p>
			<p><strong>Capacidad:</strong><span> <?= $this->aulaDO->getICapacidad() ?></span></p>
			<p><strong>País:</strong><span> <?= $this->aulaDO->getTblPais()->getVNombre() ?></span></p>
			<p><strong>Provincia:</strong><span> <?= $this->aulaDO->getTblProvincia()->getVNombre() ?></span></p>
			<?
			
			$poblacion = $this->aulaDO->getVPoblacion();
			if ( !empty($poblacion) ){
				?><p><strong>Población:</strong><span> <?= $poblacion ?></span></p><?
			}
			
			$direccion = $this->aulaDO->getVDireccion();
			if ( !empty($direccion) ){
				?><p><strong>Dirección:</strong><span> <?= $direccion ?></span></p><?
			}
			
			$descripcion = $this->aulaDO->getVDescripcion();
			if ( !empty($descripcion) ){
				?><p class="extended"><strong>Descripción:</strong><span> <?= $descripcion ?></span></p><?
			}
			
			?>
		</div>
<?
		
	} else {
		
		?><h3>No se ha encontrado el aula</h3><?
		
	}
?>