<?php
	$this->addJavascriptInclude('/js/datos.js');
	
	if ( count($this->categoriasLaboralesCOL) > 0 ){

?>


<table class="listado">
    <thead>
		<tr>
			<th><a href="/datos/categorialaboral.html/?ob=nom&amp;o=<?=$this->order?>" <?=( ($this->orderBy == 'nom')?'class="ordenado ' . $this->order . '"':'' )?> >Nombre</a></th>
			<th>Eliminar</th>
			<th>Editar</th>
		</tr>
	</thead>
	<tbody>
		<?php
		
			$contador = 0;
			foreach ( $this->categoriasLaboralesCOL as $categoriaLaboralDO ){
				
				$clase = ( ($contador%2)==0 )?'':'class="alter"';
				$contador++;
				
				?>
				<tr	<?= $clase ?> >
					<td><?= $categoriaLaboralDO->getVNombre() ?></td>
					<td class="accion"><a href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea eliminar la categoría laboral <strong><?= $categoriaLaboralDO->getVNombre() ?></strong>?','/datos/eliminar.html/categorialaboral/<?= $categoriaLaboralDO->getIdCategoriaEmpleo() ?>')" class="btnEliminar" title="Eliminar categoría laboral"><span>eliminar</span></a></td>
					<td class="accion"><a href="/datos/categorialaboral.html/<?= $categoriaLaboralDO->getIdCategoriaEmpleo() ?>" class="btnEditar" title="Editar categoría laboral"><span>editar</span></a></td>
				</tr>
				<?
				
			}
			
		?>
	</tbody>
</table>
<div id="paginadorContainer"><?= $this->paginador ?></div>

<?php 

	} else {
	
?>

<h3 class="noResult">No hay ninguna categoría laboral</h3>

<?

	}

?>

<form id="formCategorialaboral" method="post">
	<fieldset>
	
		<?
		if ( !is_null($this->categoriaLaboralDO) ){
		?>
			<legend>Edición de categoría laboral</legend>
			<input type="hidden" name="<?= md5('send') ?>" value="<?= md5('editar') ?>" />
			<div class="campo">
				<input type="button" onclick="window.location='/datos/categorialaboral.html'" value="Nuevo" class="btnSubmit">
			</div>
		<?
		} else {
		?>
			<legend>Alta de nueva categoría laboral</legend>
			<input type="hidden" name="<?= md5('send') ?>" value="<?= md5('alta') ?>" />
		<?
		}
		?>
		
		<div class="campo controlado">
			<label for="nombre">Nombre</label>
			<input class="campoTexto" type="text" id="nombre" name="nombre" value="<?= (!is_null($this->categoriaLaboralDO)) ? $this->categoriaLaboralDO->getVNombre() : '' ?>"/>
			<p id="errorNombre" class="errorInput"><?=$this->errorNombre?></p>
		</div>
		
		<div class="campo">
			<?
			if ( !is_null($this->categoriaLaboralDO) ){
			?>
				<input type="submit" value="Editar" class="btnSubmit" />
			<?
			} else {
			?>
				<input type="submit" value="Añadir" class="btnSubmit" />
			<?
			}
			?>
		</div>
	</fieldset>
</form>