<?php
	$this->addJavascriptInclude('/js/datos.js');
	
	if ( count($this->estadosCivilesCOL) > 0 ){

?>


<table class="listado">
    <thead>
		<tr>
			<th><a href="/datos/estadoCivil.html/?ob=nom&amp;o=<?=$this->order?>" <?=( ($this->orderBy == 'nom')?'class="ordenado ' . $this->order . '"':'' )?> >Nombre</a></th>
			<th>Eliminar</th>
			<th>Editar</th>
		</tr>
	</thead>
	<tbody>
		<?php
		
			$contador = 0;
			foreach ( $this->estadosCivilesCOL as $estadoCivilDO ){
				
				$clase = ( ($contador%2)==0 )?'':'class="alter"';
				$contador++;
				
				?>
				<tr	<?= $clase ?> >
					<td><?= $estadoCivilDO->getVNombre() ?></td>
					<td class="accion"><a href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea eliminar el estado civil <strong><?= $estadoCivilDO->getVNombre() ?></strong>?','/datos/eliminar.html/estadoCivil/<?= $estadoCivilDO->getIdEstadoCivil() ?>')" class="btnEliminar" title="Eliminar estado civil"><span>eliminar</span></a></td>
					<td class="accion"><a href="/datos/estadoCivil.html/<?= $estadoCivilDO->getIdEstadoCivil() ?>" class="btnEditar" title="Editar estado civil"><span>editar</span></a></td>
				</tr>
				<?
				
			}
			
		?>
	</tbody>
</table>
<div id="paginadorContainer"><?= $this->paginador ?></div>

<?php 

	} else {
	
?>

<h3>No hay ningún estado civil</h3>

<?

	}

?>

<form id="formEstadoCivil" method="post">
	<fieldset>
	
		<?
		if ( !is_null($this->estadoCivilDO) ){
		?>
			<input type="hidden" name="<?= md5('send') ?>" value="<?= md5('editar') ?>" />
			<div class="campo">
				<input type="button" onclick="window.location='/datos/estadoCivil.html'" value="Nuevo" class="btnSubmit">
			</div>
		<?
		} else {
		?>
			<input type="hidden" name="<?= md5('send') ?>" value="<?= md5('alta') ?>" />
		<?
		}
		?>
		
		<div class="campo controlado">
			<label for="nombre">Nombre</label>
			<input class="campoTexto" type="text" id="nombre" name="nombre" value="<?= (!is_null($this->estadoCivilDO)) ? $this->estadoCivilDO->getVNombre() : '' ?>"/>
			<p id="errorNombre" class="errorInput"><?=$this->errorNombre?></p>
		</div>
		
		<div class="campo">
			<?
			if ( !is_null($this->estadoCivilDO) ){
			?>
				<input type="submit" value="Editar" class="btnSubmit" />
			<?
			} else {
			?>
				<input type="submit" value="Añadir" class="btnSubmit" />
			<?
			}
			?>
		</div>
	</fieldset>
</form>