<?php

if (count($this->identificacionesCOL) > 0){
	
	?><div class="col1">
		<table class="listado">
	    <thead>
			<tr>
				<th><a href="/datos/identificacion.html/?ob=nom&amp;o=<?=$this->order?>" <?=( ($this->orderBy == 'nom')?'class="ordenado ' . $this->order . '"':'' )?> >Nombre</a></th>
				<th>Eliminar</th>
				<th>Editar</th>
			</tr>
		</thead>
		<tbody>
			<?
			
				$contador = 0;
				foreach ( $this->identificacionesCOL as $identificacionDO ){
					
					$clase = ($contador%2) == 0 ? '' : 'class="alter"';
					$contador++;
					
					?>
					<tr	<?= $clase ?> >
						<td><?= $identificacionDO->getVNombre() ?></td>
						<td class="accion"><a href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea eliminar el tipo de identificacion <strong><?= $identificacionDO->getVNombre() ?></strong>?','/datos/eliminar.html/identificacion/<?= $identificacionDO->getIdTipoIdentificacion() ?>')" class="btnEliminar" title="Eliminar identificacion"><span>eliminar</span></a></td>
						<td class="accion"><a href="/datos/identificacion.html/<?= $identificacionDO->getIdTipoIdentificacion() ?>" class="btnEditar" title="Editar identificacion"><span>editar</span></a></td>
					</tr>
					<?
					
				}
				
			?>
		</tbody>
		</table>
		<div id="paginadorContainer"><?= $this->paginador ?></div>
	</div>
	<div class="col2">
		<form action="<?= $_SERVER['REQUEST_URI'] ?>" method="post">
			<fieldset>
				<?= $this->editar ? '<legend>Edición de tipo de identificación</legend>' : '<legend>Alta de nuevo tipo de identificación</legend>' ?>
				<input type="hidden" name="sent" value="1">
				<div class="campo">
					<label for="nombre">Nombre</label>
					<input type="text" name="nombre" id="nombre" class="campoTexto grande" value="<?= $this->nombre ?>" />
				</div>
				<div class="campo">
					<input type="submit" class="btnSubmit" value="<?= $this->editar ? 'Guardar' : 'Añadir' ?>" />
				</div>
			</fieldset>
		</form>
	</div>
	<div class="separadorH"></div><?
	
}

?>