<?php

if (count($this->requisitosCOL) > 0){
	
	?><div class="col1">
		<table class="listado">
	    <thead>
			<tr>
				<th><a href="/datos/requisito.html/?ob=nom&amp;o=<?=$this->order?>" <?=( ($this->orderBy == 'nom')?'class="ordenado ' . $this->order . '"':'' )?> >Nombre</a></th>
				<th><a href="/datos/requisito.html/?ob=desc&amp;o=<?=$this->order?>" <?=( ($this->orderBy == 'desc')?'class="ordenado ' . $this->order . '"':'' )?> >Descripción</a></th>
				<th>Eliminar</th>
				<th>Editar</th>
			</tr>
		</thead>
		<tbody>
			<?
			
				$contador = 0;
				foreach ( $this->requisitosCOL as $requisitoDO ){
					
					$clase = ($contador%2) == 0 ? '' : 'class="alter"';
					$contador++;
					
					?>
					<tr	<?= $clase ?> >
						<td><?= $requisitoDO->getVNombre() ?></td>
						<td><?= $requisitoDO->getVDescripcion() ?></td>
						<td class="accion"><a href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea eliminar el requisito <strong><?= $requisitoDO->getVNombre() ?></strong>?','/datos/eliminar.html/requisito/<?= $requisitoDO->getIdRequisito() ?>')" class="btnEliminar" title="Eliminar requisito"><span>eliminar</span></a></td>
						<td class="accion"><a href="/datos/requisito.html/<?= $requisitoDO->getIdRequisito() ?>" class="btnEditar" title="Editar requisito"><span>editar</span></a></td>
					</tr>
					<?
					
				}
				
			?>
		</tbody>
		</table>
		<div id="paginadorContainer"><?= $this->paginador ?></div>
	</div>
	<div class="col2">
		<form action="<?= $_SERVER['REQUEST_URI'] ?>" method="post">
			<fieldset>
				<?= $this->editar ? '<legend>Edición de requisito</legend>' : '<legend>Alta de nuevo requisito</legend>' ?>
				<input type="hidden" name="sent" value="1">
				<div class="campo">
					<label for="nombre">Nombre</label>
					<input type="text" name="nombre" id="nombre" class="campoTexto grande" value="<?= $this->nombre ?>" />
				</div>
				<div class="campo">
					<label for="desc">Descripción</label>
					<textarea rows="10" cols="80" class="campoTexto" id="desc" name="desc"><?= $this->desc ?></textarea>
				</div>
				<div class="campo">
					<input type="submit" class="btnSubmit" value="<?= $this->editar ? 'Guardar' : 'Añadir' ?>" />
				</div>
			</fieldset>
		</form>
	</div>
	<div class="separadorH"></div><?
	
}

?>