<?php
	$this->addJavascriptInclude('/js/datos.js');
	
	if ( count($this->tiposConvocatoriaCOL) > 0 ){

?>

<h3>Convocatorias existentes</h3>

<table class="listado">
    <thead>
		<tr>
			<th><a href="/datos/tiposConvocatoria.html/?ob=nom&amp;o=<?=$this->order?>" <?=( ($this->orderBy == 'nom')?'class="ordenado ' . $this->order . '"':'' )?> >Nombre</a></th>
			<th><a href="/datos/tiposConvocatoria.html/?ob=desc&amp;o=<?=$this->order?>" <?=( ($this->orderBy == 'desc')?'class="ordenado ' . $this->order . '"':'' )?> >Descripción</a></th>
			<th>Eliminar</th>
			<th>Editar</th>
		</tr>
	</thead>
	<tbody>
		<?
		
			$contador = 0;
			foreach ( $this->tiposConvocatoriaCOL as $tipoConvocatoriaDO ){
				
				$clase =  ($contador % 2) == 0 ? '' : 'class="alter"';
				$contador++;
				
				?>
				<tr	<?= $clase ?> >
					<td><?= $tipoConvocatoriaDO->getVNombre() ?></td>
					<td><?= $tipoConvocatoriaDO->getVDescripcion() ?></td>
					<td class="accion"><a href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea eliminar el tipo de convocatoria <strong><?= $tipoConvocatoriaDO->getVNombre() ?></strong>?','/datos/eliminar.html/tiposConvocatoria/<?= $tipoConvocatoriaDO->getIdTipoConvocatoria() ?>')" class="btnEliminar" title="Eliminar tipo de convocatoria"><span>eliminar</span></a></td>
					<td class="accion"><a href="/datos/tiposConvocatoria.html/<?= $tipoConvocatoriaDO->getIdTipoConvocatoria() ?>" class="btnEditar" title="Editar tipo de convocatoria"><span>editar</span></a></td>
				</tr>
				<?
				
			}
			
		?>
	</tbody>
</table>
<div id="paginadorContainer"><?= $this->paginador ?></div>
<? 

	} else {
	
?>
<h3 class="noResult">No hay ningún tipo de convocatoria</h3>
<?

	}

?>
<form id="formCarnet" method="post">
	<fieldset>
		<legend><?= $this->editar ? 'Edición de tipo de convocatoria' : 'Alta de nuevo tipo de convocatoria' ?></legend>
	
		<input type="hidden" name="sent" value="1" />
				
		<div class="campo controlado">
			<label for="nombre">Nombre</label>
			<input class="campoTexto" type="text" id="nombre" name="nombre" value="<?= (!is_null($this->tipoConvocatoriaDO)) ? $this->tipoConvocatoriaDO->getVNombre() : '' ?>"/>
			<p id="errorNombre" class="errorInput"><?=$this->errorNombre?></p>
		</div>
		
		<div class="campo controlado">
			<label for="descripcion">Descripción</label>
			<textarea rows="10" cols="80" id="descripcion" name="descripcion"><?= !is_null($this->tipoConvocatoriaDO) ? $this->tipoConvocatoriaDO->getVDescripcion() : '' ?></textarea>
			<p id="errorDescripcion" class="errorInput"><?=$this->errorDescripcion?></p>
		</div>
		<div class="campo">
			<?
			if ( !is_null($this->tipoConvocatoriaDO) ){
			?>
				<input type="submit" value="Editar" class="btnSubmit" />
			<?
			} else {
			?>
				<input type="submit" value="Añadir" class="btnSubmit" />
			<?
			}
			?>
		</div>
	</fieldset>
</form>