<h2>Listado de profesores</h2>

<?php 

	if ( count($this->profesoresCOL) > 0 ){

?>


<table class="listado">
    <thead>
        <tr>
            <th><a href="/profesor/index.html/?ob=id&o=<?=$this->order?>" <?=( ($this->orderBy == 'id')?'class="ordenado ' . $this->order . '"':'' )?> >Id</a></th>
            <th><a href="/profesor/index.html/?ob=nom&o=<?=$this->order?>" <?=( ($this->orderBy == 'nom')?'class="ordenado ' . $this->order . '"':'' )?> >Nombre</a></th>
            <th><a href="/profesor/index.html/?ob=pob&o=<?=$this->order?>" <?=( ($this->orderBy == 'pob')?'class="ordenado ' . $this->order . '"':'' )?> >Población</a></th>
            <th><a href="/profesor/index.html/?ob=mov&o=<?=$this->order?>" <?=( ($this->orderBy == 'mov')?'class="ordenado ' . $this->order . '"':'' )?> >Móvil</a></th>
            <th>Categorias</th><?
            
                if ( $this->editar ){
                    
                    ?><th>Eliminar</th>
                    <th>Editar</th>
                    <th>Duplicar</th><?
                     
                }
            
        ?></tr>
    </thead>
    <tbody><?
    
        $alter = true;
    
        foreach ($this->profesoresCOL as $profesorDO){
    
            $alter = !$alter;
            $clave = $profesorDO->getIdPersona();
            
            ?><tr <?= $alter ? 'class="alter"' : '' ?>>
                <td><?= $clave ?></td>
                <td><a href="/profesor/ficha/<?= $clave ?>"><?= $profesorDO->getVNombre() ?></a></td>
                <td><?= $profesorDO->getVPoblacion() ?></td>
                <td><?= $profesorDO->getVMovil() ?></td>
                <td><?
                
                if (array_key_exists($clave, $this->categoriasProfesoresIDX)){
                    
                    $categoriasProfesorARR = $this->categoriasProfesoresIDX[$clave];
                    $categoriasLabelsARR = array();
                    
                    foreach ($categoriasProfesorARR as $categoriaProfesorDO) {
                        
                        $categoriasLabelsARR[] =  $this->categoriasIDX[$categoriaProfesorDO->getFkCategoria()]->getVNombre();
                        
                    }
                    
                    echo implode(',', $categoriasLabelsARR);
                    
                    
                }
                ?></td><?
                
                if ( $this->editar ){
                	?><td class="accion"><a href="/profesor/eliminar/<?= $clave ?>" onclick="ventanaConfirmacion('Eliminar profesor', '¿Está seguro que desea eliminar el profesor <strong><?= $profesorDO->getVNombre() ?></strong>?', this.href); return false;" class="btnEliminar usuario" title="Eliminar Profesor"><span>eliminar</span></a></td>
                    <td class="accion"><a href="/profesor/editar.html/<?= $clave ?>" class="btnEditar" title="Editar Profesor"><span>editar</span></a></td>
                    <td class="accion"><a href="/profesor/duplicar.html/<?= $clave ?>" class="btnDuplicar" title="Duplicar Profesor"><span>duplicar</span></a></td><?
                }
                        
            ?></tr><?
        
        }
        
        ?>
    </tbody>
</table>
<div id="paginadorContainer"><?= $this->paginador ?></div>

<?php 

	} else {

?>

<h3>No hay ningún profesor</h3>

<?php 

	}

?>