<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblAula.
 *
 * @package dataAccess
 */
class TblAulaSearch{

    /**
     * Representa el atributo idAula.
     *
     * @var integer
     */
    public $idAula;

    /**
     * Representa el atributo fkCentro.
     *
     * @var integer
     */
    public $fkCentro;

    /**
     * Representa el atributo fkProvincia.
     *
     * @var integer
     */
    public $fkProvincia;

    /**
     * Representa el atributo fkPais.
     *
     * @var string
     */
    public $fkPais;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo iCapacidad.
     *
     * @var integer
     */
    public $iCapacidad;

    /**
     * Representa el atributo vDireccion.
     *
     * @var string
     */
    public $vDireccion;

    /**
     * Representa el atributo vDescripcion.
     *
     * @var string
     */
    public $vDescripcion;

    /**
     * Representa el atributo vPoblacion.
     *
     * @var string
     */
    public $vPoblacion;

    /**
     * Representa el atributo mod_user.
     *
     * @var string
     */
    public $modUser;

    /**
     * Representa el atributo last_modified.
     *
     * @var string
     */
    public $lastModified;
}
?>