<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 16 de December de 2010 a las 10:23:35
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblAlumno.
 *
 * @package dataAccess
 */
class TblAlumnoSearch{

    /**
     * Representa el atributo idAlumno.
     *
     * @var integer
     */
    public $idAlumno;

    /**
     * Representa el atributo fkCurso.
     *
     * @var integer
     */
    public $fkCurso;

    /**
     * Representa el atributo iPersona.
     *
     * @var integer
     */
    public $iPersona;

    /**
     * Representa el atributo iUsuario.
     *
     * @var integer
     */
    public $iUsuario;

    /**
     * Representa el atributo vPais.
     *
     * @var string
     */
    public $vPais;

    /**
     * Representa el atributo vProvincia.
     *
     * @var string
     */
    public $vProvincia;

    /**
     * Representa el atributo vTipoIdentificacion.
     *
     * @var string
     */
    public $vTipoIdentificacion;

    /**
     * Representa el atributo vEstadoCivil.
     *
     * @var string
     */
    public $vEstadoCivil;

    /**
     * Representa el atributo vEstadoLaboral.
     *
     * @var string
     */
    public $vEstadoLaboral;

    /**
     * Representa el atributo vNivelEstudios.
     *
     * @var string
     */
    public $vNivelEstudios;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vPrimerApellido.
     *
     * @var string
     */
    public $vPrimerApellido;

    /**
     * Representa el atributo vSegundoApellido.
     *
     * @var string
     */
    public $vSegundoApellido;

    /**
     * Representa el atributo vPoblacion.
     *
     * @var string
     */
    public $vPoblacion;

    /**
     * Representa el atributo vNumeroIdentificacion.
     *
     * @var string
     */
    public $vNumeroIdentificacion;

    /**
     * Representa el atributo vEmail.
     *
     * @var string
     */
    public $vEmail;

    /**
     * Representa el atributo vDireccion.
     *
     * @var string
     */
    public $vDireccion;

    /**
     * Representa el atributo bActiva.
     *
     * @var boolean
     */
    public $bActiva;

    /**
     * Representa el atributo dAlta.
     *
     * @var string
     */
    public $dAlta;

    /**
     * Representa el atributo dNacimiento.
     *
     * @var string
     */
    public $dNacimiento;

    /**
     * Representa el atributo dBaja.
     *
     * @var string
     */
    public $dBaja;

    /**
     * Representa el atributo vNumeroSS.
     *
     * @var string
     */
    public $vNumeroSS;
}
?>