<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 02 de November de 2010 a las 12:43:46
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblAlumno.
 *
 * @package dataAccess
 */
class TblAlumnoSearch{

    /**
     * Representa el atributo idAlumno.
     *
     * @var integer
     */
    public $idAlumno;

    /**
     * Representa el atributo fkEstadoCivil.
     *
     * @var integer
     */
    public $fkEstadoCivil;

    /**
     * Representa el atributo fkEstadoLaboral.
     *
     * @var integer
     */
    public $fkEstadoLaboral;

    /**
     * Representa el atributo fkCurso.
     *
     * @var integer
     */
    public $fkCurso;

    /**
     * Representa el atributo fkPais.
     *
     * @var string
     */
    public $fkPais;

    /**
     * Representa el atributo fkTipoIdentificacion.
     *
     * @var integer
     */
    public $fkTipoIdentificacion;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vPrimerApellido.
     *
     * @var string
     */
    public $vPrimerApellido;

    /**
     * Representa el atributo vSegundoApellido.
     *
     * @var string
     */
    public $vSegundoApellido;

    /**
     * Representa el atributo vPoblacion.
     *
     * @var string
     */
    public $vPoblacion;

    /**
     * Representa el atributo iUsuario.
     *
     * @var integer
     */
    public $iUsuario;

    /**
     * Representa el atributo vNumeroIdentificacion.
     *
     * @var string
     */
    public $vNumeroIdentificacion;

    /**
     * Representa el atributo vEmail.
     *
     * @var string
     */
    public $vEmail;

    /**
     * Representa el atributo vDireccion.
     *
     * @var string
     */
    public $vDireccion;

    /**
     * Representa el atributo bActiva.
     *
     * @var boolean
     */
    public $bActiva;

    /**
     * Representa el atributo dAlta.
     *
     * @var string
     */
    public $dAlta;

    /**
     * Representa el atributo dNacimiento.
     *
     * @var string
     */
    public $dNacimiento;

    /**
     * Representa el atributo dBaja.
     *
     * @var string
     */
    public $dBaja;
}
?>