<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 22 de October de 2010 a las 13:48:57
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla tblAcceso.
 *
 * @package dataAccess
 */
class TblAccesoPK{

    /**
     * Representa el atributo idAcceso.
     *
     * @var integer
     */
    public $idAcceso;

    /**
     * Representa el atributo fkPadre.
     *
     * @var integer
     */
    public $fkPadre;
}
?>