<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblAvatar.
 *
 * @package dataAccess
 */
class TblAvatarSearch{

    /**
     * Representa el atributo idAvatar.
     *
     * @var integer
     */
    public $idAvatar;

    /**
     * Representa el atributo fkUsuario.
     *
     * @var integer
     */
    public $fkUsuario;

    /**
     * Representa el atributo vArchivo.
     *
     * @var string
     */
    public $vArchivo;

    /**
     * Representa el atributo bActivo.
     *
     * @var boolean
     */
    public $bActivo;

    /**
     * Representa el atributo iAncho.
     *
     * @var integer
     */
    public $iAncho;

    /**
     * Representa el atributo iAlto.
     *
     * @var integer
     */
    public $iAlto;

    /**
     * Representa el atributo vMime.
     *
     * @var string
     */
    public $vMime;

    /**
     * Representa el atributo vTamano.
     *
     * @var string
     */
    public $vTamano;
}
?>