<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 11 de January de 2011 a las 08:52:54
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblCurso.
 *
 * @package dataAccess
 */
class TblCursoSearch{

    /**
     * Representa el atributo idCurso.
     *
     * @var integer
     */
    public $idCurso;

    /**
     * Representa el atributo fkPlan.
     *
     * @var integer
     */
    public $fkPlan;

    /**
     * Representa el atributo fkCategoria.
     *
     * @var integer
     */
    public $fkCategoria;

    /**
     * Representa el atributo fkColectivo.
     *
     * @var integer
     */
    public $fkColectivo;

    /**
     * Representa el atributo fkModalidad.
     *
     * @var integer
     */
    public $fkModalidad;

    /**
     * Representa el atributo fkCentro.
     *
     * @var integer
     */
    public $fkCentro;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo bNotificacionInicio.
     *
     * @var boolean
     */
    public $bNotificacionInicio;

    /**
     * Representa el atributo bNotificacionFin.
     *
     * @var boolean
     */
    public $bNotificacionFin;

    /**
     * Representa el atributo vDescripcion.
     *
     * @var string
     */
    public $vDescripcion;

    /**
     * Representa el atributo iHorasPresenciales.
     *
     * @var integer
     */
    public $iHorasPresenciales;

    /**
     * Representa el atributo iHorasDistancia.
     *
     * @var integer
     */
    public $iHorasDistancia;

    /**
     * Representa el atributo dInicio.
     *
     * @var string
     */
    public $dInicio;

    /**
     * Representa el atributo dFin.
     *
     * @var string
     */
    public $dFin;

    /**
     * Representa el atributo iNumeroAlumnos.
     *
     * @var integer
     */
    public $iNumeroAlumnos;

    /**
     * Representa el atributo mod_user.
     *
     * @var string
     */
    public $modUser;

    /**
     * Representa el atributo last_modified.
     *
     * @var string
     */
    public $lastModified;

    /**
     * Representa el atributo iGrupo.
     *
     * @var integer
     */
    public $iGrupo;

    /**
     * Representa el atributo iAccion.
     *
     * @var string
     */
    public $iAccion;

    /**
     * Representa el atributo vObservaciones.
     *
     * @var string
     */
    public $vObservaciones;

    /**
     * Representa el atributo vExpediente.
     *
     * @var string
     */
    public $vExpediente;
}
?>