<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblCurso.
 *
 * @package dataAccess
 */
class TblCursoSearch{

    /**
     * Representa el atributo idCurso.
     *
     * @var integer
     */
    public $idCurso;

    /**
     * Representa el atributo fkPlan.
     *
     * @var integer
     */
    public $fkPlan;

    /**
     * Representa el atributo fkCategoria.
     *
     * @var integer
     */
    public $fkCategoria;

    /**
     * Representa el atributo fkColectivo.
     *
     * @var integer
     */
    public $fkColectivo;

    /**
     * Representa el atributo fkSector.
     *
     * @var integer
     */
    public $fkSector;

    /**
     * Representa el atributo fkModalidad.
     *
     * @var integer
     */
    public $fkModalidad;

    /**
     * Representa el atributo fkAula.
     *
     * @var integer
     */
    public $fkAula;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo iHorasPresenciales.
     *
     * @var integer
     */
    public $iHorasPresenciales;

    /**
     * Representa el atributo iHorasDistancia.
     *
     * @var integer
     */
    public $iHorasDistancia;

    /**
     * Representa el atributo iHorasTutoria.
     *
     * @var integer
     */
    public $iHorasTutoria;

    /**
     * Representa el atributo dInicio.
     *
     * @var string
     */
    public $dInicio;

    /**
     * Representa el atributo dFin.
     *
     * @var string
     */
    public $dFin;

    /**
     * Representa el atributo iNumeroAlumnos.
     *
     * @var integer
     */
    public $iNumeroAlumnos;

    /**
     * Representa el atributo mod_user.
     *
     * @var string
     */
    public $modUser;

    /**
     * Representa el atributo last_modified.
     *
     * @var string
     */
    public $lastModified;
}
?>