<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblCategoria.
 *
 * @package dataAccess
 */
class TblCategoriaSearch{

    /**
     * Representa el atributo idCategoria.
     *
     * @var integer
     */
    public $idCategoria;

    /**
     * Representa el atributo fkPadre.
     *
     * @var integer
     */
    public $fkPadre;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vDescripcion.
     *
     * @var string
     */
    public $vDescripcion;
}
?>