<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla tblCategoria.
 *
 * @package dataAccess
 */
class TblCategoriaPK{

    /**
     * Representa el atributo idCategoria.
     *
     * @var integer
     */
    public $idCategoria;

    /**
     * Representa el atributo fkPadre.
     *
     * @var integer
     */
    public $fkPadre;
}
?>