<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla tblCategoria.
 *
 * @package dataAccess
 */
class TblCategoriaPK{

    /**
     * Representa el atributo idCategoria.
     *
     * @var integer
     */
    public $idCategoria;

    /**
     * Representa el atributo fkPadre.
     *
     * @var integer
     */
    public $fkPadre;
}
?>