<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 16 de December de 2010 a las 04:06:51
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblCategoriaEmpleo.
 *
 * @package dataAccess
 */
class TblCategoriaEmpleoSearch{

    /**
     * Representa el atributo idCategoriaEmpleo.
     *
     * @var integer
     */
    public $idCategoriaEmpleo;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;
}
?>