<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblConvocatoria.
 *
 * @package dataAccess
 */
class TblConvocatoriaSearch{

    /**
     * Representa el atributo idConvocatoria.
     *
     * @var integer
     */
    public $idConvocatoria;

    /**
     * Representa el atributo fkTipoConvocatoria.
     *
     * @var integer
     */
    public $fkTipoConvocatoria;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vDescripcion.
     *
     * @var string
     */
    public $vDescripcion;

    /**
     * Representa el atributo ePresupuesto.
     *
     * @var string
     */
    public $ePresupuesto;

    /**
     * Representa el atributo mod_user.
     *
     * @var string
     */
    public $modUser;

    /**
     * Representa el atributo last_modified.
     *
     * @var string
     */
    public $lastModified;
}
?>