<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblCentro.
 *
 * @package dataAccess
 */
class TblCentroSearch{

    /**
     * Representa el atributo idCentro.
     *
     * @var integer
     */
    public $idCentro;

    /**
     * Representa el atributo fkProvincia.
     *
     * @var integer
     */
    public $fkProvincia;

    /**
     * Representa el atributo fkPais.
     *
     * @var string
     */
    public $fkPais;

    /**
     * Representa el atributo fkEmpresa.
     *
     * @var integer
     */
    public $fkEmpresa;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vPoblacion.
     *
     * @var string
     */
    public $vPoblacion;

    /**
     * Representa el atributo vTelefono.
     *
     * @var string
     */
    public $vTelefono;

    /**
     * Representa el atributo vLatitud.
     *
     * @var string
     */
    public $vLatitud;

    /**
     * Representa el atributo vLongitud.
     *
     * @var string
     */
    public $vLongitud;

    /**
     * Representa el atributo vDireccion.
     *
     * @var string
     */
    public $vDireccion;

    /**
     * Representa el atributo vDescripcion.
     *
     * @var string
     */
    public $vDescripcion;

    /**
     * Representa el atributo mod_user.
     *
     * @var string
     */
    public $modUser;

    /**
     * Representa el atributo last_modified.
     *
     * @var string
     */
    public $lastModified;
}
?>