<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 16 de December de 2010 a las 04:06:51
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla tblCategoriaEmpleo.
 *
 * @package dataAccess
 */
class TblCategoriaEmpleoPK{

    /**
     * Representa el atributo idCategoriaEmpleo.
     *
     * @var integer
     */
    public $idCategoriaEmpleo;
}
?>