<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblCurso.
 *
 * @package dataAccess
 */
class TblCursoSearch{

    /**
     * Representa el atributo idCurso.
     *
     * @var integer
     */
    public $idCurso;

    /**
     * Representa el atributo fkPlan.
     *
     * @var integer
     */
    public $fkPlan;

    /**
     * Representa el atributo fkCategoria.
     *
     * @var integer
     */
    public $fkCategoria;

    /**
     * Representa el atributo fkColectivo.
     *
     * @var integer
     */
    public $fkColectivo;

    /**
     * Representa el atributo fkSector.
     *
     * @var integer
     */
    public $fkSector;

    /**
     * Representa el atributo fkModalidad.
     *
     * @var integer
     */
    public $fkModalidad;

    /**
     * Representa el atributo fkAula.
     *
     * @var integer
     */
    public $fkAula;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vDescripcion.
     *
     * @var string
     */
    public $vDescripcion;

    /**
     * Representa el atributo iHorasPresenciales.
     *
     * @var integer
     */
    public $iHorasPresenciales;

    /**
     * Representa el atributo iHorasDistancia.
     *
     * @var integer
     */
    public $iHorasDistancia;

    /**
     * Representa el atributo iHorasTutoria.
     *
     * @var integer
     */
    public $iHorasTutoria;

    /**
     * Representa el atributo dInicio.
     *
     * @var string
     */
    public $dInicio;

    /**
     * Representa el atributo dFin.
     *
     * @var string
     */
    public $dFin;

    /**
     * Representa el atributo iNumeroAlumnos.
     *
     * @var integer
     */
    public $iNumeroAlumnos;

    /**
     * Representa el atributo mod_user.
     *
     * @var string
     */
    public $modUser;

    /**
     * Representa el atributo last_modified.
     *
     * @var string
     */
    public $lastModified;

    /**
     * Representa el atributo iHorasManana.
     *
     * @var integer
     */
    public $iHorasManana;

    /**
     * Representa el atributo iHorasTarde.
     *
     * @var integer
     */
    public $iHorasTarde;

    /**
     * Representa el atributo iDeManana.
     *
     * @var string
     */
    public $iDeManana;

    /**
     * Representa el atributo iAManana.
     *
     * @var string
     */
    public $iAManana;

    /**
     * Representa el atributo iDeTarde.
     *
     * @var string
     */
    public $iDeTarde;

    /**
     * Representa el atributo iATarde.
     *
     * @var string
     */
    public $iATarde;

    /**
     * Representa el atributo iGrupo.
     *
     * @var integer
     */
    public $iGrupo;

    /**
     * Representa el atributo iAccion.
     *
     * @var integer
     */
    public $iAccion;

    /**
     * Representa el atributo iSesion.
     *
     * @var integer
     */
    public $iSesion;
}
?>