<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 15 de December de 2010 a las 08:27:58
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblCobroParo.
 *
 * @package dataAccess
 */
class TblCobroParoSearch{

    /**
     * Representa el atributo idCobroParo.
     *
     * @var integer
     */
    public $idCobroParo;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;
}
?>