<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla tblDisponibilidadAula.
 *
 * @package dataAccess
 */
class TblDisponibilidadAulaPK{

    /**
     * Representa el atributo idDisponibilidadAula.
     *
     * @var integer
     */
    public $idDisponibilidadAula;
}
?>