<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblDisponibilidadAula.
 *
 * @package dataAccess
 */
class TblDisponibilidadAulaSearch{

    /**
     * Representa el atributo idDisponibilidadAula.
     *
     * @var integer
     */
    public $idDisponibilidadAula;

    /**
     * Representa el atributo fkAula.
     *
     * @var integer
     */
    public $fkAula;

    /**
     * Representa el atributo dInicio.
     *
     * @var string
     */
    public $dInicio;

    /**
     * Representa el atributo dFin.
     *
     * @var string
     */
    public $dFin;
}
?>