<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 02 de November de 2010 a las 12:43:46
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla tblDisponibilidadProfesor.
 *
 * @package dataAccess
 */
class TblDisponibilidadProfesorPK{

    /**
     * Representa el atributo idDisponibilidad.
     *
     * @var integer
     */
    public $idDisponibilidad;
}
?>