<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblDisponibilidadAula.
 *
 * @package dataAccess
 */
class TblDisponibilidadAulaSearch{

    /**
     * Representa el atributo idDisponibilidadAula.
     *
     * @var integer
     */
    public $idDisponibilidadAula;

    /**
     * Representa el atributo fkAula.
     *
     * @var integer
     */
    public $fkAula;

    /**
     * Representa el atributo dInicio.
     *
     * @var string
     */
    public $dInicio;

    /**
     * Representa el atributo dFin.
     *
     * @var string
     */
    public $dFin;
}
?>