<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla tblDisponibilidadProfesor.
 *
 * @package dataAccess
 */
class TblDisponibilidadProfesorPK{

    /**
     * Representa el atributo idDisponibilidad.
     *
     * @var integer
     */
    public $idDisponibilidad;
}
?>