<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblDocumento.
 *
 * @package dataAccess
 */
class TblDocumentoSearch{

    /**
     * Representa el atributo idDocumento.
     *
     * @var integer
     */
    public $idDocumento;

    /**
     * Representa el atributo vRealName.
     *
     * @var string
     */
    public $vRealName;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vMime.
     *
     * @var string
     */
    public $vMime;

    /**
     * Representa el atributo vTamano.
     *
     * @var string
     */
    public $vTamano;

    /**
     * Representa el atributo vDescription.
     *
     * @var string
     */
    public $vDescription;

    /**
     * Representa el atributo mod_user.
     *
     * @var string
     */
    public $modUser;

    /**
     * Representa el atributo last_modified.
     *
     * @var string
     */
    public $lastModified;
}
?>