<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblDisponibilidadProfesor.
 *
 * @package dataAccess
 */
class TblDisponibilidadProfesorSearch{

    /**
     * Representa el atributo idDisponibilidadProfesor.
     *
     * @var integer
     */
    public $idDisponibilidadProfesor;

    /**
     * Representa el atributo fkProfesor.
     *
     * @var integer
     */
    public $fkProfesor;

    /**
     * Representa el atributo dInicio.
     *
     * @var string
     */
    public $dInicio;

    /**
     * Representa el atributo dFin.
     *
     * @var string
     */
    public $dFin;
}
?>