<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla tblDisponibilidadProfesor.
 *
 * @package dataAccess
 */
class TblDisponibilidadProfesorPK{

    /**
     * Representa el atributo idDisponibilidadProfesor.
     *
     * @var integer
     */
    public $idDisponibilidadProfesor;
}
?>