<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblDocumentacion.
 *
 * @package dataAccess
 */
class TblDocumentacionSearch{

    /**
     * Representa el atributo idDocumentacion.
     *
     * @var integer
     */
    public $idDocumentacion;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vMime.
     *
     * @var string
     */
    public $vMime;

    /**
     * Representa el atributo vTamano.
     *
     * @var string
     */
    public $vTamano;
}
?>