<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblDocumento.
 *
 * @package dataAccess
 */
class TblDocumentoSearch{

    /**
     * Representa el atributo idDocumento.
     *
     * @var integer
     */
    public $idDocumento;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vMime.
     *
     * @var string
     */
    public $vMime;

    /**
     * Representa el atributo vTamano.
     *
     * @var string
     */
    public $vTamano;
}
?>