<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblDisponibilidadProfesor.
 *
 * @package dataAccess
 */
class TblDisponibilidadProfesorSearch{

    /**
     * Representa el atributo fkPersona.
     *
     * @var integer
     */
    public $fkPersona;

    /**
     * Representa el atributo dInicio.
     *
     * @var string
     */
    public $dInicio;

    /**
     * Representa el atributo dFin.
     *
     * @var string
     */
    public $dFin;

    /**
     * Representa el atributo idDisponibilidad.
     *
     * @var integer
     */
    public $idDisponibilidad;
}
?>