<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 02 de November de 2010 a las 12:43:46
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblDisponibilidadProfesor.
 *
 * @package dataAccess
 */
class TblDisponibilidadProfesorSearch{

    /**
     * Representa el atributo tblPersona_idPersona.
     *
     * @var integer
     */
    public $tblPersonaIdPersona;

    /**
     * Representa el atributo dInicio.
     *
     * @var string
     */
    public $dInicio;

    /**
     * Representa el atributo dFin.
     *
     * @var string
     */
    public $dFin;

    /**
     * Representa el atributo idDisponibilidad.
     *
     * @var integer
     */
    public $idDisponibilidad;
}
?>