<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblDesiderata.
 *
 * @package dataAccess
 */
class TblDesiderataSearch{

    /**
     * Representa el atributo idDesiderata.
     *
     * @var integer
     */
    public $idDesiderata;

    /**
     * Representa el atributo fkPersona.
     *
     * @var integer
     */
    public $fkPersona;

    /**
     * Representa el atributo vDescripcion.
     *
     * @var string
     */
    public $vDescripcion;
}
?>