<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblEstadoLaboral.
 *
 * @package dataAccess
 */
class TblEstadoLaboralSearch{

    /**
     * Representa el atributo idEstadoLaboral.
     *
     * @var integer
     */
    public $idEstadoLaboral;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;
}
?>