<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblEmpresa.
 *
 * @package dataAccess
 */
class TblEmpresaSearch{

    /**
     * Representa el atributo idEmpresa.
     *
     * @var integer
     */
    public $idEmpresa;

    /**
     * Representa el atributo fkPais.
     *
     * @var string
     */
    public $fkPais;

    /**
     * Representa el atributo fkProvincia.
     *
     * @var integer
     */
    public $fkProvincia;

    /**
     * Representa el atributo fkUsuario.
     *
     * @var integer
     */
    public $fkUsuario;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vCif.
     *
     * @var string
     */
    public $vCif;

    /**
     * Representa el atributo vPoblacion.
     *
     * @var string
     */
    public $vPoblacion;

    /**
     * Representa el atributo vDireccion.
     *
     * @var string
     */
    public $vDireccion;

    /**
     * Representa el atributo vCp.
     *
     * @var string
     */
    public $vCp;

    /**
     * Representa el atributo vTelefono.
     *
     * @var string
     */
    public $vTelefono;

    /**
     * Representa el atributo vTelefono2.
     *
     * @var string
     */
    public $vTelefono2;

    /**
     * Representa el atributo vFax.
     *
     * @var string
     */
    public $vFax;

    /**
     * Representa el atributo bActiva.
     *
     * @var boolean
     */
    public $bActiva;

    /**
     * Representa el atributo dAlta.
     *
     * @var string
     */
    public $dAlta;

    /**
     * Representa el atributo dBaja.
     *
     * @var string
     */
    public $dBaja;

    /**
     * Representa el atributo mod_user.
     *
     * @var string
     */
    public $modUser;

    /**
     * Representa el atributo last_modified.
     *
     * @var string
     */
    public $lastModified;
}
?>