<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 29 de December de 2010 a las 08:23:55
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblEstudio.
 *
 * @package dataAccess
 */
class TblEstudioSearch{

    /**
     * Representa el atributo idEstudio.
     *
     * @var integer
     */
    public $idEstudio;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vDescripcion.
     *
     * @var string
     */
    public $vDescripcion;
}
?>