<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblEstadoCivil.
 *
 * @package dataAccess
 */
class TblEstadoCivilSearch{

    /**
     * Representa el atributo idEstadoCivil.
     *
     * @var integer
     */
    public $idEstadoCivil;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;
}
?>