<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 13 de December de 2010 a las 08:54:13
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblHorario.
 *
 * @package dataAccess
 */
class TblHorarioSearch{

    /**
     * Representa el atributo idHorario.
     *
     * @var integer
     */
    public $idHorario;

    /**
     * Representa el atributo fkCurso.
     *
     * @var integer
     */
    public $fkCurso;

    /**
     * Representa el atributo dDia.
     *
     * @var string
     */
    public $dDia;

    /**
     * Representa el atributo iDesde.
     *
     * @var string
     */
    public $iDesde;

    /**
     * Representa el atributo iHasta.
     *
     * @var string
     */
    public $iHasta;

    /**
     * Representa el atributo iSesion.
     *
     * @var integer
     */
    public $iSesion;
}
?>