<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblHorario.
 *
 * @package dataAccess
 */
class TblHorarioSearch{

    /**
     * Representa el atributo idHorario.
     *
     * @var integer
     */
    public $idHorario;

    /**
     * Representa el atributo iDesde.
     *
     * @var integer
     */
    public $iDesde;

    /**
     * Representa el atributo iHasta.
     *
     * @var integer
     */
    public $iHasta;

    /**
     * Representa el atributo fkCurso.
     *
     * @var integer
     */
    public $fkCurso;
}
?>