<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblMaterialCurso.
 *
 * @package dataAccess
 */
class TblMaterialCursoSearch{

    /**
     * Representa el atributo idMaterialCurso.
     *
     * @var integer
     */
    public $idMaterialCurso;

    /**
     * Representa el atributo fkCurso.
     *
     * @var integer
     */
    public $fkCurso;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vDescripcion.
     *
     * @var string
     */
    public $vDescripcion;

    /**
     * Representa el atributo iCantidad.
     *
     * @var integer
     */
    public $iCantidad;

    /**
     * Representa el atributo ePrecio.
     *
     * @var string
     */
    public $ePrecio;
}
?>