<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblNotificacion.
 *
 * @package dataAccess
 */
class TblNotificacionSearch{

    /**
     * Representa el atributo idNotificacion.
     *
     * @var integer
     */
    public $idNotificacion;

    /**
     * Representa el atributo vAsunto.
     *
     * @var string
     */
    public $vAsunto;

    /**
     * Representa el atributo vMensaje.
     *
     * @var string
     */
    public $vMensaje;
}
?>