<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 02 de November de 2010 a las 12:43:47
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblPersona.
 *
 * @package dataAccess
 */
class TblPersonaSearch{

    /**
     * Representa el atributo idPersona.
     *
     * @var integer
     */
    public $idPersona;

    /**
     * Representa el atributo fkUsuario.
     *
     * @var integer
     */
    public $fkUsuario;

    /**
     * Representa el atributo fkPais.
     *
     * @var string
     */
    public $fkPais;

    /**
     * Representa el atributo fkProvincia.
     *
     * @var integer
     */
    public $fkProvincia;

    /**
     * Representa el atributo fkTipoIdentificacion.
     *
     * @var integer
     */
    public $fkTipoIdentificacion;

    /**
     * Representa el atributo fkEstadoCivil.
     *
     * @var integer
     */
    public $fkEstadoCivil;

    /**
     * Representa el atributo fkEstadoLaboral.
     *
     * @var integer
     */
    public $fkEstadoLaboral;

    /**
     * Representa el atributo fkNivelEstudios.
     *
     * @var integer
     */
    public $fkNivelEstudios;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vPrimerApellido.
     *
     * @var string
     */
    public $vPrimerApellido;

    /**
     * Representa el atributo vSegundoApellido.
     *
     * @var string
     */
    public $vSegundoApellido;

    /**
     * Representa el atributo vPoblacion.
     *
     * @var string
     */
    public $vPoblacion;

    /**
     * Representa el atributo vCp.
     *
     * @var string
     */
    public $vCp;

    /**
     * Representa el atributo vNumeroIdentificacion.
     *
     * @var string
     */
    public $vNumeroIdentificacion;

    /**
     * Representa el atributo vDireccion.
     *
     * @var string
     */
    public $vDireccion;

    /**
     * Representa el atributo vTelefono.
     *
     * @var string
     */
    public $vTelefono;

    /**
     * Representa el atributo vMovil.
     *
     * @var string
     */
    public $vMovil;

    /**
     * Representa el atributo bActiva.
     *
     * @var boolean
     */
    public $bActiva;

    /**
     * Representa el atributo dAlta.
     *
     * @var string
     */
    public $dAlta;

    /**
     * Representa el atributo dNacimiento.
     *
     * @var string
     */
    public $dNacimiento;

    /**
     * Representa el atributo dBaja.
     *
     * @var string
     */
    public $dBaja;

    /**
     * Representa el atributo mod_user.
     *
     * @var string
     */
    public $modUser;

    /**
     * Representa el atributo last_modified.
     *
     * @var string
     */
    public $lastModified;
}
?>