<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblPais.
 *
 * @package dataAccess
 */
class TblPaisSearch{

    /**
     * Representa el atributo vIso.
     *
     * @var string
     */
    public $vIso;

    /**
     * Representa el atributo vNombre_es.
     *
     * @var string
     */
    public $vNombreEs;

    /**
     * Representa el atributo vNombre_ca.
     *
     * @var string
     */
    public $vNombreCa;

    /**
     * Representa el atributo vNombre_en.
     *
     * @var string
     */
    public $vNombreEn;
}
?>