<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblProvincia.
 *
 * @package dataAccess
 */
class TblProvinciaSearch{

    /**
     * Representa el atributo idProvincia.
     *
     * @var integer
     */
    public $idProvincia;

    /**
     * Representa el atributo vNombre_es.
     *
     * @var string
     */
    public $vNombreEs;

    /**
     * Representa el atributo vNombre_ca.
     *
     * @var string
     */
    public $vNombreCa;

    /**
     * Representa el atributo vNombre_en.
     *
     * @var string
     */
    public $vNombreEn;
}
?>