<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblPlan.
 *
 * @package dataAccess
 */
class TblPlanSearch{

    /**
     * Representa el atributo idPlan.
     *
     * @var integer
     */
    public $idPlan;

    /**
     * Representa el atributo fkTipoPlan.
     *
     * @var integer
     */
    public $fkTipoPlan;

    /**
     * Representa el atributo fkConvocatoria.
     *
     * @var integer
     */
    public $fkConvocatoria;

    /**
     * Representa el atributo fkEmpresaConsultora.
     *
     * @var integer
     */
    public $fkEmpresaConsultora;

    /**
     * Representa el atributo fkEmpresaPropietaria.
     *
     * @var integer
     */
    public $fkEmpresaPropietaria;

    /**
     * Representa el atributo fkEstadoPlan.
     *
     * @var integer
     */
    public $fkEstadoPlan;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vDescripcion.
     *
     * @var string
     */
    public $vDescripcion;

    /**
     * Representa el atributo ePresupuestoAsignado.
     *
     * @var string
     */
    public $ePresupuestoAsignado;

    /**
     * Representa el atributo mod_user.
     *
     * @var string
     */
    public $modUser;

    /**
     * Representa el atributo last_modified.
     *
     * @var string
     */
    public $lastModified;
}
?>