<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 21 de January de 2011 a las 10:11:21
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblTrabajoParo.
 *
 * @package dataAccess
 */
class TblTrabajoParoSearch{

    /**
     * Representa el atributo idTrabajoParo.
     *
     * @var integer
     */
    public $idTrabajoParo;

    /**
     * Representa el atributo vDescripcion.
     *
     * @var string
     */
    public $vDescripcion;
}
?>