<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblTipoConvocatoria.
 *
 * @package dataAccess
 */
class TblTipoConvocatoriaSearch{

    /**
     * Representa el atributo idTipoConvocatoria.
     *
     * @var integer
     */
    public $idTipoConvocatoria;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vDescripcion.
     *
     * @var string
     */
    public $vDescripcion;
}
?>