<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla tblTipoConvocatoria.
 *
 * @package dataAccess
 */
class TblTipoConvocatoriaPK{

    /**
     * Representa el atributo idTipoConvocatoria.
     *
     * @var integer
     */
    public $idTipoConvocatoria;
}
?>