<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 20 de December de 2010 a las 09:07:46
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblTutoria.
 *
 * @package dataAccess
 */
class TblTutoriaSearch{

    /**
     * Representa el atributo idTutoria.
     *
     * @var integer
     */
    public $idTutoria;

    /**
     * Representa el atributo fkCurso.
     *
     * @var integer
     */
    public $fkCurso;

    /**
     * Representa el atributo fkModalidad.
     *
     * @var integer
     */
    public $fkModalidad;

    /**
     * Representa el atributo fkTutor.
     *
     * @var integer
     */
    public $fkTutor;

    /**
     * Representa el atributo iHoras.
     *
     * @var integer
     */
    public $iHoras;

    /**
     * Representa el atributo bLunes.
     *
     * @var boolean
     */
    public $bLunes;

    /**
     * Representa el atributo bMartes.
     *
     * @var boolean
     */
    public $bMartes;

    /**
     * Representa el atributo bMiercoles.
     *
     * @var boolean
     */
    public $bMiercoles;

    /**
     * Representa el atributo bJueves.
     *
     * @var boolean
     */
    public $bJueves;

    /**
     * Representa el atributo bViernes.
     *
     * @var boolean
     */
    public $bViernes;

    /**
     * Representa el atributo bSabado.
     *
     * @var boolean
     */
    public $bSabado;

    /**
     * Representa el atributo bDomingo.
     *
     * @var boolean
     */
    public $bDomingo;

    /**
     * Representa el atributo iDesdeManana.
     *
     * @var string
     */
    public $iDesdeManana;

    /**
     * Representa el atributo iHastaManana.
     *
     * @var string
     */
    public $iHastaManana;

    /**
     * Representa el atributo iDesdeTarde.
     *
     * @var string
     */
    public $iDesdeTarde;

    /**
     * Representa el atributo iHastaTarde.
     *
     * @var string
     */
    public $iHastaTarde;
}
?>