<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblTipoPlan.
 *
 * @package dataAccess
 */
class TblTipoPlanSearch{

    /**
     * Representa el atributo idTipoPlan.
     *
     * @var integer
     */
    public $idTipoPlan;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vDescripcion.
     *
     * @var string
     */
    public $vDescripcion;
}
?>