<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblUsuario.
 *
 * @package dataAccess
 */
class TblUsuarioSearch{

    /**
     * Representa el atributo idUsuario.
     *
     * @var integer
     */
    public $idUsuario;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vPassword.
     *
     * @var string
     */
    public $vPassword;

    /**
     * Representa el atributo vEmail.
     *
     * @var string
     */
    public $vEmail;
}
?>