<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TblUsuario.
 *
 * @package dataAccess
 */
class TblUsuarioSearch{

    /**
     * Representa el atributo idUsuario.
     *
     * @var integer
     */
    public $idUsuario;

    /**
     * Representa el atributo vNombre.
     *
     * @var string
     */
    public $vNombre;

    /**
     * Representa el atributo vPassword.
     *
     * @var string
     */
    public $vPassword;

    /**
     * Representa el atributo vEmail.
     *
     * @var string
     */
    public $vEmail;
}
?>