<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 25 de October de 2010 a las 09:30:07
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelPersonaCategoria.
 *
 * @package dataAccess
 */
class TrelPersonaCategoriaSearch{

    /**
     * Representa el atributo fkPersona.
     *
     * @var integer
     */
    public $fkPersona;

    /**
     * Representa el atributo fkCategoria.
     *
     * @var integer
     */
    public $fkCategoria;
}
?>