<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 29 de December de 2010 a las 10:57:19
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla trelEstudioPersona.
 *
 * @package dataAccess
 */
class TrelEstudioPersonaPK{

    /**
     * Representa el atributo idEstudioPersona.
     *
     * @var integer
     */
    public $idEstudioPersona;

    /**
     * Representa el atributo fkTipoEstudio.
     *
     * @var integer
     */
    public $fkTipoEstudio;

    /**
     * Representa el atributo fkPersona.
     *
     * @var integer
     */
    public $fkPersona;
}
?>