<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 10 de December de 2010 a las 06:28:02
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelDocumentoConvocatoria.
 *
 * @package dataAccess
 */
class TrelDocumentoConvocatoriaSearch{

    /**
     * Representa el atributo fkConvocatoria.
     *
     * @var integer
     */
    public $fkConvocatoria;

    /**
     * Representa el atributo fkDocumento.
     *
     * @var integer
     */
    public $fkDocumento;
}
?>