<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla trelEquipamientoAula.
 *
 * @package dataAccess
 */
class TrelEquipamientoAulaPK{

    /**
     * Representa el atributo fkAula.
     *
     * @var integer
     */
    public $fkAula;

    /**
     * Representa el atributo fkEquipamiento.
     *
     * @var integer
     */
    public $fkEquipamiento;
}
?>