<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 02 de November de 2010 a las 15:44:10
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla trelPrecandidato.
 *
 * @package dataAccess
 */
class TrelPrecandidatoPK{

    /**
     * Representa el atributo fkPersona.
     *
     * @var integer
     */
    public $fkPersona;

    /**
     * Representa el atributo fkPlanCursoCentro.
     *
     * @var integer
     */
    public $fkPlanCursoCentro;
}
?>