<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelDocumentoCurso.
 *
 * @package dataAccess
 */
class TrelDocumentoCursoSearch{

    /**
     * Representa el atributo fkCurso.
     *
     * @var integer
     */
    public $fkCurso;

    /**
     * Representa el atributo fkDocumento.
     *
     * @var integer
     */
    public $fkDocumento;
}
?>