<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelNotificacionEmpresa.
 *
 * @package dataAccess
 */
class TrelNotificacionEmpresaSearch{

    /**
     * Representa el atributo fkEmpresa.
     *
     * @var integer
     */
    public $fkEmpresa;

    /**
     * Representa el atributo fkNotificacion.
     *
     * @var integer
     */
    public $fkNotificacion;
}
?>