<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelDocumentacionConvocatoria.
 *
 * @package dataAccess
 */
class TrelDocumentacionConvocatoriaSearch{

    /**
     * Representa el atributo fkConvocatoria.
     *
     * @var integer
     */
    public $fkConvocatoria;

    /**
     * Representa el atributo fkDocumentacion.
     *
     * @var integer
     */
    public $fkDocumentacion;
}
?>