<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelEquipamientoPlanCursoAula.
 *
 * @package dataAccess
 */
class TrelEquipamientoPlanCursoAulaSearch{

    /**
     * Representa el atributo idEquipamientoPlanCursoAula.
     *
     * @var integer
     */
    public $idEquipamientoPlanCursoAula;

    /**
     * Representa el atributo fkEquipamiento.
     *
     * @var integer
     */
    public $fkEquipamiento;

    /**
     * Representa el atributo fkPlanCursoAula.
     *
     * @var integer
     */
    public $fkPlanCursoAula;

    /**
     * Representa el atributo iCantidad.
     *
     * @var integer
     */
    public $iCantidad;

    /**
     * Representa el atributo ePrecio.
     *
     * @var string
     */
    public $ePrecio;
}
?>