<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla trelNotificacionDocumento.
 *
 * @package dataAccess
 */
class TrelNotificacionDocumentoPK{

    /**
     * Representa el atributo fkNotificacion.
     *
     * @var integer
     */
    public $fkNotificacion;

    /**
     * Representa el atributo fkDocumento.
     *
     * @var integer
     */
    public $fkDocumento;
}
?>