<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelNotificacionDocumento.
 *
 * @package dataAccess
 */
class TrelNotificacionDocumentoSearch{

    /**
     * Representa el atributo fkNotificacion.
     *
     * @var integer
     */
    public $fkNotificacion;

    /**
     * Representa el atributo fkDocumento.
     *
     * @var integer
     */
    public $fkDocumento;
}
?>