<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 02 de November de 2010 a las 12:43:47
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelProfesor.
 *
 * @package dataAccess
 */
class TrelProfesorSearch{

    /**
     * Representa el atributo fkPersona.
     *
     * @var integer
     */
    public $fkPersona;

    /**
     * Representa el atributo fkPlanCursoAula.
     *
     * @var integer
     */
    public $fkPlanCursoAula;
}
?>