<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelNotificacionEmpresa.
 *
 * @package dataAccess
 */
class TrelNotificacionEmpresaSearch{

    /**
     * Representa el atributo fkEmpresa.
     *
     * @var integer
     */
    public $fkEmpresa;

    /**
     * Representa el atributo fkNotificacion.
     *
     * @var integer
     */
    public $fkNotificacion;
}
?>