<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 29 de December de 2010 a las 10:57:19
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelEstudioPersona.
 *
 * @package dataAccess
 */
class TrelEstudioPersonaSearch{

    /**
     * Representa el atributo idEstudioPersona.
     *
     * @var integer
     */
    public $idEstudioPersona;

    /**
     * Representa el atributo fkTipoEstudio.
     *
     * @var integer
     */
    public $fkTipoEstudio;

    /**
     * Representa el atributo fkPersona.
     *
     * @var integer
     */
    public $fkPersona;

    /**
     * Representa el atributo iAnyo.
     *
     * @var string
     */
    public $iAnyo;
}
?>