<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla trelEquipamientoAula.
 *
 * @package dataAccess
 */
class TrelEquipamientoAulaPK{

    /**
     * Representa el atributo fkAula.
     *
     * @var integer
     */
    public $fkAula;

    /**
     * Representa el atributo fkEquipamiento.
     *
     * @var integer
     */
    public $fkEquipamiento;
}
?>