<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelProfesor.
 *
 * @package dataAccess
 */
class TrelProfesorSearch{

    /**
     * Representa el atributo fkPersona.
     *
     * @var integer
     */
    public $fkPersona;

    /**
     * Representa el atributo fkCurso.
     *
     * @var integer
     */
    public $fkCurso;
}
?>