<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelEquipamientoPlanCursoAula.
 *
 * @package dataAccess
 */
class TrelEquipamientoPlanCursoAulaSearch{

    /**
     * Representa el atributo idEquipamientoPlanCursoAula.
     *
     * @var integer
     */
    public $idEquipamientoPlanCursoAula;

    /**
     * Representa el atributo fkEquipamiento.
     *
     * @var integer
     */
    public $fkEquipamiento;

    /**
     * Representa el atributo fkCurso.
     *
     * @var integer
     */
    public $fkCurso;

    /**
     * Representa el atributo iCantidad.
     *
     * @var integer
     */
    public $iCantidad;

    /**
     * Representa el atributo ePrecio.
     *
     * @var string
     */
    public $ePrecio;
}
?>