<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla trelNotificacionEmpresa.
 *
 * @package dataAccess
 */
class TrelNotificacionEmpresaPK{

    /**
     * Representa el atributo fkEmpresa.
     *
     * @var integer
     */
    public $fkEmpresa;

    /**
     * Representa el atributo fkNotificacion.
     *
     * @var integer
     */
    public $fkNotificacion;
}
?>