<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 31 de January de 2011 a las 09:55:18
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelAlumno.
 *
 * @package dataAccess
 */
class TrelAlumnoSearch{

    /**
     * Representa el atributo fkPersona.
     *
     * @var integer
     */
    public $fkPersona;

    /**
     * Representa el atributo fkCurso.
     *
     * @var integer
     */
    public $fkCurso;

    /**
     * Representa el atributo dAlta.
     *
     * @var string
     */
    public $dAlta;
}
?>