<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 21 de October de 2010 a las 10:48:39
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla trelNotificacionEmpresa.
 *
 * @package dataAccess
 */
class TrelNotificacionEmpresaPK{

    /**
     * Representa el atributo fkEmpresa.
     *
     * @var integer
     */
    public $fkEmpresa;

    /**
     * Representa el atributo fkNotificacion.
     *
     * @var integer
     */
    public $fkNotificacion;
}
?>