<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:53
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelRequisitoConvocatoria.
 *
 * @package dataAccess
 */
class TrelRequisitoConvocatoriaSearch{

    /**
     * Representa el atributo fkConvocatoria.
     *
     * @var integer
     */
    public $fkConvocatoria;

    /**
     * Representa el atributo fkRequisito.
     *
     * @var integer
     */
    public $fkRequisito;
}
?>