<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 15 de November de 2010 a las 08:45:42
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelPrecandidato.
 *
 * @package dataAccess
 */
class TrelPrecandidatoSearch{

    /**
     * Representa el atributo fkPersona.
     *
     * @var integer
     */
    public $fkPersona;

    /**
     * Representa el atributo fkCurso.
     *
     * @var integer
     */
    public $fkCurso;

    /**
     * Representa el atributo dAlta.
     *
     * @var string
     */
    public $dAlta;
}
?>