<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 15 de November de 2010 a las 08:53:54
 * @package dataAccess
 */

/**
 * Objeto que representa la clave primaria de la tabla trelEquipamientoPlanCursoAula.
 *
 * @package dataAccess
 */
class TrelEquipamientoPlanCursoAulaPK{

    /**
     * Representa el atributo idEquipamientoPlanCursoAula.
     *
     * @var integer
     */
    public $idEquipamientoPlanCursoAula;
}
?>