<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelPersonaCategoria.
 *
 * @package dataAccess
 */
class TrelPersonaCategoriaSearch{

    /**
     * Representa el atributo fkPersona.
     *
     * @var integer
     */
    public $fkPersona;

    /**
     * Representa el atributo fkCategoria.
     *
     * @var integer
     */
    public $fkCategoria;
}
?>