<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 02 de November de 2010 a las 15:44:10
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelCandidato.
 *
 * @package dataAccess
 */
class TrelCandidatoSearch{

    /**
     * Representa el atributo fkPersona.
     *
     * @var integer
     */
    public $fkPersona;

    /**
     * Representa el atributo fkCurso.
     *
     * @var integer
     */
    public $fkCurso;
}
?>