<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelDocumentacionConvocatoria.
 *
 * @package dataAccess
 */
class TrelDocumentacionConvocatoriaSearch{

    /**
     * Representa el atributo fkConvocatoria.
     *
     * @var integer
     */
    public $fkConvocatoria;

    /**
     * Representa el atributo fkDocumentacion.
     *
     * @var integer
     */
    public $fkDocumentacion;
}
?>