<?php
/**
 * Este archivo ha sido generado con Ningen Dogen v.0.6
 * el 25 de October de 2010 a las 12:44:09
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelPrecandidato.
 *
 * @package dataAccess
 */
class TrelPrecandidatoSearch{

    /**
     * Representa el atributo idCandidato.
     *
     * @var integer
     */
    public $idCandidato;

    /**
     * Representa el atributo fkPersona.
     *
     * @var integer
     */
    public $fkPersona;

    /**
     * Representa el atributo fkPlanCursoCentro.
     *
     * @var integer
     */
    public $fkPlanCursoCentro;

    /**
     * Representa el atributo dAlta.
     *
     * @var string
     */
    public $dAlta;
}
?>