<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 24 de November de 2010 a las 08:55:33
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelEquipamientoAula.
 *
 * @package dataAccess
 */
class TrelEquipamientoAulaSearch{

    /**
     * Representa el atributo fkAula.
     *
     * @var integer
     */
    public $fkAula;

    /**
     * Representa el atributo fkEquipamiento.
     *
     * @var integer
     */
    public $fkEquipamiento;

    /**
     * Representa el atributo iCantidad.
     *
     * @var integer
     */
    public $iCantidad;
}
?>