<?php
/**
 * Este archivo ha sido generado con Owl Dogen v.0.6
 * el 09 de December de 2010 a las 08:48:54
 * @package dataAccess
 */

/**
 * Objeto para pasar parámetros de búsqueda al objeto TrelRolUsuario.
 *
 * @package dataAccess
 */
class TrelRolUsuarioSearch{

    /**
     * Representa el atributo fkUsuario.
     *
     * @var integer
     */
    public $fkUsuario;

    /**
     * Representa el atributo fkRol.
     *
     * @var integer
     */
    public $fkRol;
}
?>