<?

	if ( !is_null($this->planDO) ){
		
?>
	<div class="ficha">
	
			<h3>Datos generales</h3>
	
			<div class="bloque">
		
				<p><strong>Nombre</strong><span> <?= $this->planDO->getVNombre() ?></span></p>
				<p><strong>Tipo</strong><span> <?= $this->tiposPlanIDX[$this->planDO->getFkTipoPlan()] ?></span></p>
				<p><strong>Convocatoria</strong><span><a href="/convocatoria/ficha/<?= $this->planDO->getFkConvocatoria() ?>" rel="external"><?= $this->convocatoriasIDX[$this->planDO->getFkConvocatoria()] ?></a></span></p>
				<p><strong>Sector</strong><span> <?= $this->sectoresIDX[$this->planDO->getFkSector()] ?></span></p>
				<p><strong>Número de expediente</strong><span> <?= $this->planDO->getVNumeroExpediente() ?></span></p>
				<p class="estadosPlan"><strong>Estado</strong><span class="estado <?= strtolower($this->estadosPlanIDX[$this->planDO->getFkEstadoPlan()]) ?>"> <?= $this->estadosPlanIDX[$this->planDO->getFkEstadoPlan()] ?></span></p>
				<p><strong>Empresa Propietaria</strong><span> <?= $this->empresasIDX[$this->planDO->getFkEmpresaPropietaria()] ?></span></p>
				<p><strong>Consultora</strong><span> <?= $this->empresasIDX[$this->planDO->getFkEmpresaConsultora()] ?></span></p>
				<p><strong>Presupuesto</strong><span> <?= OwlNumeric::decimalFormatoEuropeo($this->planDO->getEPresupuestoAsignado(), 2) ?>€</span></p>
				<?
				
				$descripcion = $this->planDO->getVDescripcion();
				if ( !empty($descripcion) ){
					?><p class="extended"><strong>Descripción</strong><span> <?= $descripcion ?></span></p><?
				}
				
			?></div><?
		
			
			// Cursos
			$arrCursosDO = $this->planDO->getTblCursos();
			if ( !empty($arrCursosDO) ){

				?><h3>Cursos que integran este plan de formación</h3>
				<div class="scroll">
					<table class="listado fijo">
						<thead>
							<tr>
								<th>Nombre</th>
							</tr>
						</thead>
						<tbody><?
					
						$alter = true;
						foreach ( $arrCursosDO as $cursoDO ){
		
							$alter = !$alter;
							?>
							
		            		<tr <?= $alter ? 'class="alter"' : '' ?>>
		            			<td><a href="/curso/ficha/<?=$cursoDO->getIdCurso()?>"><?=$cursoDO->getVNombre()?></a></td>
		            		</tr>
		            		<?
		            		
						}
						
					?></tbody>
					</table>
				</div>
				<div class="separadorH"></div><?
			
			}
		
		?>
		</div>
<?
		
	} else {
		
		?><h3>No se ha encontrado el plan</h3><?
		
	}
?>