<?

	if ( !is_null($this->planDO) ){
		
?>
		<div class="ficha">
			<p><strong>Nombre:</strong><span> <?= $this->planDO->getVNombre() ?></span></p>
			<p><strong>Tipo:</strong><span> <?= $this->tiposPlanIDX[$this->planDO->getFkTipoPlan()] ?></span></p>
			<p><strong>Convocatoria:</strong><span> <?= $this->convocatoriasIDX[$this->planDO->getFkConvocatoria()] ?></span></p>
			<p><strong>Estado:</strong><span> <?= $this->estadosPlanIDX[$this->planDO->getFkEstadoPlan()] ?></span></p>
			<p><strong>Propietaria:</strong><span> <?= $this->empresasIDX[$this->planDO->getFkEmpresaPropietaria()] ?></span></p>
			<p><strong>Consultora:</strong><span> <?= $this->empresasIDX[$this->planDO->getFkEmpresaConsultora()] ?></span></p>
			<p><strong>Presupuesto:</strong><span> <?= NingenNumeric::decimalFormatoEuropeo($this->planDO->getEPresupuestoAsignado(), 2) ?>€</span></p>
			<?
			
			$descripcion = $this->planDO->getVDescripcion();
			if ( !empty($descripcion) ){
				?><p class="extended"><strong>Descripción:</strong><span> <?= $descripcion ?></span></p><?
			}
			
			?>
		<?
		
		// Cursos
		$arrCursosDO = $this->planDO->getTblCursos();
		if ( !empty($arrCursosDO) ){

			?><br/><h3>Cursos</h3><?
			
			foreach ( $arrCursosDO as $cursoDO ){
				echo '<p><a href="/curso/ficha/' . $cursoDO->getIdCurso() . '">' . $cursoDO->getVNombre() . '</a></span></p>';
			}
			
		}
		
		
		?>
		</div>
<?
		
	} else {
		
		?><h3>No se ha encontrado el plan</h3><?
		
	}
?>