<?php 

	if ( count($this->planesCOL) > 0 ){

?>

<table class="listado">
    <thead>
		<tr>
			<th><a href="/plan/index.html/?ob=nom&o=<?=$this->order?>" <?=( ($this->orderBy == 'nom')?'class="ordenado ' . $this->order . '"':'' )?> >Nombre</a></th>
			<th><a href="/plan/index.html/?ob=con&o=<?=$this->order?>" <?=( ($this->orderBy == 'con')?'class="ordenado ' . $this->order . '"':'' )?> >Convocatoria</a></th>
			<th><a href="/plan/index.html/?ob=tipo&o=<?=$this->order?>" <?=( ($this->orderBy == 'tipo')?'class="ordenado ' . $this->order . '"':'' )?> >Tipo</a></th>
			<th><a href="/plan/index.html/?ob=est&o=<?=$this->order?>" <?=( ($this->orderBy == 'est')?'class="ordenado ' . $this->order . '"':'' )?> >Estado</a></th>
			<th><a href="/plan/index.html/?ob=prop&o=<?=$this->order?>" <?=( ($this->orderBy == 'prop')?'class="ordenado ' . $this->order . '"':'' )?> >Propietaria</a></th>
			<th><a href="/plan/index.html/?ob=pres&o=<?=$this->order?>" <?=( ($this->orderBy == 'pres')?'class="ordenado ' . $this->order . '"':'' )?> >Presupuesto</a></th>
			<?
			
				if ( $this->editar ){
					?><th>Eliminar</th>
					<th>Editar</th>
					<th>Duplicar</th><?		
				}
			
			?>
		</tr>
	</thead>
	<tbody>
		<?php
		
			$contador = 0;
			foreach ( $this->planesCOL as $planDO ){
				
			    //$planDO = new TblPlan($db);
				$clase = ( ($contador%2)==0 )?'':'class="alter"';
				$contador++;
				
				?>
				<tr	<?= $clase ?> >
					<td><a href="/plan/ficha.html/<?= $planDO->getIdPlan() ?>"><?= $planDO->getVNombre() ?></a></td>
					<td><a href="/convocatoria/ficha.html/<?= $planDO->getFkConvocatoria() ?>"><?= $this->convocatoriasIDX[$planDO->getFkConvocatoria()] ?></a></td>
					<td><?= $this->tiposPlanIDX[$planDO->getFkTipoPlan()] ?></td>
					<td><?= $this->estadosPlanIDX[$planDO->getFkEstadoPlan()] ?></td>
					<td><?= $this->consultorasIDX[$planDO->getFkEmpresaPropietaria()] ?></td>
					<td><?= NingenNumeric::decimalFormatoEuropeo($planDO->getEPresupuestoAsignado(), 2) ?>€</td>
					<?
			
						if ( $this->editar ){
							?><td class="accion"><a href="javascript:ventanaConfirmacion('Confirmar','¿Está seguro que desea eliminar el plan <strong><?= $planDO->getVNombre() ?></strong>?','/plan/eliminar.html/<?= $planDO->getIdPlan() ?>')" class="btnEliminar" title="Eliminar Plan"><span>eliminar</span></a></td>
							<td class="accion"><a href="/plan/editar.html/<?= $planDO->getIdPlan() ?>" class="btnEditar" title="Editar Plan"><span>editar</span></a></td>
							<td class="accion"><a href="/plan/duplicar.html/<?= $planDO->getIdPlan() ?>" class="btnDuplicar" title="Duplicar Plan"><span>duplicar</span></a></td><?	
						}
					
					?>
				</tr>
				<?
				
			}
			
		?>
	</tbody>
</table>
<div id="paginadorContainer"><?= $this->paginador ?></div>
<?php 

	} else {

?>

<h3>No hay ningún plan</h3>

<?php 

	}

?>